import { useEffect, useMemo, useState, type FormEvent } from 'react';
import OpsVistaCopilot from './OpsVistaCopilot';
import OpsVistaDatePicker from './OpsVistaDatePicker';
import { permissionsFor, type OpsVistaUser } from './accessControl';
import type { ActionRecord, ActionSeverity, ActionStatus } from './actionCenterTypes';
import type { VerificationStatus } from './verificationLoop';
import './actionCenter.css';

type AuditRow={id:string;at:string;actor_name:string;event:string;before_value?:string;after_value?:string;reason:string};
type Assignee={id:string;name:string;title:string;role:string;locations:string[]};
type Props={currentUser:OpsVistaUser;allowedLocations:string[];initialSearch?:string;initialRecordId?:string;initialLocation?:string};
const statuses:ActionStatus[]=['Open','Assigned','Investigating','Completed','Dismissed'];
const severities:ActionSeverity[]=['High','Medium','Low'];
const api='/api/workflows?resource=actions';
const dateTime=(value?:string)=>value?new Date(value).toLocaleString('en-US',{timeZone:'America/New_York'}):'—';
const easternDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const displayDate=(value?:string)=>value?new Date(`${value.slice(0,10)}T12:00:00Z`).toLocaleDateString('en-US',{timeZone:'UTC'}):'—';

export default function ActionCenterView({currentUser,allowedLocations,initialSearch,initialRecordId,initialLocation}:Props){
  const permissions=permissionsFor(currentUser);
  const [actions,setActions]=useState<ActionRecord[]>([]);
  const [assignees,setAssignees]=useState<Assignee[]>([]);
  const [selectedId,setSelectedId]=useState(initialRecordId||'');
  const [audit,setAudit]=useState<AuditRow[]>([]);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState('');
  const [location,setLocation]=useState(initialLocation&&allowedLocations.includes(initialLocation)?initialLocation:'All locations');
  const [status,setStatus]=useState(initialSearch||initialRecordId?'All':'Active');
  const [ownership,setOwnership]=useState(currentUser.role==='Location Manager'?'My actions':'All actions');
  const [search,setSearch]=useState(initialSearch||'');
  const [showCreate,setShowCreate]=useState(false);
  const [ownerId,setOwnerId]=useState('');
  const [dueAt,setDueAt]=useState('');
  const [verificationStatus,setVerificationStatus]=useState<VerificationStatus>('Not enough evidence yet');
  const [verificationNote,setVerificationNote]=useState('');
  const [form,setForm]=useState({title:'',location:allowedLocations[0]||'',category:'Operations',severity:'Medium' as ActionSeverity,signal:'',cause:'',recommendation:'',impact:''});

  const locationScopeKey=allowedLocations.join('|');
  const load=async()=>{setLoading(true);setError('');try{const response=await fetch(api,{credentials:'include',cache:'no-store'});const body=await response.json().catch(()=>({})) as {actions?:ActionRecord[];assignees?:Assignee[];error?:string};if(!response.ok)throw new Error(body.error||'Action Center unavailable');const scope=new Set(allowedLocations);const scoped=(body.actions||[]).filter(item=>scope.has(item.location));setActions(scoped);setAssignees(body.assignees||[]);setSelectedId(current=>initialRecordId&&scoped.some(item=>item.id===initialRecordId)?initialRecordId:scoped.some(item=>item.id===current)?current:(scoped[0]?.id||''));}catch(e){setError(e instanceof Error?e.message:'Action Center unavailable');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[locationScopeKey]);
  useEffect(()=>{if(initialSearch||initialRecordId){setSearch(initialSearch||'');setStatus('All');setLocation(initialLocation&&allowedLocations.includes(initialLocation)?initialLocation:'All locations');if(initialRecordId)setSelectedId(initialRecordId);}},[initialSearch,initialRecordId,initialLocation,locationScopeKey]);
  const selected=actions.find(item=>item.id===selectedId);
  useEffect(()=>{if(!selected){setAudit([]);return;}setOwnerId(selected.ownerId||assignees.find(user=>user.name===selected.ownerName)?.id||'');setDueAt(selected.dueAt?.slice(0,10)||'');setVerificationStatus(selected.verificationStatus==='Pending'?'Not enough evidence yet':selected.verificationStatus);setVerificationNote(selected.verificationNote||'');fetch(`${api}&id=${encodeURIComponent(selected.id)}`,{credentials:'include',cache:'no-store'}).then(response=>response.json()).then((body:{audit?:AuditRow[]})=>setAudit(body.audit||[])).catch(()=>setAudit([]));},[selected?.id,assignees.length]);

  const filtered=useMemo(()=>actions.filter(action=>{const matchesLocation=location==='All locations'||action.location===location;const matchesStatus=status==='All'||(status==='Active'?!['Completed','Dismissed'].includes(action.status):action.status===status);const matchesOwner=ownership==='All actions'||action.ownerId===currentUser.id;const q=search.trim().toLowerCase();const matchesSearch=!q||[action.title,action.location,action.category,action.ownerName,action.accountableName,action.accountableRole,action.signal].filter(Boolean).join(' ').toLowerCase().includes(q);return matchesLocation&&matchesStatus&&matchesOwner&&matchesSearch;}).sort((a,b)=>(b.priorityScore||0)-(a.priorityScore||0)||new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()),[actions,location,status,ownership,search,currentUser.id]);
  const open=actions.filter(item=>!['Completed','Dismissed'].includes(item.status));
  const myActions=open.filter(item=>item.ownerId===currentUser.id);
  const assigneesFor=(actionLocation:string)=>assignees.filter(user=>!user.locations.length||user.locations.includes(actionLocation));
  const selectedOwner=assignees.find(user=>user.id===ownerId);
  const update=async(id:string,patch:Record<string,unknown>,reason:string)=>{setSaving(true);setError('');try{const response=await fetch(api,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch,reason})});const body=await response.json().catch(()=>({})) as {action?:ActionRecord;error?:string};if(!response.ok||!body.action)throw new Error(body.error||'Action could not be updated');setActions(items=>items.map(item=>item.id===id?body.action!:item));const detail=await fetch(`${api}&id=${encodeURIComponent(id)}`,{credentials:'include',cache:'no-store'}).then(r=>r.json()) as {audit?:AuditRow[]};setAudit(detail.audit||[]);}catch(e){setError(e instanceof Error?e.message:'Action could not be updated');}finally{setSaving(false);}};
  const verify=()=>{if(!selected||!verificationNote.trim())return;const nextStatus=verificationStatus==='Worked'?'Completed':verificationStatus==='Did not work'?'Investigating':'Assigned';void update(selected.id,{verificationStatus,verificationNote:verificationNote.trim(),verifiedAt:new Date().toISOString(),status:nextStatus},'Verification result applied');};
  const create=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const response=await fetch(api,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,ownerId:ownerId||undefined,ownerName:selectedOwner?.name,dueAt:dueAt||undefined,priorityScore:form.severity==='High'?80:form.severity==='Medium'?50:25,sources:['Manual Action Center']})});const body=await response.json().catch(()=>({})) as {action?:ActionRecord;error?:string};if(!response.ok||!body.action)throw new Error(body.error||'Action could not be created');setActions(items=>[body.action!,...items]);setSelectedId(body.action.id);setShowCreate(false);setForm({...form,title:'',signal:'',cause:'',recommendation:'',impact:''});}catch(e){setError(e instanceof Error?e.message:'Action could not be created');}finally{setSaving(false);}};
  const copilotActions=actions.map(item=>({...item,id:item.id,owner:item.ownerName}));
  useEffect(()=>{if(!filtered.some(item=>item.id===selectedId))setSelectedId(filtered[0]?.id||'');},[filtered,selectedId]);

  return <div className="action-center-live">
    <section className="action-live-toolbar"><div><strong>Persistent operational workflow</strong><span>Every assignment, status change and verification is saved with an audit trail.</span></div><div><select value={ownership} onChange={e=>setOwnership(e.target.value)}><option>My actions</option><option>All actions</option></select><select value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option>{allowedLocations.map(item=><option key={item}>{item}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>Active</option><option>All</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><button onClick={()=>setShowCreate(true)} disabled={!permissions.canEscalateActions}>+ New action</button></div></section>
    {error&&<div className="action-live-error">{error}</div>}
    <section className="metrics-grid action-live-metrics"><div className="metric-card my-actions-card" onClick={()=>setOwnership('My actions')} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setOwnership('My actions');}}} role="button" tabIndex={0}><div className="metric-label">MY ACTIONS</div><div className="metric-value">{myActions.length}</div><div className="metric-note">Assigned directly to {currentUser.name}</div></div><div className="metric-card"><div className="metric-label">OPEN ACTIONS</div><div className="metric-value">{open.length}</div><div className="metric-note">Saved in OpsVista</div></div><div className="metric-card"><div className="metric-label">HIGH PRIORITY</div><div className="metric-value warn">{open.filter(item=>item.severity==='High').length}</div><div className="metric-note">Requires immediate ownership</div></div><div className="metric-card"><div className="metric-label">UNASSIGNED</div><div className="metric-value">{open.filter(item=>!item.ownerName).length}</div><div className="metric-note">No responsible person</div></div><div className="metric-card"><div className="metric-label">OVERDUE</div><div className="metric-value warn">{open.filter(item=>item.dueAt&&item.dueAt<easternDate()).length}</div><div className="metric-note">Past assigned deadline</div></div><div className="metric-card"><div className="metric-label">VERIFIED WORKED</div><div className="metric-value">{actions.filter(item=>item.verificationStatus==='Worked').length}</div><div className="metric-note">Closed with evidence</div></div></section>
    {permissions.canUseCopilot&&<OpsVistaCopilot actions={copilotActions} selected={selected?{...selected,id:selected.id,owner:selected.ownerName}:undefined}/>}
    <section className="action-live-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search action, location, category or owner…"/><button onClick={()=>void load()} disabled={loading}>{loading?'Loading…':'Refresh actions'}</button></section>
    <div className="content-grid action-live-grid"><section className="panel action-list-panel"><div className="panel-header"><div><h2>{ownership==='My actions'?'My Actions':'Needs Action'}</h2><p>{ownership==='My actions'?'Work assigned directly to your OpsVista profile.':'Persistent actions inside your authorized locations.'}</p></div><span className="count-pill">{filtered.length}</span></div><div className="action-list">{!loading&&!filtered.length&&<div className="action-live-empty">No actions match this scope. No test actions were inserted.</div>}{filtered.map(item=><button key={item.id} className={`action-row ${selected?.id===item.id?'selected':''}`} onClick={()=>setSelectedId(item.id)}><div className={`severity ${item.severity.toLowerCase()}`}>{item.severity==='High'?'!':item.severity==='Medium'?'•':'○'}</div><div className="action-main"><div className="action-meta"><span>{item.location}</span><span>•</span><span>{item.category}</span>{item.ownerId===currentUser.id&&<><span>•</span><span className="my-action-chip">MY ACTION</span></>}{item.automated&&<><span>•</span><span>AUTO · {item.priorityScore}/100</span></>}</div><strong>{item.title}</strong><p>{item.signal}</p><div className="action-footer"><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span><span className="impact">{item.ownerName||'Unassigned'}{item.dueAt?` · due ${displayDate(item.dueAt)}`:''}</span></div></div><span className="chev">›</span></button>)}</div></section>
      {selected&&<section className="panel detail-panel"><div className="detail-top"><div><span className={`severity-label ${selected.severity.toLowerCase()}`}>{selected.severity} priority</span><h2>{selected.title}</h2><p>{selected.location} · {selected.category} · Updated {dateTime(selected.updatedAt)}</p></div></div>{selected.accountableName&&<div className="action-accountability-subject"><span>REQUIRES CORRECTION / FOLLOW-UP</span><strong>{selected.accountableName}</strong><small>{selected.accountableRole||'Operational exception source'}</small></div>}<div className="detail-block"><label>SIGNAL</label><p>{selected.signal}</p></div><div className="detail-block"><label>LIKELY CAUSE</label><p>{selected.cause}</p></div><div className="detail-block recommendation"><label>OPSVISTA RECOMMENDATION</label><p>{selected.recommendation}</p></div>{permissions.canSeeFinancialImpact&&<div className="impact-box"><span>Estimated impact</span><strong>{selected.impact}</strong></div>}{selected.sourceUrl&&<a className="action-source-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source transaction in Ramp ↗</a>}<div className="action-assignment"><label>FOLLOW-UP OWNER<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Unassigned</option>{assigneesFor(selected.location).map(user=><option key={user.id} value={user.id}>{user.name} · {user.title}</option>)}</select></label><label>DUE DATE<OpsVistaDatePicker value={dueAt} onChange={setDueAt} ariaLabel="Select action due date"/></label><button disabled={saving} onClick={()=>void update(selected.id,{status:ownerId?'Assigned':'Open',ownerId,ownerName:selectedOwner?.name,dueAt:dueAt||undefined},'Responsible user and deadline assigned')}>Save assignment</button></div>{permissions.canEscalateActions&&<div className="action-buttons"><button className="primary" disabled={saving} onClick={()=>void update(selected.id,{status:'Investigating'},'Investigation started')}>Investigate</button><button disabled={saving} onClick={()=>void update(selected.id,{status:'Dismissed'},'Action dismissed')}>Dismiss</button></div>}{permissions.canVerifyActions&&<section className="action-verification"><div><span>VERIFICATION LOOP</span><strong>Did the action work?</strong></div><select value={verificationStatus} onChange={e=>setVerificationStatus(e.target.value as VerificationStatus)}><option>Worked</option><option>Did not work</option><option>Not enough evidence yet</option></select><textarea value={verificationNote} onChange={e=>setVerificationNote(e.target.value)} placeholder="Required: describe the evidence or measured result…"/><button disabled={saving||!verificationNote.trim()} onClick={verify}>Save verified result</button></section>}<div className="action-audit"><h3>Audit history</h3>{audit.map(row=><div key={row.id}><strong>{row.event}</strong><span>{row.actor_name} · {dateTime(row.at)}</span><p>{row.reason}</p></div>)}{!audit.length&&<p>No audit events returned.</p>}</div></section>}
    </div>
    {showCreate&&<div className="action-modal-backdrop" onClick={()=>setShowCreate(false)}><form className="action-modal" onSubmit={create} onClick={e=>e.stopPropagation()}><div className="action-modal-head"><div><span>NEW OPERATIONAL ACTION</span><h2>Create action</h2></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><div className="action-form-grid"><label>Location<select value={form.location} onChange={e=>{setForm({...form,location:e.target.value});setOwnerId('');}} required>{allowedLocations.map(item=><option key={item}>{item}</option>)}</select></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/></label><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value as ActionSeverity})}>{severities.map(item=><option key={item}>{item}</option>)}</select></label><label>Responsible<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Unassigned</option>{assigneesFor(form.location).map(user=><option key={user.id} value={user.id}>{user.name} · {user.title}</option>)}</select></label><label>Due date<OpsVistaDatePicker value={dueAt} onChange={setDueAt} ariaLabel="Select action due date"/></label></div><label>Signal<textarea value={form.signal} onChange={e=>setForm({...form,signal:e.target.value})} required/></label><label>Likely cause<textarea value={form.cause} onChange={e=>setForm({...form,cause:e.target.value})} required/></label><label>Recommended action<textarea value={form.recommendation} onChange={e=>setForm({...form,recommendation:e.target.value})} required/></label><label>Expected impact<input value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}/></label><button className="action-create-submit" disabled={saving}>{saving?'Saving…':'Create persistent action'}</button></form></div>}
  </div>;
}
