import { useEffect, useMemo, useState, type FormEvent } from 'react';
import OpsVistaDatePicker from './OpsVistaDatePicker';
import NotificationEmailPanel from './NotificationEmailPanel';
import { useI18n } from './i18n';
import { actionViews, matchesActionFilters, matchesActionSearch, type ActionFilters } from './actionViews';
import { permissionsFor, type OpsVistaUser } from './accessControl';
import type { ActionNotificationDetail, ActionRecord, ActionSeverity, ActionStatus } from './actionCenterTypes';
import type { VerificationStatus } from './verificationLoop';
import './actionCenter.css';
import ActionAssignmentOverview from './ActionAssignmentOverview';
import { actionOwnerKey, actionIsOpen, actionIsOverdue } from './actionAssignments';

type AuditRow={id:string;at:string;actor_name:string;event:string;before_value?:string;after_value?:string;reason:string};
type Assignee={id:string;name:string;title:string;role:string;locations:string[]};
type SuggestedAssignee={id:string;name:string;title:string;reason:string};
type Props={currentUser:OpsVistaUser;allowedLocations:string[];initialSearch?:string;initialRecordId?:string;initialLocation?:string;canTestNotifications?:boolean};
const statuses:ActionStatus[]=['Open','Assigned','Investigating','Completed','Dismissed'];
const severities:ActionSeverity[]=['High','Medium','Low'];
const api='/api/workflows?resource=actions';
const dateTime=(value?:string)=>value?new Date(value).toLocaleString('en-US',{timeZone:'America/New_York'}):'—';
const easternDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const displayDate=(value?:string)=>value?new Date(`${value.slice(0,10)}T12:00:00Z`).toLocaleDateString('en-US',{timeZone:'UTC'}):'—';

export default function ActionCenterView({currentUser,allowedLocations,initialSearch,initialRecordId,initialLocation,canTestNotifications=true}:Props){
  const {t}=useI18n();
  const permissions=permissionsFor(currentUser);
  const corporateView=['Founder','Corporate'].includes(currentUser.role);
  const [responsibleFilter,setResponsibleFilter]=useState('');
  const [showAssignments,setShowAssignments]=useState(corporateView);
  const [actions,setActions]=useState<ActionRecord[]>([]);
  const [assignees,setAssignees]=useState<Assignee[]>([]);
  const [selectedId,setSelectedId]=useState(initialRecordId||'');
  const [audit,setAudit]=useState<AuditRow[]>([]);
  const [notification,setNotification]=useState<ActionNotificationDetail>({state:null,events:[]});
  const [suggestions,setSuggestions]=useState<SuggestedAssignee[]>([]);
  const [suggestionStrategy,setSuggestionStrategy]=useState('');
  const [onDutyVerified,setOnDutyVerified]=useState(false);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState('');
  const [location,setLocation]=useState(initialLocation&&allowedLocations.includes(initialLocation)?initialLocation:'All locations');
  const [status,setStatus]=useState(initialSearch||initialRecordId?'All':'Active');
  const [ownership,setOwnership]=useState(!initialSearch&&!initialRecordId&&currentUser.role==='Location Manager'?'My actions':'All actions');
  const [search,setSearch]=useState(initialSearch||'');
  const [showCreate,setShowCreate]=useState(false);
  const [ownerId,setOwnerId]=useState('');
  const [dueAt,setDueAt]=useState('');
  const [verificationStatus,setVerificationStatus]=useState<VerificationStatus>('Not enough evidence yet');
  const [verificationNote,setVerificationNote]=useState('');
  const [form,setForm]=useState({title:'',location:allowedLocations[0]||'',category:'Operations',severity:'Medium' as ActionSeverity,signal:'',cause:'',recommendation:'',impact:''});

  const locationScopeKey=allowedLocations.join('|');
  const load=async()=>{setLoading(true);setError('');try{const response=await fetch(api,{credentials:'include',cache:'no-store'});const body=await response.json().catch(()=>({})) as {actions?:ActionRecord[];assignees?:Assignee[];error?:string};if(!response.ok)throw new Error(body.error||'Action Center unavailable');const scope=new Set(allowedLocations);const scoped=(body.actions||[]).filter(item=>scope.has(item.location));setActions(scoped);setAssignees(body.assignees||[]);setSelectedId(current=>initialRecordId&&scoped.some(item=>item.id===initialRecordId)?initialRecordId:scoped.some(item=>item.id===current)?current:(scoped[0]?.id||''));}catch(e){setError(e instanceof Error?e.message:'Action Center unavailable');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[locationScopeKey]);
  useEffect(()=>{if(initialSearch||initialRecordId){setSearch(initialSearch||'');setStatus('All');setOwnership('All actions');setResponsibleFilter('');setLocation(initialLocation&&allowedLocations.includes(initialLocation)?initialLocation:'All locations');if(initialRecordId)setSelectedId(initialRecordId);}},[initialSearch,initialRecordId,initialLocation,locationScopeKey]);
  const today=easternDate();
  const assignmentScope=useMemo(()=>actions.filter(item=>allowedLocations.includes(item.location)
    &&(location==='All locations'||item.location===location)&&matchesActionSearch(item,search)),[actions,location,search,locationScopeKey]);
  const filtered=useMemo(()=>assignmentScope.filter(action=>matchesActionFilters(action,{status,ownership,responsibleFilter},currentUser.id,today))
    .sort((a,b)=>(status==='History'?0:(b.priorityScore||0)-(a.priorityScore||0))
      ||new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()),[assignmentScope,status,ownership,responsibleFilter,currentUser.id,today]);
  const activeView=actionViews.find(view=>view.status===status&&view.ownership===ownership&&view.responsibleFilter===responsibleFilter);
  const selectView=(view:ActionFilters)=>{setStatus(view.status);setOwnership(view.ownership);setResponsibleFilter(view.responsibleFilter);};
  const selected=filtered.find(item=>item.id===selectedId)||filtered[0];
  useEffect(()=>{let cancelled=false;setAudit([]);setNotification({state:null,events:[]});setSuggestions([]);if(!selected)return;setOwnerId(selected.ownerId||assignees.find(user=>user.name===selected.ownerName)?.id||'');setDueAt(selected.dueAt?.slice(0,10)||'');setVerificationStatus(selected.verificationStatus==='Pending'?'Not enough evidence yet':selected.verificationStatus);setVerificationNote(selected.verificationNote||'');Promise.all([
    fetch(`${api}&id=${encodeURIComponent(selected.id)}`,{credentials:'include',cache:'no-store'}).then(response=>response.json()) as Promise<{audit?:AuditRow[];notification?:ActionNotificationDetail}>,
    fetch(`/api/workflows?resource=action_suggestions&location=${encodeURIComponent(selected.location)}&category=${encodeURIComponent(selected.category)}`,{credentials:'include',cache:'no-store'}).then(response=>response.json()) as Promise<{suggestions?:SuggestedAssignee[];strategy?:string;onDutyVerified?:boolean}>,
  ]).then(([detail,suggested])=>{if(cancelled)return;setAudit(detail.audit||[]);setNotification(detail.notification||{state:null,events:[]});setSuggestions(suggested.suggestions||[]);setSuggestionStrategy(suggested.strategy||'');setOnDutyVerified(Boolean(suggested.onDutyVerified));}).catch(()=>{if(cancelled)return;setAudit([]);setNotification({state:null,events:[]});setSuggestions([]);});return()=>{cancelled=true;};},[selected?.id,assignees.length]);

  const responsibleOptions=Array.from(new Map(actions.filter(action=>allowedLocations.includes(action.location)).map(action=>{
    const key=actionOwnerKey(action);
    return [key,{key,name:assignees.find(person=>person.id===action.ownerId)?.name||action.ownerName||t('Unassigned','Sin asignar')}];
  })).values()).sort((a,b)=>a.name.localeCompare(b.name));
  const metricsScope=assignmentScope.filter(item=>(ownership==='All actions'||item.ownerId===currentUser.id)&&(!responsibleFilter||actionOwnerKey(item)===responsibleFilter));
  const open=metricsScope.filter(actionIsOpen);
  const selectResponsible=(owner:string,nextStatus:string)=>{setResponsibleFilter(owner);setOwnership('All actions');setStatus(nextStatus);};
  const myActions=assignmentScope.filter(item=>actionIsOpen(item)&&item.ownerId===currentUser.id);
  const assigneesFor=(actionLocation:string)=>assignees.filter(user=>!user.locations.length||user.locations.includes(actionLocation));
  const selectedOwner=assignees.find(user=>user.id===ownerId);
  const update=async(id:string,patch:Record<string,unknown>,reason:string)=>{setSaving(true);setError('');try{const response=await fetch(api,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch,reason})});const body=await response.json().catch(()=>({})) as {action?:ActionRecord;error?:string};if(!response.ok||!body.action)throw new Error(body.error||'Action could not be updated');setActions(items=>items.map(item=>item.id===id?body.action!:item));const detail=await fetch(`${api}&id=${encodeURIComponent(id)}`,{credentials:'include',cache:'no-store'}).then(r=>r.json()) as {audit?:AuditRow[];notification?:ActionNotificationDetail};setAudit(detail.audit||[]);setNotification(detail.notification||{state:null,events:[]});}catch(e){setError(e instanceof Error?e.message:'Action could not be updated');}finally{setSaving(false);}};
  const quickAssign=(suggestion:SuggestedAssignee)=>{if(!selected)return;setOwnerId(suggestion.id);void update(selected.id,{status:'Assigned',ownerId:suggestion.id,dueAt:dueAt||undefined,resendNotification:true,acceptWithinMinutes:suggestionStrategy==='maintenance'?10:suggestionStrategy==='commercial'?15:30},`Smart assignment sent to ${suggestion.name}`);};
  const recordReceipt=async(status:'Seen'|'Accepted'|'In progress'|'Evidence submitted')=>{if(!selected)return;setSaving(true);setError('');try{const response=await fetch('/api/workflows?resource=action_notifications',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({actionId:selected.id,status})});const body=await response.json().catch(()=>({})) as ActionNotificationDetail&{error?:string};if(!response.ok)throw new Error(body.error||'Receipt could not be saved');setNotification(body);await load();}catch(e){setError(e instanceof Error?e.message:'Receipt could not be saved');}finally{setSaving(false);}};
  const verify=()=>{if(!selected||!verificationNote.trim())return;const nextStatus=verificationStatus==='Worked'?'Completed':verificationStatus==='Did not work'?'Investigating':'Assigned';void update(selected.id,{verificationStatus,verificationNote:verificationNote.trim(),verifiedAt:new Date().toISOString(),status:nextStatus},'Verification result applied');};
  const create=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const response=await fetch(api,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,ownerId:ownerId||undefined,ownerName:selectedOwner?.name,dueAt:dueAt||undefined,priorityScore:form.severity==='High'?80:form.severity==='Medium'?50:25,sources:['Manual Action Center']})});const body=await response.json().catch(()=>({})) as {action?:ActionRecord;error?:string};if(!response.ok||!body.action)throw new Error(body.error||'Action could not be created');setActions(items=>[body.action!,...items]);setResponsibleFilter('');setOwnership('All actions');setStatus('All');setLocation(body.action.location);setSearch('');setSelectedId(body.action.id);setShowCreate(false);setForm({...form,title:'',signal:'',cause:'',recommendation:'',impact:''});}catch(e){setError(e instanceof Error?e.message:'Action could not be created');}finally{setSaving(false);}};

  return <div className="action-center-live">
    <div className="action-view-tabs" role="group" aria-label={t('Action views','Vistas de acciones')}>
      {actionViews.map(view=><button key={view.id} type="button" data-action-view={view.id}
        aria-pressed={activeView?.id===view.id} onClick={()=>selectView(view)}>
        {t(view.en,view.es)} <span>{loading?'—':assignmentScope.filter(action=>matchesActionFilters(action,view,currentUser.id,today)).length}</span>
      </button>)}
    </div>
    {canTestNotifications&&<NotificationEmailPanel/>}
    <section className="action-live-toolbar"><div><strong>{t('Actions, priorities and follow-up','Acciones, prioridades y seguimiento')}</strong><span>{t('Filter by location or owner. Every change stays in the action history.','Filtra por locación o responsable. Cada cambio queda en el historial de la acción.')}</span></div><div><select aria-label="Ámbito de asignaciones" value={ownership} onChange={e=>{setOwnership(e.target.value);setResponsibleFilter('');}}><option value="My actions">{t('My actions','Mis acciones')}</option><option value="All actions">{t('All actions','Todas las acciones')}</option></select><select aria-label="Locación de las acciones" value={location} onChange={e=>setLocation(e.target.value)}><option value="All locations">{t('All locations','Todas las locaciones')}</option>{allowedLocations.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Estado de las acciones" value={status} onChange={e=>setStatus(e.target.value)}><option value="Active">{t('Active','Activas')}</option><option value="All">{t('All statuses','Todos los estados')}</option><option value="High priority">{t('High priority','Alta prioridad')}</option><option value="Overdue">{t('Overdue','Vencidas')}</option><option value="History">{t('History','Historial')}</option><option value="No date">{t('No date','Sin fecha')}</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><select aria-label="Responsable de seguimiento" value={responsibleFilter} onChange={e=>selectResponsible(e.target.value,status)}><option value="">{t('All owners','Todos los responsables')}</option><option value="__unassigned">{t('Unassigned','Sin asignar')}</option>{responsibleOptions.filter(person=>person.key!=='__unassigned').map(person=><option key={person.key} value={person.key}>{person.name}</option>)}</select>{corporateView&&<button aria-pressed={showAssignments} onClick={()=>setShowAssignments(value=>!value)}>{showAssignments?t('Hide owners','Ocultar responsables'):t('By owner','Por responsable')}</button>}<button onClick={()=>{setOwnerId('');setDueAt('');setShowCreate(true);}} disabled={!permissions.canEscalateActions}>{t('+ New action','+ Nueva acción')}</button></div></section>
    {error&&<div className="action-live-error">{error}</div>}
    <section className="metrics-grid action-live-metrics"><div className="metric-card my-actions-card" onClick={()=>selectView(actionViews[1])} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectView(actionViews[1]);}}} role="button" tabIndex={0}><div className="metric-label">MY ACTIONS</div><div className="metric-value">{myActions.length}</div><div className="metric-note">Assigned directly to {currentUser.name}</div></div><div className="metric-card"><div className="metric-label">OPEN ACTIONS</div><div className="metric-value">{open.length}</div><div className="metric-note">Saved in OpsVista</div></div><div className="metric-card"><div className="metric-label">HIGH PRIORITY</div><div className="metric-value warn">{open.filter(item=>item.severity==='High').length}</div><div className="metric-note">Requires immediate ownership</div></div><div className="metric-card"><div className="metric-label">UNASSIGNED</div><div className="metric-value">{open.filter(item=>actionOwnerKey(item)==='__unassigned').length}</div><div className="metric-note">No responsible person</div></div><div className="metric-card"><div className="metric-label">OVERDUE</div><div className="metric-value warn">{open.filter(item=>actionIsOverdue(item,easternDate())).length}</div><div className="metric-note">Past assigned deadline</div></div><div className="metric-card"><div className="metric-label">VERIFIED WORKED</div><div className="metric-value">{metricsScope.filter(item=>item.status==='Completed'&&item.verificationStatus==='Worked').length}</div><div className="metric-note">Closed with evidence</div></div></section>
    <section className="action-live-search"><input value={search} onChange={e=>setSearch(e.target.value)} aria-label={t('Search actions','Buscar acciones')} placeholder={t('Search action, location, category or owner…','Buscar acción, locación, categoría o responsable…')}/><button onClick={()=>void load()} disabled={loading}>{loading?t('Loading…','Cargando…'):t('Refresh actions','Actualizar acciones')}</button></section>
    {corporateView&&showAssignments&&<ActionAssignmentOverview actions={assignmentScope} people={assignees} today={easternDate()} selectedOwner={responsibleFilter} loading={loading} onSelect={selectResponsible}/>}
    {responsibleFilter&&<div className="action-owner-selection"><strong>{responsibleFilter==='__unassigned'?t('Unassigned','Sin asignar'):responsibleOptions.find(person=>person.key===responsibleFilter)?.name||t('Selected owner','Responsable seleccionado')}</strong><span>{filtered.length} acciones · {status==='Overdue'?'Vencidas':status==='No date'?'Sin fecha':status==='All'?'Todos los estados':status==='Active'?'Pendientes':status}</span><button onClick={()=>selectResponsible('','Active')}>Quitar filtro</button></div>}
    <div className="content-grid action-live-grid"><section className="panel action-list-panel"><div className="panel-header"><div><h2>{activeView?t(activeView.en,activeView.es):t('Filtered actions','Acciones filtradas')}</h2><p>{status==='History'?t('Completed and dismissed actions, with their original history.','Acciones completadas y descartadas, con su historial original.'):t('Actions in your authorized locations.','Acciones de tus locaciones autorizadas.')}</p></div><span className="count-pill">{filtered.length}</span></div><div className="action-list">{!loading&&!filtered.length&&<div className="action-live-empty">{t('No actions match these filters.','No hay acciones que coincidan con estos filtros.')}</div>}{filtered.map(item=><button key={item.id} className={`action-row ${selected?.id===item.id?'selected':''}`} onClick={()=>setSelectedId(item.id)}><div className={`severity ${item.severity.toLowerCase()}`}>{item.severity==='High'?'!':item.severity==='Medium'?'•':'○'}</div><div className="action-main"><div className="action-meta"><span>{item.location}</span><span>•</span><span>{item.category}</span>{item.ownerId===currentUser.id&&<><span>•</span><span className="my-action-chip">MY ACTION</span></>}{item.automated&&<><span>•</span><span>AUTO · {item.priorityScore}/100</span></>}</div><strong>{item.title}</strong><p>{item.signal}</p><div className="action-footer"><span className={`status ${item.status.toLowerCase()}`}>{item.status}</span><span className="impact">{item.ownerName||'Unassigned'}{item.dueAt?` · due ${displayDate(item.dueAt)}`:''}</span></div></div><span className="chev">›</span></button>)}</div></section>
      {selected&&<section className="panel detail-panel"><div className="detail-top"><div><span className={`severity-label ${selected.severity.toLowerCase()}`}>{selected.severity} priority</span><h2>{selected.title}</h2><p>{selected.location} · {selected.category} · Updated {dateTime(selected.updatedAt)}</p></div></div>{selected.accountableName&&<div className="action-accountability-subject"><span>REQUIRES CORRECTION / FOLLOW-UP</span><strong>{selected.accountableName}</strong><small>{selected.accountableRole||'Operational exception source'}</small></div>}<div className="detail-block"><label>SIGNAL</label><p>{selected.signal}</p></div><div className="detail-block"><label>LIKELY CAUSE</label><p>{selected.cause}</p></div><div className="detail-block recommendation"><label>OPSVISTA RECOMMENDATION</label><p>{selected.recommendation}</p></div>
        {permissions.canEscalateActions&&<section className="action-smart-assignment"><div><span>SMART ASSIGNMENT</span><strong>{suggestionStrategy==='maintenance'?'Send to Maintenance':suggestionStrategy==='commercial'?'Send sales coaching':'Send to manager on duty'}</strong><small>{suggestionStrategy==='manager_on_duty'?(onDutyVerified?'Verified against the live 7shifts schedule':'7shifts unavailable · showing authorized location managers'):'OpsVista selected the responsible role for this alert'}</small></div><div>{suggestions.map(suggestion=><button key={suggestion.id} disabled={saving} onClick={()=>quickAssign(suggestion)}><b>Send to {suggestion.name}</b><small>{suggestion.reason}</small></button>)}{!suggestions.length&&<em>No eligible responsible user found.</em>}</div></section>}
        {permissions.canSeeFinancialImpact&&<div className="impact-box"><span>Estimated impact</span><strong>{selected.impact}</strong></div>}{selected.sourceUrl&&<a className="action-source-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source transaction in Ramp ↗</a>}<div className="action-assignment"><label>FOLLOW-UP OWNER<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Unassigned</option>{assigneesFor(selected.location).map(user=><option key={user.id} value={user.id}>{user.name} · {user.title}</option>)}</select></label><label>DUE DATE<OpsVistaDatePicker value={dueAt} onChange={setDueAt} ariaLabel="Select action due date"/></label><button disabled={saving} onClick={()=>void update(selected.id,{status:ownerId?'Assigned':'Open',ownerId,ownerName:selectedOwner?.name,dueAt:dueAt||undefined,resendNotification:Boolean(ownerId),acceptWithinMinutes:30},'Responsible user and deadline assigned')}>Save & notify</button></div>
        {notification.state&&<section className="action-receipts"><div className="action-receipts-head"><div><span>PUSH ACCOUNTABILITY</span><strong>{notification.state.latestStatus}</strong></div><small>Accept by {dateTime(notification.state.acceptBy)}</small></div><div className="receipt-steps">{['Sent','Push accepted','Delivered','Seen','Accepted','In progress','Evidence submitted','Verified'].map(step=><i key={step} className={notification.events.some(event=>event.status===step)||notification.state?.latestStatus===step?'complete':''}>{step}</i>)}</div><div className="receipt-timeline">{notification.events.slice(0,6).map(event=><p key={event.id}><b>{event.status}</b><span>{event.actorName} · {dateTime(event.at)}</span>{event.note&&<small>{event.note}</small>}</p>)}</div>{selected.ownerId===currentUser.id&&<div className="receipt-actions"><button disabled={saving} onClick={()=>void recordReceipt('Seen')}>Mark seen</button><button disabled={saving} onClick={()=>void recordReceipt('Accepted')}>Accept responsibility</button><button disabled={saving} onClick={()=>void recordReceipt('In progress')}>Start work</button><button disabled={saving} onClick={()=>void recordReceipt('Evidence submitted')}>Submit evidence</button></div>}</section>}
        {permissions.canEscalateActions&&<div className="action-buttons"><button className="primary" disabled={saving} onClick={()=>void update(selected.id,{status:'Investigating'},'Investigation started')}>Investigate</button><button disabled={saving} onClick={()=>void update(selected.id,{status:'Dismissed'},'Action dismissed')}>Dismiss</button></div>}{permissions.canVerifyActions&&<section className="action-verification"><div><span>VERIFICATION LOOP</span><strong>Did the action work?</strong></div><select value={verificationStatus} onChange={e=>setVerificationStatus(e.target.value as VerificationStatus)}><option>Worked</option><option>Did not work</option><option>Not enough evidence yet</option></select><textarea value={verificationNote} onChange={e=>setVerificationNote(e.target.value)} placeholder="Required: describe the evidence or measured result…"/><button disabled={saving||!verificationNote.trim()} onClick={verify}>Save verified result</button></section>}<div className="action-audit"><h3>Audit history</h3>{audit.map(row=><div key={row.id}><strong>{row.event}</strong><span>{row.actor_name} · {dateTime(row.at)}</span><p>{row.reason}</p></div>)}{!audit.length&&<p>No audit events returned.</p>}</div></section>}
    </div>
    {showCreate&&<div className="action-modal-backdrop" onClick={()=>setShowCreate(false)}><form className="action-modal" onSubmit={create} onClick={e=>e.stopPropagation()}><div className="action-modal-head"><div><span>NEW OPERATIONAL ACTION</span><h2>Create action</h2></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><div className="action-form-grid"><label>Location<select value={form.location} onChange={e=>{setForm({...form,location:e.target.value});setOwnerId('');}} required>{allowedLocations.map(item=><option key={item}>{item}</option>)}</select></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/></label><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value as ActionSeverity})}>{severities.map(item=><option key={item}>{item}</option>)}</select></label><label>Responsible<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Unassigned</option>{assigneesFor(form.location).map(user=><option key={user.id} value={user.id}>{user.name} · {user.title}</option>)}</select></label><label>Due date<OpsVistaDatePicker value={dueAt} onChange={setDueAt} ariaLabel="Select action due date"/></label></div><label>Signal<textarea value={form.signal} onChange={e=>setForm({...form,signal:e.target.value})} required/></label><label>Likely cause<textarea value={form.cause} onChange={e=>setForm({...form,cause:e.target.value})} required/></label><label>Recommended action<textarea value={form.recommendation} onChange={e=>setForm({...form,recommendation:e.target.value})} required/></label><label>Expected impact<input value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}/></label><button className="action-create-submit" disabled={saving}>{saving?'Saving…':'Create persistent action'}</button></form></div>}
  </div>;
}
