import { useEffect, useMemo, useState } from 'react';
import type { OpsVistaUser } from './accessControl';

type PaymentStatus='Pending Approval'|'Approved'|'Rejected'|'Paid';
type Payment={id:string;location:string;requestDate:string;title:string;payee:string;amount:number;reason:string;requestedByName:string;requestedAt:string;status:PaymentStatus;approvedByName?:string;approvedAt?:string;approvalNote?:string;checkNumber?:string;checkDate?:string;issuedByName?:string;issuedAt?:string;paymentNote?:string};
const allLocations=['Stamford','Orange','Fairfield','Danbury','Avon','Southington'];
const inputStyle={width:'100%',boxSizing:'border-box' as const,padding:10,border:'1px solid #cbd8e6',borderRadius:8};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);

export default function PaymentRequestsView({currentUser,allowedLocations,initialSearch,initialRecordId}:{currentUser:OpsVistaUser;allowedLocations:string[];initialSearch?:string;initialRecordId?:string}){
 const [payments,setPayments]=useState<Payment[]>([]);const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);const [search,setSearch]=useState(initialSearch||'');
 const [location,setLocation]=useState(allowedLocations[0]||allLocations[0]);const [requestDate,setRequestDate]=useState(today());const [title,setTitle]=useState('');const [payee,setPayee]=useState('');const [amount,setAmount]=useState(0);const [reason,setReason]=useState('');
 const [decisionNote,setDecisionNote]=useState<Record<string,string>>({});const [checkNumber,setCheckNumber]=useState<Record<string,string>>({});const [checkDate,setCheckDate]=useState<Record<string,string>>({});const [paymentNote,setPaymentNote]=useState<Record<string,string>>({});
 const isApprover=currentUser.role==='Founder'||currentUser.role==='Corporate';const isIssuer=currentUser.role==='Administration';
 const requestLocations=(currentUser.role==='Founder'||currentUser.role==='Corporate'||currentUser.role==='Administration')?allLocations:allowedLocations;
 const locationScopeKey=allowedLocations.join('|');
 const load=async()=>{const r=await fetch('/api/payments',{credentials:'include',cache:'no-store'});const b=await r.json().catch(()=>({})) as {payments?:Payment[];error?:string};if(r.ok){const scope=new Set(allowedLocations);setPayments((b.payments||[]).filter(payment=>scope.has(payment.location)));}else setMessage(b.error||'Unable to load payments');};
 useEffect(()=>{void load()},[locationScopeKey]);
 useEffect(()=>{if(!requestLocations.includes(location))setLocation(requestLocations[0]||'')},[currentUser.id]);
 useEffect(()=>{if(initialSearch||initialRecordId)setSearch(initialSearch||initialRecordId||'')},[initialSearch,initialRecordId]);
 const visiblePayments=useMemo(()=>{const tokens=search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().split(/\s+/).filter(Boolean);if(!tokens.length)return payments;return payments.filter(payment=>{const haystack=[payment.id,payment.location,payment.requestDate,payment.title,payment.payee,payment.amount,payment.reason,payment.requestedByName,payment.status,payment.approvedByName,payment.checkNumber,payment.issuedByName].filter(Boolean).join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return tokens.every(token=>haystack.includes(token));});},[payments,search]);
 const pending=useMemo(()=>visiblePayments.filter(p=>p.status==='Pending Approval'),[visiblePayments]);
 const approved=useMemo(()=>visiblePayments.filter(p=>p.status==='Approved'),[visiblePayments]);
 const history=useMemo(()=>visiblePayments.filter(p=>p.status==='Paid'||p.status==='Rejected'),[visiblePayments]);
 const pendingValue=pending.reduce((s,p)=>s+p.amount,0),approvedValue=approved.reduce((s,p)=>s+p.amount,0);
 const create=async()=>{setLoading(true);setMessage('');const r=await fetch('/api/payments',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({location,requestDate,title,payee,amount,reason})});const b=await r.json().catch(()=>({})) as {error?:string;payment?:Payment};setMessage(r.ok?`Solicitud ${b.payment?.id} enviada para aprobación.`:b.error||'Unable to create request');if(r.ok){setTitle('');setPayee('');setAmount(0);setReason('');await load();}setLoading(false);};
 const decide=async(id:string,action:'approve'|'reject')=>{setLoading(true);setMessage('');const r=await fetch('/api/payments',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,note:decisionNote[id]||''})});const b=await r.json().catch(()=>({})) as {error?:string};setMessage(r.ok?(action==='approve'?'Pago aprobado y enviado a Administration.':'Solicitud rechazada.'):b.error||'Unable to update request');if(r.ok)await load();setLoading(false);};
 const issue=async(id:string)=>{setLoading(true);setMessage('');const r=await fetch('/api/payments',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'issue',checkNumber:checkNumber[id]||'',checkDate:checkDate[id]||today(),note:paymentNote[id]||''})});const b=await r.json().catch(()=>({})) as {error?:string};setMessage(r.ok?'Cheque marcado como emitido.':b.error||'Unable to issue payment');if(r.ok)await load();setLoading(false);};
 const card=(p:Payment,actions?:React.ReactNode)=><div key={p.id} style={{border:p.id===initialRecordId?'2px solid #2b6fd5':'1px solid #e2e8f0',boxShadow:p.id===initialRecordId?'0 0 0 4px rgba(43,111,213,.10)':'none',borderRadius:12,padding:14,display:'grid',gap:10}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start'}}><div><div style={{fontSize:11,color:'#64748b',fontWeight:800}}>{p.id} · {p.location} · {p.requestDate}</div><strong style={{fontSize:17}}>{p.title}</strong><div>{p.payee}</div></div><div style={{textAlign:'right'}}><strong style={{fontSize:19}}>{money(p.amount)}</strong><div style={{fontSize:11,color:'#64748b'}}>{p.status}</div></div></div><div style={{fontSize:13}}><strong>Motivo:</strong> {p.reason}</div><div style={{fontSize:12,color:'#64748b'}}>Solicitado por {p.requestedByName} · {new Date(p.requestedAt).toLocaleString()}</div>{p.approvedByName&&<div style={{fontSize:12,color:'#475569'}}>Decisión: {p.approvedByName}{p.approvalNote?` · ${p.approvalNote}`:''}</div>}{p.checkNumber&&<div style={{fontSize:12,color:'#166534',fontWeight:750}}>Check #{p.checkNumber} · {p.checkDate} · Emitido por {p.issuedByName}</div>}{actions}</div>;
 return <div style={{display:'grid',gap:16}}>
  <section className="metrics-grid"><div className="metric-card"><div className="metric-label">PENDING APPROVAL</div><div className="metric-value">{pending.length}</div><div className="metric-note">{money(pendingValue)} awaiting Corporate</div></div><div className="metric-card"><div className="metric-label">READY TO PAY</div><div className="metric-value">{approved.length}</div><div className="metric-note">{money(approvedValue)} approved</div></div><div className="metric-card"><div className="metric-label">WORKFLOW</div><div className="metric-value" style={{fontSize:22}}>Request → Approve → Pay</div><div className="metric-note">Audited separation of duties</div></div></section>
  <section className="panel"><div style={{padding:14,display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:10,alignItems:'center'}}><input style={inputStyle} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search payment, payee, requester, location or check…"/>{search&&<button onClick={()=>setSearch('')}>Clear</button>}</div></section>
  <section className="panel"><div className="panel-header"><div><h2>Create Payment Request</h2><p>Managers submit the request. Corporate approves. Administration only issues approved payments.</p></div><span className="count-pill">REQUEST</span></div><div style={{padding:18,display:'grid',gap:12}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div><label>LOCATION</label><select style={inputStyle} value={location} onChange={e=>setLocation(e.target.value)}>{requestLocations.map(x=><option key={x}>{x}</option>)}</select></div><div><label>PAYMENT DATE / REQUEST DATE</label><input style={inputStyle} type="date" value={requestDate} onChange={e=>setRequestDate(e.target.value)}/></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 180px',gap:10}}><div><label>TITLE / CONCEPT</label><input style={inputStyle} value={title} onChange={e=>setTitle(e.target.value)} placeholder="DJ, fundraiser, employee coverage..."/></div><div><label>PAYEE / WHO GETS PAID</label><input style={inputStyle} value={payee} onChange={e=>setPayee(e.target.value)} placeholder="Name or organization"/></div><div><label>AMOUNT</label><input style={inputStyle} type="number" min="0" step="0.01" value={amount||''} onChange={e=>setAmount(Number(e.target.value))}/></div></div><div><label>REASON / DETAILS</label><textarea style={inputStyle} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why this payment is owed; dates worked/event details; any context Corporate needs."/></div><button className="primary" disabled={loading||!location||!title.trim()||!payee.trim()||amount<=0||!reason.trim()} onClick={create}>Submit payment request</button>{message&&<div className="detail-block"><label>PAYMENTS</label><p>{message}</p></div>}</div></section>
  <section className="panel"><div className="panel-header"><div><h2>Pending Approval</h2><p>Only Founder or Corporate can approve or reject these requests.</p></div><span className="count-pill">{pending.length}</span></div><div style={{padding:18,display:'grid',gap:10}}>{pending.length?pending.map(p=>card(p,isApprover?<div style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:8}}><input style={inputStyle} value={decisionNote[p.id]||''} onChange={e=>setDecisionNote(v=>({...v,[p.id]:e.target.value}))} placeholder="Approval / rejection note (optional)"/><button className="primary" onClick={()=>decide(p.id,'approve')} disabled={loading}>Approve</button><button onClick={()=>decide(p.id,'reject')} disabled={loading}>Reject</button></div>:undefined)):<p style={{padding:10,color:'#64748b'}}>No pending requests.</p>}</div></section>
  <section className="panel"><div className="panel-header"><div><h2>Approved · Ready to Pay</h2><p>Administration records the check only after Corporate approval.</p></div><span className="count-pill">{approved.length}</span></div><div style={{padding:18,display:'grid',gap:10}}>{approved.length?approved.map(p=>card(p,isIssuer?<div style={{display:'grid',gridTemplateColumns:'180px 170px 1fr auto',gap:8}}><input style={inputStyle} value={checkNumber[p.id]||''} onChange={e=>setCheckNumber(v=>({...v,[p.id]:e.target.value}))} placeholder="Check #"/><input style={inputStyle} type="date" value={checkDate[p.id]||today()} onChange={e=>setCheckDate(v=>({...v,[p.id]:e.target.value}))}/><input style={inputStyle} value={paymentNote[p.id]||''} onChange={e=>setPaymentNote(v=>({...v,[p.id]:e.target.value}))} placeholder="Payment note"/><button className="primary" onClick={()=>issue(p.id)} disabled={loading||!(checkNumber[p.id]||'').trim()}>Mark check issued</button></div>:undefined)):<p style={{padding:10,color:'#64748b'}}>No approved payments waiting to be issued.</p>}</div></section>
  <section className="panel"><div className="panel-header"><div><h2>Payment History</h2><p>Paid and rejected requests remain permanently visible for audit.</p></div><span className="count-pill">{history.length}</span></div><div style={{padding:18,display:'grid',gap:10}}>{history.map(p=>card(p))}</div></section>
 </div>;
}
