import React from 'react';
import { createRoot, type Root } from 'react-dom/client';
import PriceWatchPanel from './PriceWatchPanel';

let root:Root|undefined,host:HTMLElement|undefined,active=false,scheduled=false;
function page(){return document.querySelector<HTMLElement>('.r365-page');}
function tabs(){return page()?.querySelector<HTMLElement>('.r365-tabs');}
function restore(){const p=page();if(!p)return;for(const child of [...p.children] as HTMLElement[]){if(child===host)continue;if(child.dataset.priceWatchHidden==='1'){child.style.removeProperty('display');delete child.dataset.priceWatchHidden;}}if(host)host.style.display='none';active=false;}
function show(){const p=page(),tab=tabs();if(!p||!tab)return;active=true;for(const button of [...tab.querySelectorAll<HTMLButtonElement>('button')]){button.setAttribute('aria-selected',button.dataset.priceWatchTab==='1'?'true':'false');button.classList.toggle('active',button.dataset.priceWatchTab==='1');}for(const child of [...p.children] as HTMLElement[]){if(child===tab||child===host||child.getAttribute('aria-label')==='Guardado y sincronización')continue;child.dataset.priceWatchHidden='1';child.style.display='none';}if(host)host.style.display='block';}
function sync(){scheduled=false;const p=page(),tab=tabs();if(!p||!tab){if(root){root.unmount();root=undefined;}host?.remove();host=undefined;active=false;return;}let button=tab.querySelector<HTMLButtonElement>('button[data-price-watch-tab="1"]');if(!button){button=document.createElement('button');button.type='button';button.setAttribute('role','tab');button.dataset.priceWatchTab='1';button.textContent='Price Watch';button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();show();});tab.appendChild(button);}if(!host||!p.contains(host)){host=document.createElement('div');host.id='opsvista-price-watch-host';host.style.display='none';tab.insertAdjacentElement('afterend',host);root=createRoot(host);root.render(<React.StrictMode><PriceWatchPanel/></React.StrictMode>);}for(const native of [...tab.querySelectorAll<HTMLButtonElement>('button:not([data-price-watch-tab="1"])')]){if(native.dataset.priceWatchBound==='1')continue;native.dataset.priceWatchBound='1';native.addEventListener('click',()=>{if(active)restore();},{capture:true});}if(active)show();}
function request(){if(scheduled)return;scheduled=true;queueMicrotask(sync);}
const observer=new MutationObserver(request);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-selected','class']});request();},{once:true});else{observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-selected','class']});request();}
