import { useEffect, useMemo, useState } from 'react';
import type { PriceWatchAlert, PriceWatchCategory, PriceWatchResponse } from '../shared/priceWatch';
import './priceWatch.css';

const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2});
const pct=(v:number|null)=>v===null?'—':`${v>0?'+':''}${v.toFixed(2)}%`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const addDays=(value:string,days:number)=>{const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
const statusLabel:Record<PriceWatchAlert['status'],string>={CRITICAL:'≥20% · CRITICAL',HIGH:'≥10% · HIGH',WATCH:'≥5% · WATCH',VERIFY:'VERIFY',BUY:'BUY / STABLE'};
const categoryOptions:Array<'All'|PriceWatchCategory>=['All','Food','Liquor','Supplies','Other'];

function History({row}:{row:PriceWatchAlert}){return <details className="pw-history"><summary>Historial · {row.history.length} compras</summary><div className="pw-history-grid">{row.history.slice().reverse().map((point,index)=><div key={`${point.date}:${point.location}:${index}`}><strong>{point.unitPrice===null?'—':money.format(point.unitPrice)}</strong><span>{point.date}</span><span>{point.location} · {point.vendor}</span><span>{point.quantity??'—'} {point.uom||''}{point.packSize?` · ${point.packSize}`:''}</span>{point.verify.length>0&&<em>{point.verify.join(' · ')}</em>}</div>)}</div></details>}
function Row({row}:{row:PriceWatchAlert}){return <tr className={`pw-${row.status.toLowerCase()}`}><td><strong>{row.itemName}</strong><small>{row.vendorItemNumber||'SKU pendiente'} · {row.category}</small><History row={row}/></td><td><strong>{row.current.unitPrice===null?'—':money.format(row.current.unitPrice)}</strong><small>{row.current.uom||'UOM pendiente'}{row.current.packSize?` · ${row.current.packSize}`:''}</small></td><td>{row.baselinePrice===null?'—':money.format(row.baselinePrice)}</td><td><strong>{pct(row.changePct)}</strong>{row.fourWeekHigh&&<small>4-WEEK HIGH</small>}{row.consecutiveIncreases>1&&<small>{row.consecutiveIncreases} aumentos consecutivos</small>}</td><td>{row.impact===null?'—':money.format(row.impact)}</td><td><strong>{row.current.vendor}</strong><small>{row.current.location} · {row.current.date}</small><small>{row.current.invoiceNumber?`Invoice ${row.current.invoiceNumber}`:'Invoice sin número'}</small></td><td>{row.bestComparable?<><strong>{money.format(row.bestComparable.price)}</strong><small>{row.bestComparable.vendor}</small><small>{row.bestComparable.location} · {row.bestComparable.date}</small></>:'—'}</td><td><span className={`pw-badge ${row.status.toLowerCase()}`}>{statusLabel[row.status]}</span>{row.verify.length>0&&<small>{row.verify.join(' · ')}</small>}</td></tr>}

export default function PriceWatchPanel(){
 const [weeks,setWeeks]=useState(4),[data,setData]=useState<PriceWatchResponse>(),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const [category,setCategory]=useState<'All'|PriceWatchCategory>('All'),[status,setStatus]=useState('Action'),[location,setLocation]=useState('All'),[vendor,setVendor]=useState('All'),[search,setSearch]=useState('');
 const end=today(),start=addDays(end,-weeks*7+1);
 const load=async(force=false)=>{force?setRefreshing(true):setLoading(true);setError('');try{const query=new URLSearchParams({start,end});if(force)query.set('refresh','1');const response=await fetch(`/api/price-watch?${query}`,{credentials:'include',cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'No se pudo abrir Price Watch.');setData(body);}catch(reason){setError(reason instanceof Error?reason.message:'Price Watch no está disponible.');}finally{setLoading(false);setRefreshing(false);}};
 useEffect(()=>{void load(false)},[weeks]);
 const rows=data?.alerts||[];const locations=useMemo(()=>['All',...new Set(rows.flatMap(r=>r.locations))].sort(),[rows]);const vendors=useMemo(()=>['All',...new Set(rows.flatMap(r=>r.vendors))].sort(),[rows]);
 const visible=useMemo(()=>rows.filter(row=>{if(category!=='All'&&row.category!==category)return false;if(status==='Action'&&!['CRITICAL','HIGH','WATCH'].includes(row.status))return false;if(status!=='All'&&status!=='Action'&&row.status!==status)return false;if(location!=='All'&&!row.locations.includes(location))return false;if(vendor!=='All'&&!row.vendors.includes(vendor))return false;const q=search.trim().toLowerCase();return !q||`${row.itemName} ${row.vendorItemNumber||''} ${row.vendors.join(' ')}`.toLowerCase().includes(q);}),[rows,category,status,location,vendor,search]);
 const actionCount=rows.filter(r=>['CRITICAL','HIGH','WATCH'].includes(r.status)).length;
 return <section className="pw-shell" aria-label="Price Watch de Restaurant365">
  <header className="pw-header"><div><span className="pw-kicker">RESTAURANT365 · PURCHASING INTELLIGENCE</span><h2>Price Watch</h2><p>Detecta subidas y bajadas de precio por producto, compara vendors y locaciones, y separa cambios reales de cambios de UOM/pack.</p></div><div className="pw-actions"><label>VENTANA<select value={weeks} onChange={e=>setWeeks(Number(e.target.value))}><option value={4}>4 semanas</option><option value={8}>8 semanas</option><option value={12}>12 semanas</option></select></label><button type="button" onClick={()=>void load(true)} disabled={refreshing}>{refreshing?'Actualizando R365…':'Actualizar R365'}</button></div></header>
  <div className="pw-range">{start} → {end}{data?.fetchedAt&&<span> · última lectura {new Date(data.fetchedAt).toLocaleString('es-MX',{timeZone:'America/New_York'})} CT</span>}</div>
  {error&&<div className="pw-error"><strong>No se pudo completar Price Watch.</strong><span>{error}</span></div>}
  {loading&&!data?<div className="pw-loading">Leyendo invoices y líneas de compra de Restaurant365…</div>:data&&<>
   <div className="pw-kpis"><div><span>Productos</span><strong>{data.summary.items}</strong></div><div><span>Acción ≥5%</span><strong>{actionCount}</strong></div><div><span>≥10%</span><strong>{data.summary.alerts10}</strong></div><div><span>≥20%</span><strong>{data.summary.alerts20}</strong></div><div><span>Bajaron</span><strong>{data.summary.decreases}</strong></div><div><span>Impacto estimado</span><strong>{money.format(data.summary.estimatedImpact)}</strong></div><div><span>Verify</span><strong>{data.summary.verify}</strong></div></div>
   <div className="pw-coverage"><strong>Cobertura:</strong> {data.sourceCoverage.invoices} invoices · {data.sourceCoverage.itemLines} líneas por artículo · {data.sourceCoverage.accountLines} líneas solo contables. {data.sourceCoverage.itemLines===0&&<span>R365 todavía no devolvió detalle por artículo para este período; no se fabrican alertas con líneas GL.</span>}</div>
   <div className="pw-filters"><label>BUSCAR<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Producto, SKU o vendor"/></label><label>CATEGORÍA<select value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{categoryOptions.map(v=><option key={v}>{v}</option>)}</select></label><label>ESTADO<select value={status} onChange={e=>setStatus(e.target.value)}><option>Action</option><option>All</option><option value="CRITICAL">Critical ≥20%</option><option value="HIGH">High ≥10%</option><option value="WATCH">Watch ≥5%</option><option value="VERIFY">Verify</option><option value="BUY">Buy / Stable</option></select></label><label>LOCACIÓN<select value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(v=><option key={v}>{v}</option>)}</select></label><label>VENDOR<select value={vendor} onChange={e=>setVendor(e.target.value)}>{vendors.map(v=><option key={v}>{v}</option>)}</select></label></div>
   <div className="pw-priority"><strong>Cómo comprar con esta pantalla</strong><span><b>CRITICAL/HIGH:</b> revisar antes de reordenar. <b>WATCH:</b> controlar volumen/porción y buscar alternativa. <b>BUY/STABLE:</b> precio estable o menor. <b>VERIFY:</b> no tomar decisión hasta confirmar UOM, pack, SKU o cantidad.</span></div>
   <div className="pw-table-wrap"><table className="pw-table"><thead><tr><th>Producto</th><th>Precio actual</th><th>Baseline</th><th>Cambio</th><th>Impacto</th><th>Compra actual</th><th>Mejor comparable</th><th>Acción</th></tr></thead><tbody>{visible.map(row=><Row key={row.key} row={row}/>)}</tbody></table>{!visible.length&&<div className="pw-empty">No hay productos que coincidan con estos filtros.</div>}</div>
   <details className="pw-method"><summary>Metodología y controles</summary>{data.caveats.map((value,index)=><p key={index}>{value}</p>)}<p><strong>Baseline:</strong> promedio de hasta tres compras comparables anteriores con el mismo artículo, UOM y pack size. Alertas: +5%, +10% y +20%.</p><p><strong>4-WEEK HIGH:</strong> el precio actual es el más alto dentro del período comparable. Los créditos no se usan como precio de compra.</p></details>
  </>}
 </section>;
}
