import { Fragment, useEffect, useMemo, useState, type CSSProperties, type FormEvent } from 'react';
import { currentAuthenticatedUser, type OpsVistaUser } from './accessControl';
import { canCreateProjectsForIdentity } from '../shared/projectAccess';
import './projects.css';
import './projectGantt.css';

type ProjectStatus='Planning'|'In Progress'|'Blocked'|'Completed'|'Cancelled';
type ProjectPriority='High'|'Medium'|'Low';
type ProjectMilestone={id:string;title:string;owner?:string;dueDate?:string;status:'Pending'|'In Progress'|'Completed'};
type ProjectRecord={id:string;name:string;description:string;objective:string;locations:string[];ownerName:string;collaborators:string[];status:ProjectStatus;priority:ProjectPriority;startDate:string;dueDate:string;completedAt?:string;budget:number;actualSpend:number;progress:number;milestones:ProjectMilestone[];attachments:Array<{name:string;url:string}>;createdAt:string;updatedAt:string};
type AuditRow={id:string;at:string;actor_name:string;event:string;before_value?:string;after_value?:string;reason:string};
type Props={currentUser:OpsVistaUser;allowedLocations:string[];canSeeFinancialImpact:boolean;initialSearch?:string;initialRecordId?:string;readOnly?:boolean};
type ViewMode='Board'|'List'|'Timeline'|'Gantt';
const api='/api/workflows?resource=projects';
const statuses:ProjectStatus[]=['Planning','In Progress','Blocked','Completed','Cancelled'];
const priorities:ProjectPriority[]=['High','Medium','Low'];
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
function easternToday(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const values=Object.fromEntries(parts.map(part=>[part.type,part.value]));return `${values.year}-${values.month}-${values.day}`;}
function addDays(value:string,days:number){const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
const date=(value:string)=>new Date(`${value}T00:00:00Z`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const dayNumber=(value:string)=>Math.floor(new Date(`${value}T00:00:00Z`).getTime()/86400000);
function isUserPreview(user:OpsVistaUser){try{return currentAuthenticatedUser().id!==user.id;}catch{return false;}}

export default function ProjectsView({currentUser,allowedLocations,canSeeFinancialImpact,initialSearch,initialRecordId,readOnly=false}:Props){
  const today=useMemo(easternToday,[]);
  const [projects,setProjects]=useState<ProjectRecord[]>([]);
  const [selectedId,setSelectedId]=useState(initialRecordId||'');
  const [audit,setAudit]=useState<AuditRow[]>([]);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState('');
  const [view,setView]=useState<ViewMode>('Board');
  const [location,setLocation]=useState('All locations');
  const [status,setStatus]=useState(initialSearch||initialRecordId?'All':'Active');
  const [search,setSearch]=useState(initialSearch||'');
  const [showCreate,setShowCreate]=useState(false);
  const [progress,setProgress]=useState(0);
  const [actualSpend,setActualSpend]=useState(0);
  const [newMilestone,setNewMilestone]=useState('');
  const [form,setForm]=useState({name:'',description:'',objective:'',locations:allowedLocations.slice(0,1),ownerName:currentUser.name,collaborators:'',status:'Planning' as ProjectStatus,priority:'Medium' as ProjectPriority,startDate:today,dueDate:addDays(today,30),budget:0});
  const locationScopeKey=allowedLocations.join('|');
  const load=async()=>{setLoading(true);setError('');try{const response=await fetch(api,{credentials:'include',cache:'no-store'});const body=await response.json().catch(()=>({})) as {projects?:ProjectRecord[];error?:string};if(!response.ok)throw new Error(body.error||'Projects unavailable');const scope=new Set(allowedLocations);const scoped=(body.projects||[]).filter(item=>item.locations.every(projectLocation=>scope.has(projectLocation)));setProjects(scoped);setSelectedId(current=>initialRecordId&&scoped.some(item=>item.id===initialRecordId)?initialRecordId:scoped.some(item=>item.id===current)?current:'');}catch(e){setError(e instanceof Error?e.message:'Projects unavailable');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[locationScopeKey]);
  useEffect(()=>{if(initialSearch||initialRecordId){setSearch(initialSearch||'');setStatus('All');if(initialRecordId)setSelectedId(initialRecordId);}},[initialSearch,initialRecordId]);
  const selected=projects.find(item=>item.id===selectedId);
  useEffect(()=>{if(!selected){setAudit([]);return;}setProgress(selected.progress);setActualSpend(selected.actualSpend);fetch(`${api}&id=${encodeURIComponent(selected.id)}`,{credentials:'include',cache:'no-store'}).then(r=>r.json()).then((body:{audit?:AuditRow[]})=>setAudit(body.audit||[])).catch(()=>setAudit([]));},[selected?.id]);
  const filtered=useMemo(()=>projects.filter(project=>{const locationMatch=location==='All locations'||project.locations.includes(location);const statusMatch=status==='All'||(status==='Active'?!['Completed','Cancelled'].includes(project.status):project.status===status);const q=search.trim().toLowerCase();const searchMatch=!q||[project.name,project.description,project.objective,project.ownerName,...project.locations].join(' ').toLowerCase().includes(q);return locationMatch&&statusMatch&&searchMatch;}),[projects,location,status,search]);
  const gantt=useMemo(()=>{
    const projectDates=filtered.flatMap(project=>[project.startDate,project.dueDate]).filter(Boolean);
    const first=projectDates.length?projectDates.reduce((min,value)=>value<min?value:min,projectDates[0]):today;
    const last=projectDates.length?projectDates.reduce((max,value)=>value>max?value:max,projectDates[0]):addDays(today,30);
    const start=addDays(first<today?first:today,-7);
    const end=addDays(last>today?last:today,7);
    const days=Math.max(1,dayNumber(end)-dayNumber(start)+1);
    const months:Array<{label:string;left:number;width:number}>=[];
    let cursor=start;
    while(cursor<=end){
      const current=new Date(`${cursor}T00:00:00Z`);
      const nextMonth=new Date(Date.UTC(current.getUTCFullYear(),current.getUTCMonth()+1,1)).toISOString().slice(0,10);
      const monthEnd=addDays(nextMonth,-1)<end?addDays(nextMonth,-1):end;
      months.push({label:current.toLocaleDateString('en-US',{timeZone:'UTC',month:'short',year:'numeric'}),left:(dayNumber(cursor)-dayNumber(start))/days*100,width:(dayNumber(monthEnd)-dayNumber(cursor)+1)/days*100});
      cursor=nextMonth;
    }
    return {start,end,days,months,todayLeft:(dayNumber(today)-dayNumber(start)+.5)/days*100};
  },[filtered,today]);
  const active=projects.filter(item=>!['Completed','Cancelled'].includes(item.status));const totalBudget=active.reduce((sum,item)=>sum+item.budget,0);const totalSpend=active.reduce((sum,item)=>sum+item.actualSpend,0);const overdue=active.filter(item=>item.dueDate<today).length;
  const effectiveReadOnly=readOnly||isUserPreview(currentUser);
  const canCreateProjects=!effectiveReadOnly&&canCreateProjectsForIdentity(currentUser);
  const create=async(event:FormEvent)=>{event.preventDefault();if(!canCreateProjects){setError('Only Roberto Rodríguez or Jacob Rodríguez can create projects');return;}if(!form.locations.length){setError('Select at least one location');return;}setSaving(true);setError('');try{const response=await fetch(api,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,collaborators:form.collaborators.split(',').map(value=>value.trim()).filter(Boolean),milestones:[]})});const body=await response.json().catch(()=>({})) as {project?:ProjectRecord;error?:string};if(!response.ok||!body.project)throw new Error(body.error||'Project could not be created');setProjects(items=>[body.project!,...items]);setSelectedId(body.project.id);setShowCreate(false);setForm({...form,name:'',description:'',objective:'',budget:0});}catch(e){setError(e instanceof Error?e.message:'Project could not be created');}finally{setSaving(false);}};
  const update=async(id:string,patch:Record<string,unknown>,reason:string)=>{if(effectiveReadOnly){setError('User preview is read-only');return;}setSaving(true);setError('');try{const response=await fetch(api,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...patch,reason})});const body=await response.json().catch(()=>({})) as {project?:ProjectRecord;error?:string};if(!response.ok||!body.project)throw new Error(body.error||'Project could not be updated');setProjects(items=>items.map(item=>item.id===id?body.project!:item));const detail=await fetch(`${api}&id=${encodeURIComponent(id)}`,{credentials:'include',cache:'no-store'}).then(r=>r.json()) as {audit?:AuditRow[]};setAudit(detail.audit||[]);}catch(e){setError(e instanceof Error?e.message:'Project could not be updated');}finally{setSaving(false);}};
  const addMilestone=()=>{if(!selected||!newMilestone.trim())return;const milestones=[...selected.milestones,{id:`MS-${Date.now()}`,title:newMilestone.trim(),owner:selected.ownerName,dueDate:selected.dueDate,status:'Pending' as const}];setNewMilestone('');void update(selected.id,{milestones},'Milestone added');};
  const toggleMilestone=(milestone:ProjectMilestone)=>{if(!selected)return;const milestones=selected.milestones.map(item=>item.id===milestone.id?{...item,status:item.status==='Completed'?'Pending' as const:'Completed' as const}:item);const completed=milestones.filter(item=>item.status==='Completed').length;const calculated=milestones.length?Math.round(completed/milestones.length*100):selected.progress;void update(selected.id,{milestones,progress:calculated},`Milestone ${milestone.status==='Completed'?'reopened':'completed'}`);};
  const toggleLocation=(value:string)=>setForm(current=>({...current,locations:current.locations.includes(value)?current.locations.filter(item=>item!==value):[...current.locations,value]}));

  return <div className="projects-page">
    <section className="projects-toolbar"><div><strong>Projects portfolio</strong><span>Longer-term initiatives with owners, dates, milestones and budget control.</span></div><div><select value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option>{allowedLocations.map(item=><option key={item}>{item}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>Active</option><option>All</option>{statuses.map(item=><option key={item}>{item}</option>)}</select>{canCreateProjects&&<button onClick={()=>setShowCreate(true)}>+ New project</button>}</div></section>
    {error&&<div className="projects-error">{error}</div>}
    <section className="projects-kpis"><article><span>ACTIVE PROJECTS</span><strong>{active.length}</strong><small>{projects.filter(item=>item.status==='Blocked').length} blocked</small></article><article><span>OVERDUE</span><strong className={overdue?'warn':''}>{overdue}</strong><small>Past due date</small></article><article><span>AVG. PROGRESS</span><strong>{active.length?Math.round(active.reduce((sum,item)=>sum+item.progress,0)/active.length):0}%</strong><small>Across active portfolio</small></article>{canSeeFinancialImpact&&<><article><span>APPROVED BUDGET</span><strong>{money(totalBudget)}</strong><small>Active projects</small></article><article><span>ACTUAL SPEND</span><strong>{money(totalSpend)}</strong><small>{totalBudget?`${Math.round(totalSpend/totalBudget*100)}% of budget`:'No budget recorded'}</small></article></>}</section>
    <section className="projects-viewbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search project, objective, owner or location…"/><div>{(['Board','List','Timeline','Gantt'] as ViewMode[]).map(item=><button key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{item}</button>)}</div><button onClick={()=>void load()}>{loading?'Loading…':'Refresh'}</button></section>
    {!loading&&!filtered.length&&<section className="projects-empty"><strong>No projects in this scope.</strong><span>Create the first project; OpsVista will not substitute test initiatives.</span></section>}
    {view==='Board'&&<section className="projects-board">{(['Planning','In Progress','Blocked','Completed'] as ProjectStatus[]).map(column=><div key={column} className="project-column"><div className="project-column-head"><strong>{column}</strong><span>{filtered.filter(item=>item.status===column).length}</span></div>{filtered.filter(item=>item.status===column).map(project=><button key={project.id} className="project-card" onClick={()=>setSelectedId(project.id)}><div><span className={`project-priority ${project.priority.toLowerCase()}`}>{project.priority}</span><small>{project.id}</small></div><strong>{project.name}</strong><p>{project.objective}</p><div className="project-progress"><i style={{width:`${project.progress}%`}}></i></div><div className="project-card-meta"><span>{project.progress}%</span><span>{project.ownerName}</span><span>Due {date(project.dueDate)}</span></div><div className="project-location-chips">{project.locations.map(item=><span key={item}>{item}</span>)}</div></button>)}</div>)}</section>}
    {view==='List'&&<section className="projects-table-wrap"><table><thead><tr><th>PROJECT</th><th>LOCATIONS</th><th>OWNER</th><th>STATUS</th><th>PROGRESS</th><th>DUE</th>{canSeeFinancialImpact&&<><th>BUDGET</th><th>SPEND</th></>}</tr></thead><tbody>{filtered.map(project=><tr key={project.id} onClick={()=>setSelectedId(project.id)}><td><strong>{project.name}</strong><small>{project.id}</small></td><td>{project.locations.join(', ')}</td><td>{project.ownerName}</td><td><span className={`project-status ${project.status.toLowerCase().replaceAll(' ','-')}`}>{project.status}</span></td><td>{project.progress}%</td><td>{date(project.dueDate)}</td>{canSeeFinancialImpact&&<><td>{money(project.budget)}</td><td>{money(project.actualSpend)}</td></>}</tr>)}</tbody></table></section>}
    {view==='Timeline'&&<section className="projects-timeline">{[...filtered].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(project=><button key={project.id} onClick={()=>setSelectedId(project.id)}><time>{date(project.startDate)}<b>→</b>{date(project.dueDate)}</time><div><strong>{project.name}</strong><span>{project.ownerName} · {project.locations.join(', ')}</span></div><em className={project.dueDate<today&&!['Completed','Cancelled'].includes(project.status)?'late':''}>{project.progress}%</em></button>)}</section>}
    {view==='Gantt'&&<section className="projects-gantt"><header><div><strong>Portfolio delivery plan</strong><span>{date(gantt.start)} → {date(gantt.end)} · {filtered.length} projects</span></div><div className="gantt-legend"><span><i className="today"></i>Today</span><span><i className="progress"></i>Progress</span><span><i className="milestone"></i>Milestone</span><span><i className="late"></i>Overdue</span></div></header><div className="gantt-scroll"><div className="gantt-grid" style={{'--gantt-days':gantt.days} as CSSProperties}><div className="gantt-corner"><strong>PROJECT / OWNER</strong><span>Click any row for full details</span></div><div className="gantt-calendar-head">{gantt.months.map(month=><span key={`${month.label}-${month.left}`} style={{left:`${month.left}%`,width:`${month.width}%`}}>{month.label}</span>)}<i className="gantt-today-line" style={{left:`${gantt.todayLeft}%`}}></i></div>{[...filtered].sort((a,b)=>a.startDate.localeCompare(b.startDate)).map(project=>{const late=project.dueDate<today&&!['Completed','Cancelled'].includes(project.status);const rawLeft=(dayNumber(project.startDate)-dayNumber(gantt.start))/gantt.days*100;const rawWidth=(dayNumber(project.dueDate)-dayNumber(project.startDate)+1)/gantt.days*100;const left=Math.max(0,rawLeft);const width=Math.max(1.2,Math.min(100-left,rawWidth));return <Fragment key={project.id}><button className="gantt-project-label" onClick={()=>setSelectedId(project.id)}><strong>{project.name}</strong><span>{project.ownerName} · {project.status}</span></button><div className="gantt-track" onClick={()=>setSelectedId(project.id)} role="button" tabIndex={0} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')setSelectedId(project.id);}}><i className="gantt-today-line" style={{left:`${gantt.todayLeft}%`}}></i><div className={`gantt-bar ${late?'late':''} ${project.status.toLowerCase().replaceAll(' ','-')}`} style={{left:`${left}%`,width:`${width}%`}} title={`${project.name}: ${date(project.startDate)} – ${date(project.dueDate)}`}><b style={{width:`${project.progress}%`}}></b><span>{project.progress}%</span></div>{project.milestones.filter(item=>item.dueDate).map(item=>{const marker=(dayNumber(item.dueDate!)-dayNumber(gantt.start)+.5)/gantt.days*100;return marker>=0&&marker<=100?<i key={item.id} className={`gantt-milestone ${item.status==='Completed'?'done':''}`} style={{left:`${marker}%`}} title={`${item.title} · ${date(item.dueDate!)}`}></i>:null;})}</div></Fragment>;})}</div></div></section>}
    {selected&&<div className="project-drawer-backdrop" onClick={()=>setSelectedId('')}><aside className="project-drawer" onClick={e=>e.stopPropagation()}><div className="project-drawer-head"><div><span>{selected.id} · {selected.priority} PRIORITY</span><h2>{selected.name}</h2><p>{selected.locations.join(', ')} · {selected.ownerName}</p></div><button onClick={()=>setSelectedId('')}>×</button></div><div className="project-objective"><label>OBJECTIVE</label><p>{selected.objective}</p><small>{selected.description}</small></div><div className="project-detail-grid"><div><label>STATUS</label><select value={selected.status} onChange={e=>void update(selected.id,{status:e.target.value},'Project status changed')}>{statuses.map(item=><option key={item}>{item}</option>)}</select></div><div><label>DATES</label><strong>{date(selected.startDate)} → {date(selected.dueDate)}</strong></div><div><label>PROGRESS</label><input type="number" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/><button onClick={()=>void update(selected.id,{progress},'Progress updated')}>Save</button></div>{canSeeFinancialImpact&&<div><label>BUDGET / SPEND</label><strong>{money(selected.budget)}</strong><input type="number" min="0" step="0.01" value={actualSpend} onChange={e=>setActualSpend(Number(e.target.value))}/><button onClick={()=>void update(selected.id,{actualSpend},'Actual spend updated')}>Save</button></div>}</div><div className="project-milestones"><div><h3>Milestones</h3><span>{selected.milestones.filter(item=>item.status==='Completed').length}/{selected.milestones.length} completed</span></div>{selected.milestones.map(item=><button key={item.id} onClick={()=>toggleMilestone(item)}><i className={item.status==='Completed'?'done':''}>{item.status==='Completed'?'✓':''}</i><span><strong>{item.title}</strong><small>{item.owner||selected.ownerName}{item.dueDate?` · due ${date(item.dueDate)}`:''}</small></span></button>)}<div className="project-add-milestone"><input value={newMilestone} onChange={e=>setNewMilestone(e.target.value)} placeholder="Add milestone…" onKeyDown={e=>{if(e.key==='Enter')addMilestone();}}/><button onClick={addMilestone}>Add</button></div></div><div className="project-audit"><h3>Project history</h3>{audit.map(row=><div key={row.id}><strong>{row.event}</strong><span>{row.actor_name} · {new Date(row.at).toLocaleString()}</span><p>{row.reason}</p></div>)}{!audit.length&&<p>No audit events returned.</p>}</div></aside></div>}
    {canCreateProjects&&showCreate&&<div className="project-modal-backdrop" onClick={()=>setShowCreate(false)}><form className="project-modal" onSubmit={create} onClick={e=>e.stopPropagation()}><div className="project-drawer-head"><div><span>NEW PROJECT</span><h2>Create project</h2><p>Projects remain separate from Action Center.</p></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><label>Project name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Objective<textarea value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})} required/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><div className="project-form-grid"><label>Owner<input value={form.ownerName} onChange={e=>setForm({...form,ownerName:e.target.value})} required/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as ProjectPriority})}>{priorities.map(item=><option key={item}>{item}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ProjectStatus})}>{statuses.map(item=><option key={item}>{item}</option>)}</select></label><label>Start date<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} required/></label><label>Due date<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} required/></label><label>Budget<input type="number" min="0" step="0.01" value={form.budget} onChange={e=>setForm({...form,budget:Number(e.target.value)})}/></label></div><label>Collaborators<input value={form.collaborators} onChange={e=>setForm({...form,collaborators:e.target.value})} placeholder="Names separated by commas"/></label><fieldset><legend>Locations</legend>{allowedLocations.map(item=><label key={item}><input type="checkbox" checked={form.locations.includes(item)} onChange={()=>toggleLocation(item)}/>{item}</label>)}</fieldset><button className="project-submit" disabled={saving}>{saving?'Saving…':'Create project'}</button></form></div>}
  </div>;
}
