import { useMemo, useState } from 'react';
import './scheduleOvertimeMonitor.css';
import './scheduleSalary.css';
import type { ExternalEscalation } from './actionCenterTypes';
import { useI18n } from './i18n';

export type ScheduleShift={id:number;start:string;end:string;location:string;role:string};
export type ScheduleEmployee={
  userId:number;employeeName:string;primaryLocation:string;locations:string[];role:string;
  workedHours:number;scheduledHours:number;remainingScheduledHours:number;projectedHours:number;
  overtimeHours:number;actualOvertimeHours:number;hourlyWage:number|null;estimatedOvertimeCost:number|null;wageSource:'shift_or_punch'|'user_hourly'|'manual_override'|'unavailable';toastMatchStatus:'matched_external_id'|'matched_name'|'ambiguous'|'unmatched';employmentType:'hourly'|'salary';nextShift?:ScheduleShift;
  status:'Overtime'|'Risk'|'Safe'|'Salary';
};
export type ScheduleLocation={location:string;monitoredEmployees:number;riskEmployees:number;actualOvertimeHours:number;additionalProjectedOvertimeHours:number;projectedOvertimeHours:number;salaryOver40Hours:number;unclassifiedToastOvertimeHours:number;unclassifiedToastEmployees:number;estimatedOvertimeCost:number;employeesMissingHourlyWage:number};
export type ScheduleRisk={
  start:string;end:string;generatedAt:string;thresholdHours:number;scheduledHours:number;riskEmployees:number;
  actualOvertimeHours:number;additionalProjectedOvertimeHours:number;projectedOvertimeHours:number;salaryOver40Hours:number;unclassifiedToastOvertimeHours:number;unclassifiedToastEmployees:number;estimatedOvertimeCost:number;employeesMissingHourlyWage:number;unmatchedToastEmployees:number;employees:ScheduleEmployee[];locations:ScheduleLocation[];
};

type Props={
  data:ScheduleRisk|null;
  error?:string;
  loading:boolean;
  onEscalate?:(item:ExternalEscalation)=>Promise<unknown>|void;
};

const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
const cost=(value:number|null,t:(en:string,es:string)=>string)=>value===null?t('Rate unavailable','Tarifa no disponible'):money(value);
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).map(part=>part[0]).join('').slice(0,2).toUpperCase();

export default function ScheduleOvertimeMonitor({data,error,loading,onEscalate}:Props){
  const {t,locale}=useI18n();
  const dateTime=(value:string)=>new Intl.DateTimeFormat(locale,{timeZone:'America/New_York',weekday:'short',hour:'numeric',minute:'2-digit'}).format(new Date(value));
  const [alertAt,setAlertAt]=useState(40);
  const [onlyRisk,setOnlyRisk]=useState(false);
  const [selected,setSelected]=useState<ScheduleEmployee|null>(null);
  const [sent,setSent]=useState<number[]>([]);
  const employees=useMemo(()=>((data?.employees||[])
    .filter(row=>!onlyRisk||(row.employmentType==='hourly'&&row.projectedHours>=alertAt))
    .sort((a,b)=>a.employmentType!==b.employmentType?(a.employmentType==='salary'?1:-1):b.overtimeHours-a.overtimeHours||b.projectedHours-a.projectedHours)),[data,onlyRisk,alertAt]);
  const locationRows=useMemo(()=>(data?.locations||[]),[data]);
  const topRisk=employees.filter(row=>row.overtimeHours>0).slice(0,2);
  const send=async(employee:ScheduleEmployee)=>{
    if(!onEscalate)return;
    try{await onEscalate({location:employee.nextShift?.location||employee.primaryLocation,title:t(`Review projected overtime · ${employee.employeeName}`,`Revisar overtime proyectado · ${employee.employeeName}`),signal:t(`${employee.employeeName} is projected at ${employee.projectedHours.toFixed(1)} h (${employee.overtimeHours.toFixed(1)} h overtime) for ${data?.start}–${data?.end}.`,`${employee.employeeName} está proyectado a ${employee.projectedHours.toFixed(1)} h (${employee.overtimeHours.toFixed(1)} h de overtime) para ${data?.start}–${data?.end}.`),cause:t(`Has ${employee.workedHours.toFixed(1)} worked hours and still has ${employee.remainingScheduledHours.toFixed(1)} scheduled hours remaining.`,`Acumula ${employee.workedHours.toFixed(1)} h trabajadas y todavía tiene ${employee.remainingScheduledHours.toFixed(1)} h programadas por completar.`),recommendation:employee.nextShift?t(`The location manager should speak with ${employee.employeeName}, review or reassign the ${dateTime(employee.nextShift.start)} shift at ${employee.nextShift.location} (${employee.nextShift.role}), and protect required coverage.`,`El location manager debe hablar con ${employee.employeeName}, revisar o reasignar el turno de ${dateTime(employee.nextShift.start)} en ${employee.nextShift.location} (${employee.nextShift.role}) y proteger la cobertura necesaria.`):t(`The location manager should review remaining shifts with ${employee.employeeName} and reassign hours to a qualified person who will remain under 40 hours.`,`El location manager debe revisar con ${employee.employeeName} los turnos restantes y reasignar horas a una persona calificada que permanezca debajo de 40 horas.`),impact:employee.estimatedOvertimeCost===null?t('OT cost unavailable because Toast did not provide a valid hourly rate.','Costo OT no disponible porque Toast no entregó una tarifa horaria válida.'):t(`${money(employee.estimatedOvertimeCost)} estimated OT cost at 1.5×`,`${money(employee.estimatedOvertimeCost)} de costo OT estimado a 1.5×`),severity:employee.overtimeHours>=4?'High':'Medium',accountableName:employee.employeeName,accountableRole:t(`${employee.role} · overtime exposure`,`${employee.role} · exposición a overtime`),automationKey:`overtime::${employee.nextShift?.location||employee.primaryLocation}::${employee.userId}::${data?.start}::${data?.end}`,sources:['Toast Labor','7shifts Schedule'],sourceIds:[String(employee.userId)]});setSent(current=>current.includes(employee.userId)?current:[...current,employee.userId]);}catch(error){if(error instanceof Error&&error.message==='Action assignment cancelled')return;}
  };

  if(loading)return <section className="schedule-panel schedule-loading"><strong>{t('Loading 7shifts schedules and Toast Time Entries…','Cargando horarios de 7shifts y Time Entries de Toast…')}</strong><span>{t('Calculating overtime by employee and location.','Calculando overtime por empleado y ubicación.')}</span></section>;
  if(error)return <section className="schedule-panel schedule-error"><strong>{t('Projected overtime could not be calculated','No fue posible calcular el overtime proyectado')}</strong><span>{error}</span><small>{t('OpsVista will not show estimates until it receives real 7shifts shifts/roles plus valid Toast hours and rates.','OpsVista no mostrará estimaciones hasta recibir turnos y puestos reales de 7shifts, más horas y tarifas válidas de Toast.')}</small></section>;
  if(!data)return null;

  return <div className="schedule-section">
    <div className="schedule-section-heading"><div><span>7SHIFTS · LIVE SCHEDULE</span><h2>{t('Overtime monitor by employee','Monitor de overtime por empleado')}</h2><p>{data.start} → {data.end} · {t('Operating week Wednesday–Tuesday · Worked hours + remaining published shifts','Semana operativa miércoles–martes · Horas trabajadas + turnos publicados restantes')}</p></div><div className="schedule-controls"><label>{t('Alert at','Alerta a')} <select value={alertAt} onChange={event=>setAlertAt(Number(event.target.value))}><option value={36}>36 h</option><option value={38}>38 h</option><option value={40}>40 h</option></select></label><button className={onlyRisk?'active':''} onClick={()=>setOnlyRisk(value=>!value)}>{t('At risk only','Solo en riesgo')}</button></div></div>

    <section className="schedule-kpis">
      <article><span className="schedule-kpi-icon blue">◷</span><div><label>{t('SCHEDULED HOURS','HORAS PROGRAMADAS')}</label><strong>{data.scheduledHours.toFixed(1)}</strong><p>{t('7shifts · full published week','7shifts · semana completa publicada')}</p></div></article>
      <article><span className="schedule-kpi-icon red">!</span><div><label>{t('EMPLOYEES AT RISK','EMPLEADOS EN RIESGO')}</label><strong>{data.riskEmployees}</strong><p>{t('Projected over 40 hours','Proyectados sobre 40 horas')}</p></div></article>
      <article><span className="schedule-kpi-icon red">✓</span><div><label>{t('PAYABLE OT · HOURLY','OT PAGADERO · HOURLY')}</label><strong>{data.actualOvertimeHours.toFixed(1)} h</strong><p>{t('Hourly employees · already worked','Empleados por hora · ya trabajado')}</p></div></article>
      <article><span className="schedule-kpi-icon amber">↗</span><div><label>{t('ADDITIONAL SCHEDULED OT','OT ADICIONAL PROGRAMADO')}</label><strong>{data.additionalProjectedOvertimeHours.toFixed(1)} h</strong><p>{t('Remaining exposure in 7shifts','Exposición restante en 7shifts')}</p></div></article>
      <article><span className="schedule-kpi-icon amber">Σ</span><div><label>{t('TOTAL PROJECTED OT','OT TOTAL PROYECTADO')}</label><strong>{data.projectedOvertimeHours.toFixed(1)} h</strong><p>{t('Worked + additional exposure','Trabajado + exposición adicional')}</p></div></article>
      <article><span className="schedule-kpi-icon blue">i</span><div><label>{t('SALARIED OVER 40 H','SALARIADOS SOBRE 40 H')}</label><strong>{data.salaryOver40Hours.toFixed(1)} h</strong><p>{t('Informational only · not payable OT','Solo informativo · no es OT pagadero')}</p></div></article>
      <article><span className="schedule-kpi-icon amber">?</span><div><label>{t('UNCLASSIFIED TOAST OT','OT TOAST SIN CLASIFICAR')}</label><strong>{data.unclassifiedToastOvertimeHours.toFixed(1)} h</strong><p>{data.unclassifiedToastEmployees} {t('employees without a visible 7shifts link','empleados sin vínculo visible en 7shifts')}</p></div></article>
      <article><span className="schedule-kpi-icon green">$</span><div><label>{t('ESTIMATED OT COST','COSTO OT ESTIMADO')}</label><strong>{money(data.estimatedOvertimeCost)}</strong><p>{t('Toast Time Entries at 1.5×','Toast Time Entries a 1.5×')}{data.employeesMissingHourlyWage?t(` · ${data.employeesMissingHourlyWage} without rate`,` · ${data.employeesMissingHourlyWage} sin tarifa`):''}</p></div></article>
    </section>

    <div className="schedule-main-grid">
      <section className="schedule-panel schedule-employee-panel">
        <div className="schedule-panel-head"><div><h3>{t('Hours by employee','Horas por empleado')}</h3><p>{t('Worked hours and rate: Toast Time Entry Management · Scheduled: 7shifts.','Trabajadas y tarifa: Toast Time Entry Management · Programadas: 7shifts.')}{data.unmatchedToastEmployees?` ${data.unmatchedToastEmployees} ${t('employees require cross-system linking.','empleados requieren vinculación entre sistemas.')}`:''}</p></div><span>{employees.length} {t('employees','empleados')}</span></div>
        <div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>{t('Employee','Empleado')}</th><th>{t('Location / role','Locación / puesto')}</th><th>{t('Toast worked','Trabajadas Toast')}</th><th>{t('Toast rate','Tarifa Toast')}</th><th>{t('7shifts scheduled','Programadas 7shifts')}</th><th>{t('Projection','Proyección')}</th><th>{t('Projected OT','OT proyectado')}</th><th>{t('Next shift','Próximo turno')}</th><th>{t('Action','Acción')}</th></tr></thead><tbody>
          {employees.map(employee=>{const salaried=employee.employmentType==='salary';const progress=Math.min(100,employee.workedHours/40*100);const atRisk=!salaried&&employee.projectedHours>=alertAt;return <tr key={employee.userId} className={employee.overtimeHours>0?'schedule-overtime-row':atRisk?'schedule-risk-row':salaried?'schedule-salary-row':''}>
            <td><div className="schedule-person"><span>{initials(employee.employeeName)}</span><div><strong>{employee.employeeName}</strong>{salaried?<small>{t('Salaried employee','Personal asalariado')}</small>:employee.wageSource==='manual_override'&&!employee.toastMatchStatus.startsWith('matched')?<small>{t('Configured rate · unlinked Toast hours','Tarifa configurada · horas Toast sin vincular')}</small>:!employee.toastMatchStatus.startsWith('matched')&&<small>{t('No confirmed Toast link','Sin vínculo confirmado con Toast')}</small>}</div></div></td>
            <td><strong>{employee.primaryLocation}</strong><small>{employee.role}{employee.locations.length>1?` · ${employee.locations.length} ${t('locations','locaciones')}`:''}</small></td>
            <td><strong>{employee.workedHours.toFixed(1)} h</strong><small>{salaried?t('Recorded coverage hours','Horas de cobertura registradas'):t(`${employee.actualOvertimeHours.toFixed(1)} h OT already worked`,`${employee.actualOvertimeHours.toFixed(1)} h OT ya trabajadas`)}</small><div className="schedule-progress"><i style={{width:`${progress}%`}} className={employee.overtimeHours>0?'danger':atRisk?'warning':''}/></div></td>
            <td><strong>{salaried?t('Salary','Salario'):employee.hourlyWage===null?'—':`${money(employee.hourlyWage)}/h`}</strong><small>{salaried?t('No hourly rate','No usa tarifa por hora'):employee.hourlyWage===null?t('No valid hourly rate','Sin tarifa horaria válida'):employee.wageSource==='manual_override'?t('Configured rate','Tarifa configurada'):'Time Entry Management'}</small></td>
            <td><strong>{employee.scheduledHours.toFixed(1)} h</strong><small>{employee.remainingScheduledHours.toFixed(1)} h {t('remaining','restantes')}</small></td>
            <td><strong className={employee.overtimeHours>0?'schedule-danger-text':''}>{employee.projectedHours.toFixed(1)} h</strong>{salaried&&<small>{t('Salaried coverage','Cobertura asalariada')}</small>}</td>
            <td>{salaried?<span className="schedule-salary-pill">{t('Salary · OT does not apply','Salario · OT no aplica')}</span>:employee.overtimeHours>0?<><span className="schedule-ot-pill">+{employee.overtimeHours.toFixed(1)} h</span><small>{cost(employee.estimatedOvertimeCost,t)}</small></>:atRisk?<span className="schedule-risk-pill">{t('Near limit','Cerca del límite')}</span>:<span className="schedule-safe-pill">{t('No OT','Sin OT')}</span>}</td>
            <td>{employee.nextShift?<><strong>{dateTime(employee.nextShift.start)}</strong><small>{employee.nextShift.location} · {employee.nextShift.role}</small></>:<span>{t('No remaining shifts','Sin turnos restantes')}</span>}</td>
            <td><button disabled={salaried} onClick={()=>setSelected(employee)}>{salaried?t('Salary','Salario'):t('Review','Revisar')}</button></td>
          </tr>})}
          {!employees.length&&<tr><td colSpan={9}><div className="schedule-empty">{t('No employees match these filters.','No hay empleados que coincidan con estos filtros.')}</div></td></tr>}
        </tbody></table></div>
      </section>

      <aside className="schedule-panel schedule-location-panel"><div className="schedule-panel-head"><div><h3>{t('Risk by location','Riesgo por locación')}</h3><p>{t('Separates payable hourly OT, salaried hours, and Toast records pending classification.','Separa OT hourly pagadero, horas asalariadas y registros Toast pendientes de clasificar.')}</p></div></div><div className="schedule-location-list">{locationRows.map(row=><div key={row.location}><div><strong>{row.location}</strong><small>{row.riskEmployees?t(`${row.riskEmployees} hourly at risk · `,`${row.riskEmployees} hourly en riesgo · `):''}{row.monitoredEmployees} {t('monitored','monitoreados')}</small></div><div className={row.projectedOvertimeHours>0?'danger':'safe'}><strong>{row.projectedOvertimeHours.toFixed(1)} h {t('total hourly OT','OT hourly total')}</strong><small>{row.actualOvertimeHours.toFixed(1)} {t('payable','pagaderas')} · {row.additionalProjectedOvertimeHours.toFixed(1)} {t('additional','adicionales')} · {money(row.estimatedOvertimeCost)}{row.employeesMissingHourlyWage?t(` · ${row.employeesMissingHourlyWage} without rate`,` · ${row.employeesMissingHourlyWage} sin tarifa`):''}</small><small>{row.salaryOver40Hours.toFixed(1)} h {t('salaried over 40','asalariadas sobre 40')} · {row.unclassifiedToastOvertimeHours.toFixed(1)} h {t('unclassified Toast','Toast sin clasificar')} ({row.unclassifiedToastEmployees})</small></div></div>)}</div>
        <div className="schedule-recommendation"><strong>💡 {t('Recommended action','Acción recomendada')}</strong>{topRisk.length?<p>{t(`Review ${topRisk.map(row=>row.employeeName).join(' and ')}. Their next shifts account for ${topRisk.reduce((sum,row)=>sum+row.overtimeHours,0).toFixed(1)} h of overtime. Known cost: ${money(topRisk.reduce((sum,row)=>sum+(row.estimatedOvertimeCost??0),0))}${topRisk.some(row=>row.estimatedOvertimeCost===null)?' plus employees without a valid hourly rate.':'.'}`,`Revisa ${topRisk.map(row=>row.employeeName).join(' y ')}. Sus próximos turnos concentran ${topRisk.reduce((sum,row)=>sum+row.overtimeHours,0).toFixed(1)} h de overtime. Costo conocido: ${money(topRisk.reduce((sum,row)=>sum+(row.estimatedOvertimeCost??0),0))}${topRisk.some(row=>row.estimatedOvertimeCost===null)?' más empleados sin tarifa horaria válida.':'.'}`)}</p>:<p>{t('No employees are projected over 40 hours with the current filters.','No hay empleados proyectados sobre 40 horas con los filtros actuales.')}</p>}</div>
      </aside>
    </div>

    {selected&&<div className="schedule-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="schedule-drawer" onClick={event=>event.stopPropagation()}><div className="schedule-drawer-head"><div><span>TOAST + 7SHIFTS OVERTIME REVIEW</span><h2>{selected.employeeName}</h2><p>{selected.primaryLocation} · {selected.role}</p></div><button onClick={()=>setSelected(null)}>×</button></div><div className="schedule-drawer-metrics"><div><label>{t('Toast worked','Trabajadas Toast')}</label><strong>{selected.workedHours.toFixed(1)} h</strong></div><div><label>{t('OT already worked','OT ya trabajado')}</label><strong>{selected.actualOvertimeHours.toFixed(1)} h</strong></div><div><label>{t('Toast rate','Tarifa Toast')}</label><strong>{selected.hourlyWage===null?t('Unavailable','No disponible'):`${money(selected.hourlyWage)}/h`}</strong></div><div><label>{t('7shifts remaining','Restantes 7shifts')}</label><strong>{selected.remainingScheduledHours.toFixed(1)} h</strong></div><div><label>{t('Projection','Proyección')}</label><strong>{selected.projectedHours.toFixed(1)} h</strong></div><div><label>{t('OT / cost','OT / costo')}</label><strong>{selected.overtimeHours.toFixed(1)} h · {cost(selected.estimatedOvertimeCost,t)}</strong></div></div>{selected.nextShift?<div className="schedule-next-shift"><label>{t('NEXT SHIFT TO REVIEW','PRÓXIMO TURNO PARA REVISAR')}</label><strong>{dateTime(selected.nextShift.start)} – {dateTime(selected.nextShift.end)}</strong><p>{selected.nextShift.location} · {selected.nextShift.role}</p></div>:<div className="schedule-next-shift"><label>{t('NEXT SHIFT','PRÓXIMO TURNO')}</label><p>{t('No published shifts remain in this period.','No quedan turnos publicados en este periodo.')}</p></div>}<div className="schedule-drawer-recommendation"><label>{t('OPSVISTA RECOMMENDATION','RECOMENDACIÓN OPSVISTA')}</label><p>{selected.overtimeHours>0?t('Reassign the next shift to a qualified person who will remain under 40 hours. First confirm that required position and rush coverage are preserved.','Reasigna el próximo turno a una persona calificada que permanezca debajo de 40 horas. Confirma primero que se conserve la cobertura necesaria del puesto y del rush.'):t('Keep monitoring. The projection remains below 40 hours with the currently published shifts.','Mantén el monitoreo. La proyección permanece debajo de 40 horas con los turnos publicados actuales.')}</p></div><div className="schedule-drawer-actions"><button className="primary" disabled={!onEscalate||sent.includes(selected.userId)||selected.overtimeHours<=0} onClick={()=>void send(selected)}>{sent.includes(selected.userId)?t('Assigned in Action Center','Asignado en Action Center'):t('Assign to manager','Asignar al manager')}</button><button onClick={()=>setSelected(null)}>{t('Close','Cerrar')}</button></div></aside></div>}
  </div>;
}
