import type { LaborCostSource, LaborReportStatus } from '../shared/laborCostSource';
import { currentAuthenticatedUser } from './accessControl';
import { useMemo, useState } from 'react';
import './scheduleOvertimeMonitor.css';
import './scheduleSalary.css';
import type { ExternalEscalation } from './actionCenterTypes';
import { useI18n } from './i18n';

export type ScheduleShift={id:number;start:string;end:string;location:string;role:string};
type OvertimeCosts={workedOvertimeCostSource?:LaborCostSource;forecastAvailable?:boolean;workedOvertimeCost?:number|null;additionalProjectedOvertimeCost?:number|null;calculatedOvertimeDifferenceHours?:number};
export type ScheduleEmployee=OvertimeCosts&{
  unclassifiedOvertimeHours?:number;userId:number;employeeName:string;primaryLocation:string;locations:string[];role:string;
  workedHours:number;scheduledHours:number;remainingScheduledHours:number;projectedHours:number;
  overtimeHours:number;actualOvertimeHours:number;additionalProjectedOvertimeHours?:number;hourlyWage:number|null;estimatedOvertimeCost:number|null;wageSource:'shift_or_punch'|'user_hourly'|'manual_override'|'unavailable';toastMatchStatus:'matched_external_id'|'matched_name'|'ambiguous'|'unmatched'|'toast_only';employmentType:'hourly'|'salary'|'unknown';nextShift?:ScheduleShift;
  status:'Overtime'|'Risk'|'Safe'|'Salary'|'Unclassified';
};
export type ScheduleLocation=OvertimeCosts&{location:string;monitoredEmployees:number;riskEmployees:number;actualOvertimeHours:number;additionalProjectedOvertimeHours:number;projectedOvertimeHours:number;salaryOver40Hours:number;unclassifiedToastOvertimeHours:number;unclassifiedToastEmployees:number;estimatedOvertimeCost:number|null;employeesMissingHourlyWage:number};
export type ScheduleRisk=OvertimeCosts&{
  scheduleAvailable?:boolean;laborReportStatuses?:LaborReportStatus[];laborReportRetrievedAt?:string;start:string;end:string;generatedAt:string;workedThrough?:string;timeZone?:string;periodClosed?:boolean;payrollReferenceError?:string;payrollReference?:{start:string;end:string;providedAt:string;hours:number;cost:number;locations:{location:string;hours:number;cost:number}[]}|null;thresholdHours:number;scheduledHours:number;riskEmployees:number;
  actualOvertimeHours:number;additionalProjectedOvertimeHours:number;projectedOvertimeHours:number;salaryOver40Hours:number;unclassifiedToastOvertimeHours:number;unclassifiedToastEmployees:number;estimatedOvertimeCost:number|null;employeesMissingHourlyWage:number;unmatchedToastEmployees:number;employees:ScheduleEmployee[];locations:ScheduleLocation[];
};

type Props={
  data:ScheduleRisk|null;
  error?:string;
  loading:boolean;
  onEscalate?:(item:ExternalEscalation)=>Promise<unknown>|void;
  onPayrollImported?:()=>void;
};

const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
const cost=(value:number|null|undefined,t:(en:string,es:string)=>string)=>value==null?t('Incomplete cost','Costo incompleto'):money(value);
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).map(part=>part[0]).join('').slice(0,2).toUpperCase();

export default function ScheduleOvertimeMonitor({data,error,loading,onEscalate,onPayrollImported}:Props){
  const {t,locale}=useI18n();
  const dateTime=(value:string)=>new Intl.DateTimeFormat(locale,{timeZone:'America/New_York',weekday:'short',hour:'numeric',minute:'2-digit'}).format(new Date(value));
  const [importStatus,setImportStatus]=useState('');
  const [importing,setImporting]=useState(false);
  const canImport=['Founder','Corporate','HR'].includes(currentAuthenticatedUser()?.role||'');
  const importPayroll=async(file:File|undefined)=>{
    if(!file)return;setImporting(true);setImportStatus('');
    try{
      if(file.size>65536)throw new Error(t('Use a payroll summary JSON under 64 KB.','Usa un resumen de nómina JSON menor a 64 KB.'));
      const payload=JSON.parse(await file.text());
      const response=await fetch('/api/operations/performance?payroll_reference=true',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
      const result=await response.json();if(!response.ok)throw new Error(result.error||t('Import failed','No se pudo importar'));
      setImportStatus(t(`Saved payroll reference: ${result.start}–${result.end}. Select that week to compare.`,`Referencia guardada: ${result.start}–${result.end}. Selecciona esa semana para comparar.`));onPayrollImported?.();
    }catch(error){setImportStatus(error instanceof Error?error.message:t('Invalid file','Archivo inválido'));}finally{setImporting(false);}
  };
  const [alertAt,setAlertAt]=useState(40);
  const [onlyRisk,setOnlyRisk]=useState(false);
  const [selected,setSelected]=useState<ScheduleEmployee|null>(null);
  const [sent,setSent]=useState<number[]>([]);
  const employees=useMemo(()=>((data?.employees||[])
    .filter(row=>!onlyRisk||(row.employmentType==='hourly'&&row.projectedHours>=alertAt))
    .sort((a,b)=>a.employmentType!==b.employmentType?(a.employmentType==='salary'?1:-1):b.overtimeHours-a.overtimeHours||b.projectedHours-a.projectedHours)),[data,onlyRisk,alertAt]);
  const locationRows=useMemo(()=>(data?.locations||[]),[data]);
  const topRisk=employees.filter(row=>(row.additionalProjectedOvertimeHours??0)>0).sort((a,b)=>(b.additionalProjectedOvertimeHours??0)-(a.additionalProjectedOvertimeHours??0)).slice(0,2);
  const send=async(employee:ScheduleEmployee)=>{
    if(!onEscalate)return;
    try{await onEscalate({location:employee.nextShift?.location||employee.primaryLocation,title:t(`Review projected overtime · ${employee.employeeName}`,`Revisar overtime proyectado · ${employee.employeeName}`),signal:t(`${employee.employeeName} is projected at ${employee.projectedHours.toFixed(2)} h (${employee.overtimeHours.toFixed(2)} h overtime) for ${data?.start}–${data?.end}.`,`${employee.employeeName} está proyectado a ${employee.projectedHours.toFixed(2)} h (${employee.overtimeHours.toFixed(2)} h de overtime) para ${data?.start}–${data?.end}.`),cause:t(`Has ${employee.workedHours.toFixed(2)} worked hours and still has ${employee.remainingScheduledHours.toFixed(2)} scheduled hours remaining.`,`Acumula ${employee.workedHours.toFixed(2)} h trabajadas y todavía tiene ${employee.remainingScheduledHours.toFixed(2)} h programadas por completar.`),recommendation:employee.nextShift?t(`The location manager should speak with ${employee.employeeName}, review or reassign the ${dateTime(employee.nextShift.start)} shift at ${employee.nextShift.location} (${employee.nextShift.role}), and protect required coverage.`,`El location manager debe hablar con ${employee.employeeName}, revisar o reasignar el turno de ${dateTime(employee.nextShift.start)} en ${employee.nextShift.location} (${employee.nextShift.role}) y proteger la cobertura necesaria.`):t(`The location manager should review remaining shifts with ${employee.employeeName} and reassign hours to a qualified person who will remain under 40 hours.`,`El location manager debe revisar con ${employee.employeeName} los turnos restantes y reasignar horas a una persona calificada que permanezca debajo de 40 horas.`),impact:employee.estimatedOvertimeCost===null?t('OT cost unavailable because Toast did not provide a valid hourly rate.','Costo OT no disponible porque Toast no entregó una tarifa horaria válida.'):t(`${money(employee.estimatedOvertimeCost)} OT cost including future estimates`,`${money(employee.estimatedOvertimeCost)} de costo OT incluyendo estimaciones futuras`),severity:employee.overtimeHours>=4?'High':'Medium',accountableName:employee.employeeName,accountableRole:t(`${employee.role} · overtime exposure`,`${employee.role} · exposición a overtime`),automationKey:`overtime::${employee.nextShift?.location||employee.primaryLocation}::${employee.userId}::${data?.start}::${data?.end}`,sources:['Toast Labor','7shifts Schedule'],sourceIds:[String(employee.userId)]});setSent(current=>current.includes(employee.userId)?current:[...current,employee.userId]);}catch(error){if(error instanceof Error&&error.message==='Action assignment cancelled')return;}
  };

  if(loading)return <section className="schedule-panel schedule-loading"><strong>{t('Loading 7shifts schedules and Toast Time Entries…','Cargando horarios de 7shifts y Time Entries de Toast…')}</strong><span>{t('Calculating overtime by employee and location.','Calculando overtime por empleado y ubicación.')}</span></section>;
  if(error&&!data)return <section className="schedule-panel schedule-error"><strong>{t('Projected overtime could not be calculated','No fue posible calcular el overtime proyectado')}</strong><span>{error}</span><small>{t('OpsVista will not show estimates until it receives real 7shifts shifts/roles plus valid Toast hours and rates.','OpsVista no mostrará estimaciones hasta recibir turnos y puestos reales de 7shifts, más horas y tarifas válidas de Toast.')}</small></section>;
  if(!data)return null;

  const sourceLabel=(source:LaborCostSource|undefined)=>source==='toast_reported'?t('Cost reported by Toast','Costo reportado por Toast'):source==='mixed'?t('Part reported, part estimated','Parte reportada, parte estimada'):source==='unavailable'?t('Incomplete historical cost','Costo histórico incompleto'):t('Estimated from time entries · 1.5×','Estimado de marcaciones · 1.5×');
  const forecast=data.forecastAvailable!==false;
  const reportStatus=data.laborReportStatuses||[];
  return <div className="schedule-section">
    <div className="schedule-section-heading"><div><span>TOAST · WORKED LABOR / 7SHIFTS · FORECAST</span><h2>{t('Overtime monitor by employee','Monitor de overtime por empleado')}</h2><p>{data.start} → {data.end} · {t('Wednesday–Tuesday · Connecticut time','Miércoles–martes · Hora de Connecticut')}<br/>{t('Toast through','Toast hasta')} {data.workedThrough||data.end} · {t('Updated','Actualizado')}: {new Date(data.generatedAt).toLocaleString(locale,{timeZone:'America/New_York'})} · {data.periodClosed?t('Past period · no future projection','Periodo pasado · sin proyección futura'):t('Open period · estimates may change','Periodo abierto · las estimaciones pueden cambiar')}</p></div><div className="schedule-controls"><label>{t('Alert at','Alerta a')} <select value={alertAt} onChange={event=>setAlertAt(Number(event.target.value))}><option value={36}>36 h</option><option value={38}>38 h</option><option value={40}>40 h</option></select></label><button className={onlyRisk?'active':''} onClick={()=>setOnlyRisk(value=>!value)}>{t('At risk only','Solo en riesgo')}</button></div></div>

    {(error||!forecast)&&<p role="status">{data.scheduleAvailable===false?t('7shifts schedules are unavailable. Toast worked hours and costs remain visible.','Los horarios de 7shifts no están disponibles. Las horas y costos trabajados de Toast siguen visibles.'):t('Some future shifts need employee linking before a complete forecast can be calculated. All classified Toast hours remain in the worked total.','Algunos turnos futuros requieren vincular empleados para completar la proyección. Todas las horas clasificadas de Toast permanecen en el total trabajado.')}</p>}
    {reportStatus.includes('not_configured')?<p role="status">{t('Toast calculated costs are not connected. Worked costs use historical time-entry estimates.','Los costos calculados de Toast no están conectados. Los costos trabajados usan estimaciones de las marcaciones históricas.')}</p>:reportStatus.some(status=>status!=='ready')&&<p role="status">{reportStatus.includes('mismatch')?t('The Toast cost report does not match the current time entries. Affected locations retain estimated costs.','El reporte de costos de Toast no coincide con las marcaciones actuales. Las locaciones afectadas conservan costos estimados.'):reportStatus.includes('pending')?t('Toast is preparing the cost report. Refresh to check again; estimates remain visible.','Toast está preparando el reporte de costos. Actualiza para revisarlo; las estimaciones siguen visibles.'):t('Toast calculated costs are temporarily unavailable. Estimates remain visible.','Los costos calculados de Toast no están disponibles por ahora. Las estimaciones siguen visibles.')}</p>}
    {data.laborReportRetrievedAt&&<p>{t('Toast cost report retrieved','Reporte de costos Toast consultado')}: {new Date(data.laborReportRetrievedAt).toLocaleString(locale,{timeZone:'America/New_York'})}</p>}
    {canImport&&<div className="schedule-controls"><label>{importing?t('Importing…','Importando…'):t('Import Toast Payroll reference (JSON)','Importar referencia Toast Payroll (JSON)')}<input type="file" accept=".json,application/json" disabled={importing} onChange={event=>{void importPayroll(event.target.files?.[0]);event.target.value='';}}/></label><small>{t('Import the complete period; it replaces the previous reference for that week. Payroll is unchanged.','Importa el periodo completo; sustituye la referencia anterior de esa semana. No modifica la nómina.')}</small></div>}
    {importStatus&&<p role="status">{importStatus}</p>}
    {data.payrollReferenceError&&<p role="status">{t('The saved payroll reference could not be loaded. Live estimates remain available.','No se pudo cargar la referencia guardada de nómina. Las estimaciones en vivo siguen disponibles.')}</p>}
    <section className="schedule-kpis">
      <article><span className="schedule-kpi-icon blue">◷</span><div><label>{t('SCHEDULED HOURS','HORAS PROGRAMADAS')}</label><strong>{data.scheduleAvailable===false?'—':data.scheduledHours.toFixed(2)}</strong><p>{t('7shifts · full published week','7shifts · semana completa publicada')}</p></div></article>
      <article><span className="schedule-kpi-icon red">!</span><div><label>{t('EMPLOYEES AT RISK','EMPLEADOS EN RIESGO')}</label><strong>{data.riskEmployees}</strong><p>{t('Projected over 40 hours','Proyectados sobre 40 horas')}</p></div></article>
      <article><span className="schedule-kpi-icon red">✓</span><div><label>{t('RECORDED OT · TOAST','OT REGISTRADO · TOAST')}</label><strong>{data.actualOvertimeHours.toFixed(2)} h</strong><p>{t('Reported by Toast · payroll pending reconciliation','Reportado por Toast · pendiente de conciliar con nómina')}</p></div></article>
      <article><span className="schedule-kpi-icon amber">↗</span><div><label>{t('ADDITIONAL SCHEDULED OT','OT ADICIONAL PROGRAMADO')}</label><strong>{forecast?`${data.additionalProjectedOvertimeHours.toFixed(2)} h`:'—'}</strong><p>{t('Remaining exposure in 7shifts','Exposición restante en 7shifts')}</p></div></article>
      <article><span className="schedule-kpi-icon amber">Σ</span><div><label>{t('TOTAL PROJECTED OT','OT TOTAL PROYECTADO')}</label><strong>{forecast?`${data.projectedOvertimeHours.toFixed(2)} h`:'—'}</strong><p>{t('Worked + additional exposure','Trabajado + exposición adicional')}</p></div></article>
      <article><span className="schedule-kpi-icon blue">i</span><div><label>{t('SALARIED OVER 40 H','SALARIADOS SOBRE 40 H')}</label><strong>{data.salaryOver40Hours.toFixed(2)} h</strong><p>{t('Separate from hourly reconciliation','Separado de la conciliación por hora')}</p></div></article>
      <article><span className="schedule-kpi-icon amber">?</span><div><label>{t('UNCLASSIFIED TOAST OT','OT TOAST SIN CLASIFICAR')}</label><strong>{data.unclassifiedToastOvertimeHours.toFixed(2)} h</strong><p>{data.unclassifiedToastEmployees} {t('employees with unresolved pay classification','empleados con clasificación salarial pendiente')}</p></div></article>
      <article><span className="schedule-kpi-icon green">$</span><div><label>{data.workedOvertimeCostSource==='toast_reported'?t('WORKED OT · TOAST COST','OT TRABAJADO · COSTO TOAST'):t('WORKED OT · ESTIMATED COST','OT TRABAJADO · COSTO ESTIMADO')}</label><strong>{cost(data.workedOvertimeCost,t)}</strong><p>{sourceLabel(data.workedOvertimeCostSource)}</p></div></article>
      <article><span className="schedule-kpi-icon amber">$</span><div><label>{t('ADDITIONAL OT · ESTIMATED COST','OT ADICIONAL · COSTO ESTIMADO')}</label><strong>{cost(data.additionalProjectedOvertimeCost,t)}</strong><p>{t('Remaining shifts only · estimated rate','Solo turnos restantes · tarifa estimada')}</p></div></article>
      <article><span className="schedule-kpi-icon green">Σ</span><div><label>{t('TOTAL OT · ESTIMATED COST','OT TOTAL · COSTO ESTIMADO')}</label><strong>{cost(data.estimatedOvertimeCost,t)}</strong><p>{t('Worked cost + future estimate · reconcile with payroll','Costo trabajado + estimado futuro · conciliar con nómina')}{data.employeesMissingHourlyWage?t(` · ${data.employeesMissingHourlyWage} without complete rates`,` · ${data.employeesMissingHourlyWage} sin tarifas completas`):''}</p></div></article>
    </section>

    {Boolean(data.calculatedOvertimeDifferenceHours)&&<section className="schedule-panel"><p>{t('40-hour calculation vs. Toast reported OT','Cálculo sobre 40 horas vs. OT reportado por Toast')}: <strong>{data.calculatedOvertimeDifferenceHours?.toFixed(2)} h</strong>. {t('Review by employee; this difference is excluded from recorded and future OT.','Revisar por empleado; esta diferencia se mantiene fuera del OT registrado y futuro.')}</p></section>}
    {data.payrollReference&&<section className="schedule-panel">
      <div className="schedule-panel-head"><div><h3>{t('Toast Payroll reconciliation','Conciliación con Toast Payroll')}</h3><p>{data.payrollReference.start} → {data.payrollReference.end} · {t('Imported final payroll reference dated','Referencia importada de nómina final con fecha')} {data.payrollReference.providedAt}. {t('All classified hourly Toast entries are included, with or without a 7shifts link.','Se incluyen todas las marcaciones Toast clasificadas por hora, con o sin vínculo a 7shifts.')}</p></div><strong>{money(data.payrollReference.cost)} · {data.payrollReference.hours.toFixed(2)} h</strong></div>
      <div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>{t('Location','Locación')}</th><th>{t('Paid OT hours','Horas OT pagadas')}</th><th>{t('Paid OT cost','Costo OT pagado')}</th><th>{t('Toast recorded hours','Horas registradas Toast')}</th><th>{t('Worked cost / source','Costo trabajado / fuente')}</th><th>{t('Hours difference','Diferencia horas')}</th><th>{t('Cost difference','Diferencia costo')}</th></tr></thead><tbody>{data.payrollReference.locations.map(paid=>{const live=locationRows.find(row=>row.location.toLowerCase()===paid.location.toLowerCase());return <tr key={paid.location}><td>{paid.location}</td><td>{paid.hours.toFixed(2)}</td><td>{money(paid.cost)}</td><td>{live?.actualOvertimeHours.toFixed(2)??'—'}</td><td>{cost(live?.workedOvertimeCost,t)}<small>{sourceLabel(live?.workedOvertimeCostSource)}</small></td><td>{live?(live.actualOvertimeHours-paid.hours).toFixed(2):'—'}</td><td>{live?.workedOvertimeCost==null?'—':money(live.workedOvertimeCost-paid.cost)}</td></tr>;})}</tbody></table></div>
    </section>}

    <div className="schedule-main-grid">
      <section className="schedule-panel schedule-employee-panel">
        <div className="schedule-panel-head"><div><h3>{t('Hours by employee','Horas por empleado')}</h3><p>{t('All worked hours: Toast · Future schedules: 7shifts.','Todas las horas trabajadas: Toast · Turnos futuros: 7shifts.')}{data.unmatchedToastEmployees?` ${data.unmatchedToastEmployees} ${t('employees require cross-system linking.','empleados requieren vinculación entre sistemas.')}`:''}</p></div><span>{employees.length} {t('employees','empleados')}</span></div>
        <div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>{t('Employee','Empleado')}</th><th>{t('Location / role','Locación / puesto')}</th><th>{t('Toast worked','Trabajadas Toast')}</th><th>{t('Toast rate','Tarifa Toast')}</th><th>{t('7shifts scheduled','Programadas 7shifts')}</th><th>{t('Projection','Proyección')}</th><th>{t('Projected OT','OT proyectado')}</th><th>{t('Next shift','Próximo turno')}</th><th>{t('Action','Acción')}</th></tr></thead><tbody>
          {employees.map(employee=>{const salaried=employee.employmentType==='salary',unknown=employee.employmentType==='unknown';const progress=Math.min(100,employee.workedHours/40*100);const atRisk=!salaried&&!unknown&&employee.projectedHours>=alertAt;return <tr key={employee.userId} className={employee.overtimeHours>0?'schedule-overtime-row':atRisk?'schedule-risk-row':salaried?'schedule-salary-row':''}>
            <td><div className="schedule-person"><span>{initials(employee.employeeName)}</span><div><strong>{employee.employeeName}</strong>{unknown?<small>{t('Pay classification pending','Clasificación salarial pendiente')}</small>:employee.toastMatchStatus==='toast_only'?<small>{t('Toast record · no schedule link','Registro Toast · sin vínculo de horario')}</small>:salaried?<small>{t('Salaried employee','Personal asalariado')}</small>:employee.wageSource==='manual_override'&&!employee.toastMatchStatus.startsWith('matched')?<small>{t('Configured rate · unlinked Toast hours','Tarifa configurada · horas Toast sin vincular')}</small>:!employee.toastMatchStatus.startsWith('matched')&&<small>{t('No confirmed Toast link','Sin vínculo confirmado con Toast')}</small>}</div></div></td>
            <td><strong>{employee.primaryLocation}</strong><small>{employee.role}{employee.locations.length>1?` · ${employee.locations.length} ${t('locations','locaciones')}`:''}</small></td>
            <td><strong>{employee.workedHours.toFixed(2)} h</strong><small>{unknown?`${(employee.unclassifiedOvertimeHours??0).toFixed(2)} h ${t('OT pending classification','OT por clasificar')}`:salaried?t('Recorded coverage hours','Horas de cobertura registradas'):t(`${employee.actualOvertimeHours.toFixed(2)} h OT already worked`,`${employee.actualOvertimeHours.toFixed(2)} h OT ya trabajadas`)}</small>{Boolean(employee.calculatedOvertimeDifferenceHours)&&<small>{t('40-hour rule difference','Diferencia regla 40 h')}: {employee.calculatedOvertimeDifferenceHours?.toFixed(2)} h</small>}<div className="schedule-progress"><i style={{width:`${progress}%`}} className={employee.overtimeHours>0?'danger':atRisk?'warning':''}/></div></td>
            <td><strong>{salaried?t('Salary','Salario'):employee.hourlyWage===null?'—':`${money(employee.hourlyWage)}/h`}</strong><small>{salaried?t('No hourly rate','No usa tarifa por hora'):employee.hourlyWage===null?t('No valid hourly rate','Sin tarifa horaria válida'):employee.wageSource==='manual_override'?t('Configured rate','Tarifa configurada'):'Time Entry Management'}</small></td>
            <td><strong>{data.scheduleAvailable===false||employee.toastMatchStatus==='toast_only'?'—':`${employee.scheduledHours.toFixed(2)} h`}</strong><small>{employee.remainingScheduledHours.toFixed(2)} h {t('remaining','restantes')}</small></td>
            <td><strong className={employee.overtimeHours>0?'schedule-danger-text':''}>{employee.forecastAvailable===false?'—':`${employee.projectedHours.toFixed(2)} h`}</strong>{salaried&&<small>{t('Salaried coverage','Cobertura asalariada')}</small>}</td>
            <td>{unknown?<span>{t('Unclassified','Sin clasificar')}</span>:salaried?<span className="schedule-salary-pill">{t('Salary · OT does not apply','Salario · OT no aplica')}</span>:employee.overtimeHours>0?<><span className="schedule-ot-pill">+{employee.overtimeHours.toFixed(2)} h</span><small>{t('Worked','Trabajado')}: {cost(employee.workedOvertimeCost,t)}</small><small>{sourceLabel(employee.workedOvertimeCostSource)}</small><small>{t('Additional','Adicional')}: {cost(employee.additionalProjectedOvertimeCost,t)}</small></>:atRisk?<span className="schedule-risk-pill">{t('Near limit','Cerca del límite')}</span>:<span className="schedule-safe-pill">{t('No OT','Sin OT')}</span>}</td>
            <td>{employee.nextShift?<><strong>{dateTime(employee.nextShift.start)}</strong><small>{employee.nextShift.location} · {employee.nextShift.role}</small></>:<span>{t('No remaining shifts','Sin turnos restantes')}</span>}</td>
            <td><button disabled={salaried||unknown} onClick={()=>setSelected(employee)}>{salaried?t('Salary','Salario'):t('Review','Revisar')}</button></td>
          </tr>})}
          {!employees.length&&<tr><td colSpan={9}><div className="schedule-empty">{t('No employees match these filters.','No hay empleados que coincidan con estos filtros.')}</div></td></tr>}
        </tbody></table></div>
      </section>

      <aside className="schedule-panel schedule-location-panel"><div className="schedule-panel-head"><div><h3>{t('Risk by location','Riesgo por locación')}</h3><p>{t('Worked OT is assigned to the recording restaurant. Future exposure is assigned to the next scheduled location.','El OT trabajado se asigna al restaurante que lo registró. La exposición futura se asigna a la locación del próximo turno.')}</p></div></div><div className="schedule-location-list">{locationRows.map(row=><div key={row.location}><div><strong>{row.location}</strong><small>{row.riskEmployees?t(`${row.riskEmployees} hourly at risk · `,`${row.riskEmployees} hourly en riesgo · `):''}{row.monitoredEmployees} {t('monitored','monitoreados')}</small></div><div className={row.projectedOvertimeHours>0?'danger':'safe'}><strong>{row.forecastAvailable===false?'—':`${row.projectedOvertimeHours.toFixed(2)} h`} {t('total hourly OT','OT hourly total')}</strong><small>{row.actualOvertimeHours.toFixed(2)} h {t('recorded','registradas')} · {cost(row.workedOvertimeCost,t)}</small><small>{sourceLabel(row.workedOvertimeCostSource)}</small><small>{row.forecastAvailable===false?'—':`${row.additionalProjectedOvertimeHours.toFixed(2)} h`} {t('additional','adicionales')} · {cost(row.additionalProjectedOvertimeCost,t)}</small><small>{t('Total estimate','Estimado total')}: {cost(row.estimatedOvertimeCost,t)}{row.employeesMissingHourlyWage?t(` · ${row.employeesMissingHourlyWage} without rate`,` · ${row.employeesMissingHourlyWage} sin tarifa`):''}</small>{Boolean(row.calculatedOvertimeDifferenceHours)&&<small>{t('40-hour rule difference','Diferencia regla 40 h')}: {row.calculatedOvertimeDifferenceHours?.toFixed(2)} h</small>}<small>{row.salaryOver40Hours.toFixed(2)} h {t('salaried over 40','asalariadas sobre 40')} · {row.unclassifiedToastOvertimeHours.toFixed(2)} h {t('unclassified Toast','Toast sin clasificar')} ({row.unclassifiedToastEmployees})</small></div></div>)}</div>
        <div className="schedule-recommendation"><strong>💡 {t('Recommended action','Acción recomendada')}</strong>{!forecast?<p>{t('Restore schedule access or resolve employee links to complete the forecast.','Restablece el acceso a horarios o resuelve los vínculos de empleados para completar la proyección.')}</p>:topRisk.length?<p>{t(`Review ${topRisk.map(row=>row.employeeName).join(' and ')}. Their next shifts account for ${topRisk.reduce((sum,row)=>sum+(row.additionalProjectedOvertimeHours??0),0).toFixed(2)} h of overtime. Known cost: ${money(topRisk.reduce((sum,row)=>sum+(row.additionalProjectedOvertimeCost??0),0))}${topRisk.some(row=>row.additionalProjectedOvertimeCost==null)?' plus employees without a valid hourly rate.':'.'}`,`Revisa ${topRisk.map(row=>row.employeeName).join(' y ')}. Sus próximos turnos concentran ${topRisk.reduce((sum,row)=>sum+(row.additionalProjectedOvertimeHours??0),0).toFixed(2)} h de overtime. Costo conocido: ${money(topRisk.reduce((sum,row)=>sum+(row.additionalProjectedOvertimeCost??0),0))}${topRisk.some(row=>row.additionalProjectedOvertimeCost==null)?' más empleados sin tarifa horaria válida.':'.'}`)}</p>:<p>{t('No additional OT from remaining shifts with the current filters.','No hay OT adicional por turnos restantes con los filtros actuales.')}</p>}</div>
      </aside>
    </div>

    {selected&&<div className="schedule-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="schedule-drawer" onClick={event=>event.stopPropagation()}><div className="schedule-drawer-head"><div><span>TOAST + 7SHIFTS OVERTIME REVIEW</span><h2>{selected.employeeName}</h2><p>{selected.primaryLocation} · {selected.role}</p></div><button onClick={()=>setSelected(null)}>×</button></div><div className="schedule-drawer-metrics"><div><label>{t('Toast worked','Trabajadas Toast')}</label><strong>{selected.workedHours.toFixed(2)} h</strong></div><div><label>{t('OT already worked','OT ya trabajado')}</label><strong>{selected.actualOvertimeHours.toFixed(2)} h</strong></div><div><label>{t('Toast rate','Tarifa Toast')}</label><strong>{selected.hourlyWage===null?t('Unavailable','No disponible'):`${money(selected.hourlyWage)}/h`}</strong></div><div><label>{t('7shifts remaining','Restantes 7shifts')}</label><strong>{selected.remainingScheduledHours.toFixed(2)} h</strong></div><div><label>{t('Projection','Proyección')}</label><strong>{selected.projectedHours.toFixed(2)} h</strong></div><div><label>{t('OT / cost','OT / costo')}</label><strong>{selected.overtimeHours.toFixed(2)} h · {cost(selected.estimatedOvertimeCost,t)}</strong></div></div>{selected.nextShift?<div className="schedule-next-shift"><label>{t('NEXT SHIFT TO REVIEW','PRÓXIMO TURNO PARA REVISAR')}</label><strong>{dateTime(selected.nextShift.start)} – {dateTime(selected.nextShift.end)}</strong><p>{selected.nextShift.location} · {selected.nextShift.role}</p></div>:<div className="schedule-next-shift"><label>{t('NEXT SHIFT','PRÓXIMO TURNO')}</label><p>{t('No published shifts remain in this period.','No quedan turnos publicados en este periodo.')}</p></div>}<div className="schedule-drawer-recommendation"><label>{t('OPSVISTA RECOMMENDATION','RECOMENDACIÓN OPSVISTA')}</label><p>{(selected.additionalProjectedOvertimeHours??0)>0?t('Reassign the next shift to a qualified person who will remain under 40 hours. First confirm that required position and rush coverage are preserved.','Reasigna el próximo turno a una persona calificada que permanezca debajo de 40 horas. Confirma primero que se conserve la cobertura necesaria del puesto y del rush.'):t('No additional projected OT. Review any difference against final payroll.','No hay OT adicional proyectado. Revisa cualquier diferencia contra la nómina final.')}</p></div><div className="schedule-drawer-actions"><button className="primary" disabled={!onEscalate||sent.includes(selected.userId)||(selected.additionalProjectedOvertimeHours??0)<=0} onClick={()=>void send(selected)}>{sent.includes(selected.userId)?t('Assigned in Action Center','Asignado en Action Center'):t('Assign to manager','Asignar al manager')}</button><button onClick={()=>setSelected(null)}>{t('Close','Cerrar')}</button></div></aside></div>}
  </div>;
}
