import { useEffect, useMemo, useState } from 'react';
import CustomDateRangePicker from './CustomDateRangePicker';
import MaxDataInsights from './MaxDataInsights';
import './sevenShiftsTasks.css';

type TaskDetail={key:string;date:string;locationId:number;locationName:string;taskListId?:number;taskListName?:string;position?:string;frequency?:string;taskId?:number;taskName:string;userId?:number;userName?:string;completed:boolean;completedAt?:string;late?:boolean};
type Day={date:string;total:number;completed:number;incomplete:number;completionPct:number|null;accountability?:TaskDetail[];detailAvailable?:boolean};
type Person={userId?:number;userName:string;completed:number;incomplete:number;late:number;tasks:number};
type LocationWeek={locationId:number;locationName:string;total:number;completed:number;incomplete:number;completionPct:number|null;detailAvailable?:boolean;accountability?:TaskDetail[];days:Day[]};
type LogbookEntry={id:number;date:string;locationName:string;author:string;category:string;message:string;attachments:number};
type Response={source?:string;start?:string;end?:string;total?:number;completed?:number;incomplete?:number;completionPct?:number|null;detailAvailable?:boolean;accountability?:TaskDetail[];people?:Person[];locations?:LocationWeek[];logbook?:LogbookEntry[];logbookComplete?:boolean;logbookError?:string;error?:string;configured?:boolean;adapterVersion?:string;taskSource?:string;availableLocationCount?:number;httpStatus?:number;serverVersion?:string};
type Period='today'|'yesterday'|'this-week'|'previous-week'|'this-month'|'last-30-days'|'custom';
type DetailFilter='all'|'pending'|'completed';
type TaskGroup={key:string;name:string;position:string;frequency?:string;taskListId?:number;tasks:TaskDetail[]};

const pct=(value:number|null|undefined)=>value===null||value===undefined?'—':`${value.toFixed(1)}%`;
const easternToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const addDays=(value:string,days:number)=>{const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)};
const dayOfWeek=(value:string)=>new Date(`${value}T12:00:00Z`).getUTCDay();
const fmtDate=(value:string)=>new Date(`${value}T12:00:00Z`).toLocaleDateString('en-US',{timeZone:'UTC',month:'short',day:'numeric'});
const fmtDateLong=(value:string)=>new Date(`${value}T12:00:00Z`).toLocaleDateString('es-US',{timeZone:'UTC',weekday:'long',month:'long',day:'numeric',year:'numeric'});
const fmtTime=(value?:string)=>value?new Date(value).toLocaleString('es-US',{timeZone:'America/New_York',month:'numeric',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'}):'';

function selectedRange(key:Period,customStart:string,customEnd:string){
  const today=easternToday();const sinceWednesday=(dayOfWeek(today)-3+7)%7;const weekStart=addDays(today,-sinceWednesday);
  if(key==='custom')return{start:customStart,end:customEnd};
  if(key==='today')return{start:today,end:today};
  if(key==='yesterday'){const yesterday=addDays(today,-1);return{start:yesterday,end:yesterday};}
  if(key==='previous-week')return{start:addDays(weekStart,-7),end:addDays(weekStart,-1)};
  if(key==='this-month')return{start:`${today.slice(0,7)}-01`,end:today};
  if(key==='last-30-days')return{start:addDays(today,-29),end:today};
  return{start:weekStart,end:today};
}

function groupTasks(tasks:TaskDetail[]):TaskGroup[]{
  const groups=new Map<string,TaskGroup>();
  for(const task of tasks){
    const name=task.taskListName||`${task.position||'General'} Tasks`;const key=String(task.taskListId??name);
    const group=groups.get(key)??{key,name,position:task.position||'Position not returned',frequency:task.frequency,taskListId:task.taskListId,tasks:[]};
    group.tasks.push(task);groups.set(key,group);
  }
  return Array.from(groups.values()).sort((left,right)=>{const leftPending=left.tasks.filter(task=>!task.completed).length,rightPending=right.tasks.filter(task=>!task.completed).length;return rightPending-leftPending||left.position.localeCompare(right.position)||left.name.localeCompare(right.name)});
}

export default function SevenShiftsTasksPanel({allowedLocations}:{allowedLocations?:string[]}){
  const today=easternToday();
  const [period,setPeriod]=useState<Period>(()=>{if(typeof window==='undefined'||!window.localStorage.getItem('opsvista-tasks-period-v2'))return'today';const saved=window.localStorage.getItem('opsvista-tasks-period')??window.sessionStorage.getItem('opsvista-tasks-period');return saved&&['today','yesterday','this-week','previous-week','this-month','last-30-days','custom'].includes(saved)?saved as Period:'today'});
  const [customStart,setCustomStart]=useState(()=>typeof window!=='undefined'?(window.localStorage.getItem('opsvista-tasks-custom-start')||today):today);
  const [customEnd,setCustomEnd]=useState(()=>typeof window!=='undefined'?(window.localStorage.getItem('opsvista-tasks-custom-end')||today):today);
  const [selected,setSelected]=useState(()=>{const saved=typeof window!=='undefined'?window.localStorage.getItem('opsvista-tasks-location'):null;return saved&&allowedLocations?.includes(saved)?saved:allowedLocations?.length===1?allowedLocations[0]:'All locations'});
  const [selectedDay,setSelectedDay]=useState('');const [detailFilter,setDetailFilter]=useState<DetailFilter>('all');const [data,setData]=useState<Response>({});const [loading,setLoading]=useState(true);const [readAt,setReadAt]=useState('');const [actionNotice,setActionNotice]=useState('');const [actionError,setActionError]=useState('');
  const week=useMemo(()=>selectedRange(period,customStart,customEnd),[period,customStart,customEnd]);
  const rangeDays=Math.floor((Date.parse(`${week.end}T00:00:00Z`)-Date.parse(`${week.start}T00:00:00Z`))/86400000)+1;
  const rangeError=!week.start||!week.end||rangeDays<1?'Choose a valid start and end date.':rangeDays>31?'The custom Tasks range can include up to 31 days.':undefined;

  useEffect(()=>{window.sessionStorage.setItem('opsvista-tasks-period',period);window.localStorage.setItem('opsvista-tasks-period',period);window.localStorage.setItem('opsvista-tasks-period-v2','1');window.localStorage.setItem('opsvista-tasks-custom-start',customStart);window.localStorage.setItem('opsvista-tasks-custom-end',customEnd);window.localStorage.setItem('opsvista-tasks-location',selected)},[period,customStart,customEnd,selected]);
  useEffect(()=>{if(rangeError){setLoading(false);return;}let cancelled=false;const run=async()=>{setLoading(true);setActionNotice('');setActionError('');try{const params=new URLSearchParams({start:week.start,end:week.end});if(selected!=='All locations')params.set('location',selected);const response=await fetch(`/api/tasks/weekly?${params}`,{credentials:'include',cache:'no-store'});const body=await response.json().catch(()=>({})) as Response;const serverVersion=response.headers.get('x-opsvista-workflow-version')||undefined;const result:Response=!response.ok?{...body,error:body.error||`7shifts request failed (${response.status})`,httpStatus:response.status,serverVersion}:!body.adapterVersion?{...body,error:`The Tasks API is running an outdated adapter${serverVersion?` (${serverVersion})`:''}. A current production deployment is required.`,httpStatus:response.status,serverVersion}:{...body,httpStatus:response.status,serverVersion};if(!cancelled){setData(result);setReadAt(new Date().toISOString());}}catch(error){if(!cancelled)setData({error:error instanceof Error?error.message:'Unable to load 7shifts Tasks'});}finally{if(!cancelled)setLoading(false);}};void run();return()=>{cancelled=true};},[selected,week.start,week.end,rangeError]);

  const locations=data.locations||[],people=data.people||[],logbook=data.logbook||[];
  const options=allowedLocations?.length?allowedLocations:Array.from(new Set(locations.map(location=>location.locationName)));
  const selectedLocation=locations.find(location=>location.locationName===selected);const detailDays=selectedLocation?.days||[];
  useEffect(()=>{if(!detailDays.length){setSelectedDay('');return;}setSelectedDay(current=>detailDays.some(day=>day.date===current)?current:([...detailDays].reverse().find(day=>day.total>0)?.date||detailDays.at(-1)?.date||''));},[selectedLocation?.locationId,week.start,week.end,detailDays.length]);
  const detailDay=detailDays.find(day=>day.date===selectedDay);const allDetailTasks=detailDay?.accountability||[];const filteredDetailTasks=allDetailTasks.filter(task=>detailFilter==='all'||(detailFilter==='completed'?task.completed:!task.completed));const taskGroups=groupTasks(filteredDetailTasks);

  const sendGroupToActionCenter=async(group:TaskGroup)=>{if(!detailDay||!selectedLocation)return;const pending=group.tasks.filter(task=>!task.completed);if(!pending.length)return;setActionNotice('');setActionError('');try{const response=await fetch('/api/workflows?resource=actions',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:selectedLocation.locationName,category:'7shifts Tasks',title:`${pending.length} pending · ${group.name}`,severity:pending.length>=5?'High':'Medium',signal:`${pending.length} of ${group.tasks.length} returned task items are pending for ${detailDay.date}: ${pending.slice(0,5).map(task=>task.taskName).join('; ')}`,cause:`The ${group.position} checklist remained incomplete in 7shifts for the selected operating day.`,recommendation:`Contact the ${group.position} lead, complete or document each pending item, and verify the checklist before close.`,impact:'Operational standard and Weekly Bonus eligibility may be affected.',automationKey:`7shifts-tasks::${selectedLocation.locationName}::${detailDay.date}::${group.taskListId??group.name}`,automated:true,priorityScore:pending.length>=5?85:60,sources:['7shifts Tasks'],sourceIds:pending.map(task=>task.key),detectedAt:new Date().toISOString()})});const body=await response.json().catch(()=>({})) as {action?:{id:string};error?:string};if(!response.ok||!body.action)throw new Error(body.error||'Action could not be created');setActionNotice(`Action ${body.action.id} saved for ${group.name}.`);}catch(error){setActionError(error instanceof Error?error.message:'Action could not be created');}};

  return <section className="panel seven-tasks-panel"><div className="panel-header seven-tasks-header"><div><h2>7shifts Tasks · Accountability</h2><p>{fmtDate(week.start)}–{fmtDate(week.end)} · Semana operativa miércoles–martes · Bono mínimo 80%</p></div><div className="seven-tasks-controls"><select value={period} onChange={event=>setPeriod(event.target.value as Period)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this-week">This week</option><option value="previous-week">Prior week</option><option value="this-month">This month</option><option value="last-30-days">Last 30 days</option><option value="custom">Custom</option></select><CustomDateRangePicker active={period==='custom'} start={customStart} end={customEnd} maxDate={today} maxRangeDays={31} onApply={(start,end)=>{setCustomStart(start);setCustomEnd(end);}} ariaLabel="Seleccionar periodo de Tasks"/><select value={selected} onChange={event=>setSelected(event.target.value)}><option>All locations</option>{options.map(location=><option key={location}>{location}</option>)}</select></div></div>
    <div className="seven-tasks-body">{rangeError?<div className="detail-block"><label>DATE RANGE</label><p>{rangeError}</p></div>:loading?<div className="detail-block"><label>7SHIFTS</label><p>Loading live task compliance…</p></div>:data.error?<div className="detail-block"><label>7SHIFTS CONNECTION</label><p>{data.error}</p><p className="seven-muted">HTTP {data.httpStatus??'unavailable'} · Server {data.serverVersion||'unidentified'}. No test percentage is shown as live.</p></div>:<>
      <div className="seven-source"><div><span>LIVE SOURCE VERIFIED</span><strong>{data.availableLocationCount??locations.length} locations · {data.taskSource||'unknown adapter'} · {data.adapterVersion||data.serverVersion||'unversioned'}</strong></div><small>Lectura {readAt?new Date(readAt).toLocaleString('es-US',{timeZone:'America/New_York'}):'—'} ET</small></div>
      <div className="metrics-grid seven-task-metrics"><div className="metric-card"><div className="metric-label">TASK COMPLETION</div><div className="metric-value">{pct(data.completionPct)}</div><div className="metric-note">{data.total?`${data.completed||0} of ${data.total} completed`:'No task records returned'}</div></div><div className="metric-card"><div className="metric-label">INCOMPLETE</div><div className="metric-value">{data.total?data.incomplete||0:'—'}</div><div className="metric-note">Selected period</div></div><div className="metric-card"><div className="metric-label">BONUS GATE</div><div className="metric-value compact">{data.completionPct===null||data.completionPct===undefined?'Pending':data.completionPct>=80?'PASS':'FAIL'}</div><div className="metric-note">Requires Tasks ≥ 80%</div></div></div>
      {!!locations.length&&<MaxDataInsights title="Tasks por locación" subtitle="Cumplimiento y pendientes en una vista comparable; pulsa cualquier elemento para actualizar conclusiones y detalle." rows={locations.map(row=>({location:row.locationName,primary:row.completionPct??0,secondary:row.incomplete,status:row.completionPct===null?'neutral':row.completionPct<80?'bad':row.completionPct<90?'watch':'good'}))} primaryLabel="Cumplimiento" secondaryLabel="Tasks incompletas" primaryFormat={value=>`${value.toFixed(1)}%`} secondaryFormat={value=>value.toFixed(0)} conclusion={filtered=>{if(!filtered.length)return['Sin Tasks verificables para este filtro.'];const compliance=[...filtered].sort((a,b)=>a.primary-b.primary);const incomplete=[...filtered].sort((a,b)=>(b.secondary??0)-(a.secondary??0));const fail=filtered.filter(row=>row.primary<80);return[`${compliance[0].location} tiene el menor cumplimiento: ${compliance[0].primary.toFixed(1)}%.`,`${incomplete[0].location} concentra ${(incomplete[0].secondary??0).toFixed(0)} Tasks incompletas.`,fail.length?`${fail.map(row=>row.location).join(', ')} no cumple${fail.length===1?'':'n'} el gate de 80%.`:'Todas las locaciones visibles cumplen el gate de Tasks.'];}}/>}
      {!data.total&&<div className="detail-block"><label>7SHIFTS TASK DATA</label><p>7shifts returned no task records for this exact period and location selection. OpsVista will not interpret an empty response as 0% or 100% compliance.</p></div>}
      <div className="seven-location-table"><table><thead><tr>{['LOCATION','COMPLETED','TOTAL','INCOMPLETE','COMPLIANCE','BONUS TASK GATE','DETAIL'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{locations.map(location=><tr key={location.locationId}><td>{location.locationName}</td><td>{location.completed}</td><td>{location.total}</td><td className={location.incomplete?'needs-followup':''}>{location.incomplete}</td><td>{pct(location.completionPct)}</td><td>{location.completionPct===null?'Pending':location.completionPct>=80?'PASS':'FAIL'}</td><td><button onClick={()=>setSelected(location.locationName)}>Abrir día →</button></td></tr>)}</tbody></table></div>
      <section className="seven-day-detail">{selected==='All locations'?<div className="seven-detail-empty"><strong>Selecciona una locación para abrir el detalle diario.</strong><span>El detalle individual se consulta por restaurante para conservar nombres de checklist, posiciones, responsables y horas reales de 7shifts.</span><div>{locations.map(location=><button key={location.locationId} onClick={()=>setSelected(location.locationName)}>{location.locationName}<small>{location.completed}/{location.total}</small></button>)}</div></div>:!selectedLocation?<div className="seven-detail-empty"><strong>No se recibió detalle para {selected}.</strong><span>La ubicación seguirá visible en el selector, pero OpsVista no inventará checklists.</span></div>:<>
        <div className={`seven-day-banner ${detailDay?.incomplete?'pending':'complete'}`}><strong>{detailDay?.total?detailDay.incomplete?`⚠ ${detailDay.incomplete} Tasks pendientes en este día.`:'✓ Día completo, sin Tasks pendientes.':'Sin Tasks devueltas para este día.'}</strong><span>{selectedLocation.locationName} · {detailDay?fmtDateLong(detailDay.date):'Selecciona un día'}</span></div>
        <div className="seven-day-heading"><div><span>DETALLE DEL DÍA</span><h3>{selectedLocation.locationName}</h3><p>{detailDay?fmtDateLong(detailDay.date):'—'} · lectura {readAt?new Date(readAt).toLocaleTimeString('es-US',{timeZone:'America/New_York'}):'—'} ET</p></div><div className="seven-task-filter"><button className={detailFilter==='all'?'active':''} onClick={()=>setDetailFilter('all')}>Todas</button><button className={detailFilter==='pending'?'active':''} onClick={()=>setDetailFilter('pending')}>Pendientes</button><button className={detailFilter==='completed'?'active':''} onClick={()=>setDetailFilter('completed')}>Completadas</button></div></div>
        <div className="seven-day-tabs">{detailDays.map(day=><button key={day.date} className={selectedDay===day.date?'active':''} onClick={()=>setSelectedDay(day.date)}><span>{fmtDate(day.date)}</span><strong>{day.completed}/{day.total}</strong><small>{day.incomplete?`${day.incomplete} pendientes`:'Completo'}</small></button>)}</div>
        {actionNotice&&<div className="seven-action-notice success">{actionNotice}</div>}{actionError&&<div className="seven-action-notice error">{actionError}</div>}
        {!detailDay?.detailAvailable?<div className="seven-detail-empty"><strong>7shifts devolvió el total, pero no los elementos individuales.</strong><span>El porcentaje y los conteos siguen siendo reales. Los nombres, responsables y horas aparecerán solamente cuando el endpoint incluya detalle verificable.</span></div>:!taskGroups.length?<div className="seven-detail-empty"><strong>No hay Tasks para el filtro seleccionado.</strong><span>Cambia entre Todas, Pendientes y Completadas.</span></div>:<div className="seven-task-groups">{taskGroups.map(group=>{const completed=group.tasks.filter(task=>task.completed).length,pending=group.tasks.length-completed;return <article key={group.key} className="seven-task-group"><header><div><span>{group.position}</span><h4>{group.name}</h4><small>{group.frequency||'Frecuencia no devuelta'}</small></div><div><strong>{completed}/{group.tasks.length}</strong><small>{pending?`${pending} pendientes`:'Completa'}</small>{pending?<button onClick={()=>void sendGroupToActionCenter(group)}>Enviar a Action Center</button>:null}</div></header><div>{group.tasks.map(task=><div key={task.key} className={`seven-task-item ${task.completed?'completed':'pending'}`}><i>{task.completed?'✓':'!'}</i><strong>{task.taskName}</strong><span><b>{task.completed?'Completada':'Pendiente'}</b>{task.completed?<>{task.userName?` · Por ${task.userName}`:' · Responsable no devuelto'}{task.completedAt?<small>{fmtTime(task.completedAt)} ET{task.late?' · Tarde':''}</small>:null}</>:<small>Sin cierre confirmado en 7shifts</small>}</span></div>)}</div></article>})}</div>}
      </>}</section>
      <section className="seven-secondary"><div><h3>Live 7shifts Logbook</h3><p>{logbook.length} entries for the selected period and location scope.</p></div>{data.logbookError&&<div className="detail-block"><label>LOGBOOK CONNECTION</label><p>{data.logbookError}</p><p className="seven-muted">Task compliance remains live; Logbook is isolated so it cannot block Tasks.</p></div>}{logbook.length?<div className="seven-location-table"><table><thead><tr>{['DATE','LOCATION','CATEGORY','AUTHOR','ENTRY','ATTACHMENTS'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{logbook.map(entry=><tr key={entry.id}><td>{entry.date}</td><td>{entry.locationName}</td><td>{entry.category}</td><td>{entry.author}</td><td>{entry.message}</td><td>{entry.attachments}</td></tr>)}</tbody></table></div>:data.logbookError?null:<div className="detail-block"><label>LOGBOOK</label><p>No Logbook entries were returned for this exact period and location selection.</p></div>}</section>
      {data.detailAvailable&&people.length>0?<section className="seven-secondary"><div><h3>Who needs follow-up</h3><p>Live task detail, sorted by missed tasks and late completions.</p></div><div className="seven-location-table"><table><thead><tr>{['PERSON','TASKS','COMPLETED','INCOMPLETE','LATE','COMPLETION'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{people.map((person,index)=>{const rate=person.tasks?100*person.completed/person.tasks:0;return <tr key={`${person.userId??person.userName}-${index}`}><td>{person.userName}</td><td>{person.tasks}</td><td>{person.completed}</td><td className={person.incomplete?'needs-followup':''}>{person.incomplete}</td><td className={person.late?'needs-followup':''}>{person.late}</td><td>{pct(rate)}</td></tr>})}</tbody></table></div></section>:null}
    </>}</div>
  </section>;
}
