import { useEffect, useMemo, useState } from 'react';

type Day={date:string;total:number;completed:number;incomplete:number;completionPct:number|null};
type Person={userId?:number;userName:string;completed:number;incomplete:number;late:number;tasks:number};
type LocationWeek={locationId:number;locationName:string;total:number;completed:number;incomplete:number;completionPct:number|null;detailAvailable?:boolean;days:Day[]};
type LogbookEntry={id:number;date:string;locationName:string;author:string;category:string;message:string;attachments:number};
type Response={source?:string;start?:string;end?:string;total?:number;completed?:number;incomplete?:number;completionPct?:number|null;detailAvailable?:boolean;people?:Person[];locations?:LocationWeek[];logbook?:LogbookEntry[];logbookError?:string;error?:string;configured?:boolean};
const pct=(v:number|null|undefined)=>v===null||v===undefined?'—':`${v.toFixed(1)}%`;
const fmtDate=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
type Period='today'|'yesterday'|'this-week'|'previous-week'|'custom';

function selectedRange(key:Period,customStart:string,customEnd:string){const now=new Date();const day=now.getDay();const sinceWed=(day-3+7)%7;const weekStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()-sinceWed);if(key==='custom')return{start:customStart,end:customEnd};if(key==='today')return{start:iso(now),end:iso(now)};if(key==='yesterday'){const yesterday=new Date(now);yesterday.setDate(yesterday.getDate()-1);return{start:iso(yesterday),end:iso(yesterday)}}if(key==='previous-week'){const start=new Date(weekStart);start.setDate(start.getDate()-7);const end=new Date(start);end.setDate(end.getDate()+6);return{start:iso(start),end:iso(end)}}return{start:iso(weekStart),end:iso(now)};}

export default function SevenShiftsTasksPanel({allowedLocations}:{allowedLocations?:string[]}){
 const today=iso(new Date());
 const [period,setPeriod]=useState<Period>(()=>{if(typeof window==='undefined')return'today';const saved=window.localStorage.getItem('opsvista-tasks-period')??window.sessionStorage.getItem('opsvista-tasks-period');return saved&&['today','yesterday','this-week','previous-week','custom'].includes(saved)?saved as Period:'today'});
 const [customStart,setCustomStart]=useState(()=>typeof window!=='undefined'?(window.localStorage.getItem('opsvista-tasks-custom-start')||today):today);
 const [customEnd,setCustomEnd]=useState(()=>typeof window!=='undefined'?(window.localStorage.getItem('opsvista-tasks-custom-end')||today):today);
 const week=useMemo(()=>selectedRange(period,customStart,customEnd),[period,customStart,customEnd]);const [data,setData]=useState<Response>({});const [loading,setLoading]=useState(true);const [selected,setSelected]=useState('All locations');
 const rangeDays=Math.floor((Date.parse(`${week.end}T00:00:00Z`)-Date.parse(`${week.start}T00:00:00Z`))/86400000)+1;
 const rangeError=!week.start||!week.end||rangeDays<1?'Choose a valid start and end date.':rangeDays>31?'The custom Tasks range can include up to 31 days.':undefined;
 useEffect(()=>{window.sessionStorage.setItem('opsvista-tasks-period',period);window.localStorage.setItem('opsvista-tasks-period',period);window.localStorage.setItem('opsvista-tasks-custom-start',customStart);window.localStorage.setItem('opsvista-tasks-custom-end',customEnd)},[period,customStart,customEnd]);
 useEffect(()=>{if(rangeError){setLoading(false);return}let cancelled=false;const run=async()=>{setLoading(true);try{const params=new URLSearchParams({start:week.start,end:week.end});if(selected!=='All locations')params.set('location',selected);const r=await fetch(`/api/tasks/weekly?${params}`,{credentials:'include',cache:'no-store'});const b=await r.json().catch(()=>({})) as Response;if(!cancelled)setData(b);}catch{if(!cancelled)setData({error:'Unable to load 7shifts Tasks'});}finally{if(!cancelled)setLoading(false);}};void run();return()=>{cancelled=true};},[selected,week.start,week.end,rangeError]);
 const locations=data.locations||[];const people=data.people||[];const logbook=data.logbook||[];const options=allowedLocations?.length?allowedLocations:Array.from(new Set(locations.map(x=>x.locationName)));
 return <section className="panel" style={{marginBottom:16}}><div className="panel-header"><div><h2>7shifts Tasks · Accountability</h2><p>{fmtDate(week.start)}–{fmtDate(week.end)} · Selected period · Bonus minimum 80%</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap',justifyContent:'flex-end'}}><select value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="this-week">This week</option><option value="previous-week">Previous week</option><option value="custom">Custom</option></select>{period==='custom'&&<><input aria-label="Custom start date" type="date" value={customStart} max={customEnd||today} onChange={e=>setCustomStart(e.target.value)}/><input aria-label="Custom end date" type="date" value={customEnd} min={customStart} max={today} onChange={e=>setCustomEnd(e.target.value)}/></>}<select value={selected} onChange={e=>setSelected(e.target.value)}><option>All locations</option>{options.map(x=><option key={x}>{x}</option>)}</select></div></div>
 <div style={{padding:18,display:'grid',gap:14}}>
  {rangeError?<div className="detail-block"><label>DATE RANGE</label><p>{rangeError}</p></div>:loading?<div className="detail-block"><label>7SHIFTS</label><p>Loading live task compliance…</p></div>:data.error?<div className="detail-block"><label>7SHIFTS CONNECTION</label><p>{data.error}</p><p style={{color:'#64748b'}}>Configure the 7shifts credentials in Vercel; no demo task percentage is shown as live.</p></div>:<>
   <div className="metrics-grid"><div className="metric-card"><div className="metric-label">TASK COMPLETION</div><div className="metric-value">{pct(data.completionPct)}</div><div className="metric-note">{data.total?`${data.completed||0} of ${data.total} completed`:'No task records returned'}</div></div><div className="metric-card"><div className="metric-label">INCOMPLETE</div><div className="metric-value">{data.total?data.incomplete||0:'—'}</div><div className="metric-note">Selected period</div></div><div className="metric-card"><div className="metric-label">BONUS GATE</div><div className="metric-value" style={{fontSize:24}}>{data.completionPct===null||data.completionPct===undefined?'Pending':data.completionPct>=80?'PASS':'FAIL'}</div><div className="metric-note">Requires Tasks ≥ 80%</div></div></div>
   {!data.total&&<div className="detail-block"><label>7SHIFTS TASK DATA</label><p>7shifts returned no task records for this exact period and location selection. OpsVista will not interpret an empty response as 0% or 100% compliance.</p></div>}
   <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr>{['LOCATION','COMPLETED','TOTAL','INCOMPLETE','COMPLIANCE','BONUS TASK GATE'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{locations.map(l=><tr key={l.locationId}><td style={{padding:10,fontWeight:800}}>{l.locationName}</td><td style={{padding:10}}>{l.completed}</td><td style={{padding:10}}>{l.total}</td><td style={{padding:10}}>{l.incomplete}</td><td style={{padding:10,fontWeight:850}}>{pct(l.completionPct)}</td><td style={{padding:10,fontWeight:850}}>{l.completionPct===null?'Pending':l.completionPct>=80?'PASS':'FAIL'}</td></tr>)}</tbody></table></div>
   <div style={{display:'grid',gap:10}}><div><h3 style={{margin:'4px 0'}}>Live 7shifts Logbook</h3><p style={{margin:0,color:'#64748b',fontSize:13}}>{logbook.length} entries for the selected period and location scope.</p></div>{data.logbookError&&<div className="detail-block"><label>LOGBOOK CONNECTION</label><p>{data.logbookError}</p><p style={{color:'#64748b'}}>Task compliance remains live; Logbook is isolated so it cannot block Tasks.</p></div>}{logbook.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr>{['DATE','LOCATION','CATEGORY','AUTHOR','ENTRY','ATTACHMENTS'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{logbook.map(entry=><tr key={entry.id}><td style={{padding:10}}>{entry.date}</td><td style={{padding:10,fontWeight:800}}>{entry.locationName}</td><td style={{padding:10}}>{entry.category}</td><td style={{padding:10}}>{entry.author}</td><td style={{padding:10,maxWidth:520}}>{entry.message}</td><td style={{padding:10}}>{entry.attachments}</td></tr>)}</tbody></table></div>:<div className="detail-block"><label>LOGBOOK</label><p>No Logbook entries were returned for this exact period and location selection.</p></div>}</div>
   {data.detailAvailable&&people.length>0?<div style={{display:'grid',gap:10}}><div><h3 style={{margin:'4px 0'}}>Who needs follow-up</h3><p style={{margin:0,color:'#64748b',fontSize:13}}>Live task detail detected from 7shifts. Sorted by missed tasks, then late completions.</p></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:680}}><thead><tr>{['PERSON','TASKS','COMPLETED','INCOMPLETE','LATE','COMPLETION'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{people.map((p,i)=>{const rate=p.tasks?100*p.completed/p.tasks:0;return <tr key={`${p.userId??p.userName}-${i}`}><td style={{padding:10,fontWeight:800}}>{p.userName}</td><td style={{padding:10}}>{p.tasks}</td><td style={{padding:10}}>{p.completed}</td><td style={{padding:10,fontWeight:p.incomplete?800:500}}>{p.incomplete}</td><td style={{padding:10,fontWeight:p.late?800:500}}>{p.late}</td><td style={{padding:10,fontWeight:850}}>{pct(rate)}</td></tr>})}</tbody></table></div></div>:<div className="detail-block"><label>ACCOUNTABILITY DETAIL</label><p>Location-level task compliance is available, but this 7shifts summary response has not exposed reliable person-level detail yet.</p><p style={{color:'#64748b'}}>OpsVista will not guess employee responsibility. The next adapter uses the active Task Lists endpoint for the selected location/date to resolve task-level ownership.</p></div>}
  </>}
 </div></section>;
}
