import { useEffect, useMemo, useState } from 'react';

type Item={id:string;name:string;unit?:string;unitPrice?:number;expectedQty:number;receivedQty?:number;shortageQty?:number;note?:string};
type Transfer={id:string;sourceLocation:string;destinationLocation:string;status:string;receiptStatus:string;createdByName:string;createdAt:string;receiverName?:string;receivedAt?:string;notes?:string;items:Item[]};
type CatalogItem={name:string;category:string;unit:string;unitPrice:number};
const locations=['Stamford','Orange','Fairfield','Danbury','Avon','Southington'];
const units=[
  {value:'ea',label:'Each / Unit'},{value:'order',label:'Order'},{value:'case',label:'Case'},{value:'can',label:'Can'},{value:'lb',label:'Pound (lb)'},{value:'oz',label:'Ounce (oz)'},{value:'gal',label:'Gallon'},{value:'qt',label:'Quart'},{value:'tray',label:'Tray'},{value:'pan',label:'Pan'},{value:'bag',label:'Bag'},{value:'box',label:'Box'},{value:'bottle',label:'Bottle'},{value:'pack',label:'Pack'},{value:'dozen',label:'Dozen'},{value:'other',label:'Other'},
];
const productCatalog:CatalogItem[]=[
  {name:'Pastel de zanahoria',category:'Desserts',unit:'ea',unitPrice:3.83},
  {name:'Tres leches',category:'Desserts',unit:'ea',unitPrice:4.42},
  {name:'Churros',category:'Desserts',unit:'order',unitPrice:1.90},
  {name:'Chocolate Trio',category:'Desserts',unit:'ea',unitPrice:4.67},
  {name:'Pastel de Chocolate',category:'Desserts',unit:'ea',unitPrice:4.60},
  {name:'Cheesecake',category:'Desserts',unit:'ea',unitPrice:2.805},
  {name:'Flan',category:'Desserts',unit:'ea',unitPrice:3.43},
  {name:'Pan de Elote',category:'Desserts',unit:'ea',unitPrice:1.268},
  {name:'Molten',category:'Desserts',unit:'ea',unitPrice:2.035},
  {name:'Chocolate Mousse',category:'Desserts',unit:'ea',unitPrice:1.78},
];
const inputStyle={width:'100%',boxSizing:'border-box' as const,padding:9,border:'1px solid #cbd8e6',borderRadius:8};
const unitLabel=(value?:string)=>units.find(unit=>unit.value===value)?.label??value??'Unit';
const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0);
const sentValue=(item:Item)=>(Number(item.unitPrice)||0)*Number(item.expectedQty||0);
const receivedValue=(item:Item)=>(Number(item.unitPrice)||0)*Number(item.receivedQty||0);
const missingValue=(item:Item)=>(Number(item.unitPrice)||0)*Math.max(0,Number(item.expectedQty||0)-Number(item.receivedQty||0));

export default function TransferLedgerView({allowedLocations=locations}:{allowedLocations?:string[]}){
  const [transfers,setTransfers]=useState<Transfer[]>([]);const [selectedId,setSelectedId]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
  const [source,setSource]=useState('Orange');const [destination,setDestination]=useState('Stamford');const [notes,setNotes]=useState('');const [items,setItems]=useState<Item[]>([{id:'item-1',name:'',unit:'ea',unitPrice:0,expectedQty:1}]);
  const selected=useMemo(()=>transfers.find(t=>t.id===selectedId)||transfers[0],[transfers,selectedId]);
  const [receiptStatus,setReceiptStatus]=useState<'Complete'|'Partial'|'Incomplete'>('Complete');const [receiverName,setReceiverName]=useState('');const [receivedAt,setReceivedAt]=useState('');const [receiveNotes,setReceiveNotes]=useState('');const [receiveItems,setReceiveItems]=useState<Item[]>([]);
  const dispatchTotal=items.reduce((sum,item)=>sum+sentValue(item),0);
  const selectedSentTotal=receiveItems.reduce((sum,item)=>sum+sentValue(item),0);
  const selectedReceivedTotal=receiveItems.reduce((sum,item)=>sum+receivedValue(item),0);
  const selectedMissingTotal=receiveItems.reduce((sum,item)=>sum+missingValue(item),0);
  const locationScopeKey=allowedLocations.join('|');
  const load=async()=>{const res=await fetch('/api/transfers',{credentials:'include',cache:'no-store'});const body=await res.json().catch(()=>({})) as {transfers?:Transfer[]};if(res.ok){const scope=new Set(allowedLocations);const scoped=(body.transfers||[]).filter(transfer=>scope.has(transfer.sourceLocation)||scope.has(transfer.destinationLocation));setTransfers(scoped);setSelectedId(id=>scoped.some(item=>item.id===id)?id:scoped[0]?.id||'');}};
  useEffect(()=>{void load()},[locationScopeKey]);
  useEffect(()=>{if(selected){setReceiveItems(selected.items.map(i=>({...i,receivedQty:i.receivedQty??i.expectedQty,shortageQty:i.shortageQty??0})));setReceiverName(selected.receiverName||'');setReceivedAt(selected.receivedAt?new Date(selected.receivedAt).toISOString().slice(0,16):new Date().toISOString().slice(0,16));setReceiptStatus((selected.receiptStatus==='Partial'||selected.receiptStatus==='Incomplete'?selected.receiptStatus:'Complete') as 'Complete'|'Partial'|'Incomplete');setReceiveNotes(selected.notes||'');}},[selected?.id]);
  const addItem=()=>setItems(v=>[...v,{id:`item-${Date.now()}`,name:'',unit:'ea',unitPrice:0,expectedQty:1}]);
  const changeProduct=(index:number,name:string)=>setItems(v=>v.map((x,i)=>{if(i!==index)return x;const match=productCatalog.find(product=>product.name.toLowerCase()===name.trim().toLowerCase());return match?{...x,name:match.name,unit:match.unit,unitPrice:match.unitPrice}:{...x,name};}));
  const create=async()=>{setLoading(true);setMessage('');const res=await fetch('/api/transfers',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceLocation:source,destinationLocation:destination,items,notes})});const body=await res.json().catch(()=>({})) as {error?:string;transfer?:Transfer};setMessage(res.ok?`Transfer ${body.transfer?.id} created · ${money(dispatchTotal)} dispatched.`:body.error||'Unable to create transfer');if(res.ok){setItems([{id:'item-1',name:'',unit:'ea',unitPrice:0,expectedQty:1}]);setNotes('');await load();if(body.transfer)setSelectedId(body.transfer.id);}setLoading(false);};
  const receive=async()=>{if(!selected)return;setLoading(true);setMessage('');const res=await fetch('/api/transfers',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,action:'receive',receiptStatus,receiverName,receivedAt:new Date(receivedAt).toISOString(),items:receiveItems,notes:receiveNotes})});const body=await res.json().catch(()=>({})) as {error?:string};setMessage(res.ok?`Receipt recorded as ${receiptStatus} · ${money(selectedReceivedTotal)} received${selectedMissingTotal>0?` · ${money(selectedMissingTotal)} missing`:''}.`:body.error||'Unable to record receipt');if(res.ok)await load();setLoading(false);};
  return <div style={{display:'grid',gap:16}}>
    <datalist id="transfer-product-catalog">{productCatalog.map(product=><option key={product.name} value={product.name}>{product.category} · {unitLabel(product.unit)} · {money(product.unitPrice)}</option>)}</datalist>
    <section className="panel"><div className="panel-header"><div><h2>Restaurant Transfer Ledger</h2><p>Permanent chain of custody with quantity, unit cost, transfer value, receiving and shortage reconciliation.</p></div><span className="count-pill">AUDITED</span></div><div style={{padding:18,display:'grid',gap:14}}>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div><label>SOURCE LOCATION</label><select style={inputStyle} value={source} onChange={e=>setSource(e.target.value)}>{locations.map(x=><option key={x}>{x}</option>)}</select></div><div><label>DESTINATION</label><select style={inputStyle} value={destination} onChange={e=>setDestination(e.target.value)}>{locations.map(x=><option key={x}>{x}</option>)}</select></div></div>
      <div style={{display:'grid',gap:8}}>{items.map((item,index)=><div key={item.id} style={{display:'grid',gridTemplateColumns:'1.5fr .75fr .55fr .65fr .7fr auto',gap:8,alignItems:'center'}}><input list="transfer-product-catalog" style={inputStyle} placeholder="Select or type product" value={item.name} onChange={e=>changeProduct(index,e.target.value)}/><select style={inputStyle} value={item.unit||'ea'} onChange={e=>setItems(v=>v.map((x,i)=>i===index?{...x,unit:e.target.value}:x))}>{units.map(unit=><option key={unit.value} value={unit.value}>{unit.label}</option>)}</select><input style={inputStyle} aria-label="Quantity" type="number" min="0" step="0.01" value={item.expectedQty} onChange={e=>setItems(v=>v.map((x,i)=>i===index?{...x,expectedQty:Number(e.target.value)}:x))}/><div style={{position:'relative'}}><span style={{position:'absolute',left:9,top:9,color:'#64748b'}}>$</span><input style={{...inputStyle,paddingLeft:22}} aria-label="Unit price" type="number" min="0" step="0.001" value={item.unitPrice??0} onChange={e=>setItems(v=>v.map((x,i)=>i===index?{...x,unitPrice:Number(e.target.value)}:x))}/></div><div style={{padding:'9px 10px',fontWeight:850,color:'#17263a',background:'#f8fafc',borderRadius:8}}>{money(sentValue(item))}</div><button onClick={()=>setItems(v=>v.filter((_,i)=>i!==index))} disabled={items.length===1}>Remove</button></div>)}</div>
      <div style={{fontSize:12,color:'#64748b'}}>Dessert catalog is active. Selecting an exact catalog product automatically fills its unit and current internal transfer cost. Custom products remain allowed for meats, liquor and other supplies.</div>
      <button onClick={addItem}>+ Add item</button>
      <div style={{display:'flex',justifyContent:'flex-end'}}><div className="impact-box" style={{minWidth:240}}><span>TRANSFER VALUE</span><strong>{money(dispatchTotal)}</strong></div></div>
      <textarea style={inputStyle} placeholder="Dispatch notes" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="primary" disabled={loading||source===destination||items.some(i=>!i.name.trim())} onClick={create}>Create & dispatch transfer</button>
    </div></section>

    <section className="panel"><div className="panel-header"><div><h2>Receive Transfer</h2><p>The receiving location confirms quantity and the dollar value actually received.</p></div><span className="count-pill">{transfers.length} RECORDS</span></div><div style={{padding:18,display:'grid',gap:14}}>
      <select style={inputStyle} value={selected?.id||''} onChange={e=>setSelectedId(e.target.value)}>{transfers.map(t=><option key={t.id} value={t.id}>{t.id} · {t.sourceLocation} → {t.destinationLocation} · {t.receiptStatus}</option>)}</select>
      {selected&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10}}><div className="impact-box"><span>From</span><strong>{selected.sourceLocation}</strong></div><div className="impact-box"><span>To</span><strong>{selected.destinationLocation}</strong></div><div className="impact-box"><span>Sent by</span><strong>{selected.createdByName}</strong></div><div className="impact-box"><span>Sent value</span><strong>{money(selectedSentTotal)}</strong></div></div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10}}><div><label>RECEIVED CONDITION</label><select style={inputStyle} value={receiptStatus} onChange={e=>setReceiptStatus(e.target.value as any)}><option>Complete</option><option>Partial</option><option>Incomplete</option></select></div><div><label>RECEIVED BY · NAME</label><input style={inputStyle} value={receiverName} onChange={e=>setReceiverName(e.target.value)} placeholder="Full name"/></div><div><label>ARRIVAL DATE & TIME</label><input style={inputStyle} type="datetime-local" value={receivedAt} onChange={e=>setReceivedAt(e.target.value)}/></div></div>
      <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:900}}><thead><tr>{['ITEM','UNIT PRICE','EXPECTED','RECEIVED','MISSING','VALUE RECEIVED','VALUE MISSING','RECEIVING NOTE'].map(h=><th key={h} style={{textAlign:'left',padding:9,borderBottom:'1px solid #e5ecf3'}}>{h}</th>)}</tr></thead><tbody>{receiveItems.map((item,index)=>{const shortage=Math.max(0,item.expectedQty-(item.receivedQty??0));return <tr key={item.id}><td style={{padding:9}}><strong>{item.name}</strong><div style={{fontSize:11,color:'#64748b'}}>{unitLabel(item.unit)}</div></td><td style={{padding:9,fontWeight:700}}>{money(item.unitPrice??0)}</td><td style={{padding:9}}>{item.expectedQty} {item.unit}</td><td style={{padding:9}}><input style={{...inputStyle,maxWidth:110}} type="number" min="0" step="0.01" value={item.receivedQty??0} onChange={e=>setReceiveItems(v=>v.map((x,i)=>i===index?{...x,receivedQty:Number(e.target.value),shortageQty:Math.max(0,x.expectedQty-Number(e.target.value))}:x))}/></td><td style={{padding:9,fontWeight:800,color:shortage>0?'#b45309':'#166534'}}>{shortage} {item.unit}</td><td style={{padding:9,fontWeight:800,color:'#166534'}}>{money(receivedValue(item))}</td><td style={{padding:9,fontWeight:800,color:missingValue(item)>0?'#b45309':'#166534'}}>{money(missingValue(item))}</td><td style={{padding:9}}><input style={inputStyle} value={item.note||''} onChange={e=>setReceiveItems(v=>v.map((x,i)=>i===index?{...x,note:e.target.value}:x))} placeholder={shortage>0?'Explain shortage / damage':'Optional note'}/></td></tr>})}</tbody></table></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><div className="impact-box"><span>VALUE SENT</span><strong>{money(selectedSentTotal)}</strong></div><div className="impact-box"><span>VALUE RECEIVED</span><strong>{money(selectedReceivedTotal)}</strong></div><div className="impact-box"><span>VALUE MISSING</span><strong>{money(selectedMissingTotal)}</strong></div></div>
      <textarea style={inputStyle} value={receiveNotes} onChange={e=>setReceiveNotes(e.target.value)} placeholder="Receiving notes, damaged items, second delivery expected, etc."/><button className="primary" disabled={loading||!receiverName.trim()||!receivedAt} onClick={receive}>Record receipt</button></>}
      {message&&<div className="detail-block"><label>TRANSFER LEDGER</label><p>{message}</p></div>}
    </div></section>
  </div>;
}
