import { beverageBonusRange, closedBonusWeek, easternDay } from '../shared/bonusWeek';
import { useBeverageScore } from './useBeverageScore';
import type { BeverageScoreRow } from '../shared/beverageScore';
import { useEffect, useMemo, useState } from 'react';
import { calculateWeeklyBonus } from './bonusEngine';
import CustomDateRangePicker from './CustomDateRangePicker';

type Period='today'|'yesterday'|'this-week'|'previous-week'|'this-month'|'last-30-days'|'custom';
type TaskLocation={locationName:string;completionPct:number|null};
type LogbookEntry={date:string;locationName:string};
type TaskResponse={locations?:TaskLocation[];logbook?:LogbookEntry[];logbookComplete?:boolean;logbookError?:string;error?:string};
type ToastLocation={location:string;netSales?:number;discountAmount?:number;discountPct:number;bonusDiscountPct?:number;bonusDiscountAmount?:number;uberEatsDiscountAmount?:number;employeeMealDiscountAmount?:number;voidPct:number;overtimeLaborPct?:number};
type ToastResponse={locations?:ToastLocation[];error?:string};
type ReviewLocation={location:string;reviewCount:number;averageRating:number|null;lowRatingCount:number;unansweredCount:number;minimumMet:boolean;scorePct:number;mappingError?:string};
type ReviewsResponse={locations?:ReviewLocation[];error?:string;configured?:boolean;source?:string;lastUpdated?:string|null};
type Row={location:string;rank:number;alcohol?:BeverageScoreRow;netSales?:number;totalDiscounts?:number;bonusDiscountAmount?:number;tasks?:number;discounts?:number;uberEatsExcluded?:number;employeeMealsExcluded?:number;voids?:number;ot?:number;reviews?:ReviewLocation;reviewAverage?:number;reviewCount?:number;leadershipPct?:number;logbookCount:number;logbookTarget:number;points:number;availableMax:number;eligible:boolean|null;failed:string[]};

const locationsDefault=['Stamford','Orange','Fairfield','Danbury','Avon','Southington'];
const usd=(v:number|undefined)=>v===undefined?'Pendiente':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const pct=(v:number|undefined,digits=1)=>v===undefined?'Pending':`${v.toFixed(digits)}%`;
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function selectedRange(key:Period,customStart:string,customEnd:string){const instant=new Date();if(key==='previous-week')return closedBonusWeek(instant);const now=new Date(`${easternDay(instant)}T12:00:00`);const sinceWed=(now.getDay()-3+7)%7;const weekStart=new Date(now.getFullYear(),now.getMonth(),now.getDate()-sinceWed);if(key==='custom')return{start:customStart,end:customEnd};if(key==='today')return{start:iso(now),end:iso(now)};if(key==='yesterday'){const yesterday=new Date(now);yesterday.setDate(yesterday.getDate()-1);return{start:iso(yesterday),end:iso(yesterday)}}if(key==='this-month')return{start:iso(new Date(now.getFullYear(),now.getMonth(),1)),end:iso(now)};if(key==='last-30-days'){const start=new Date(now);start.setDate(start.getDate()-29);return{start:iso(start),end:iso(now)}}return{start:iso(weekStart),end:iso(now)};}

export default function WeeklyBonusLivePanel({allowedLocations,canReadRestaurant365=false,onOpenRestaurant365}:{allowedLocations?:string[];canReadRestaurant365?:boolean;onOpenRestaurant365?:(start:string,end:string)=>void}){
  const today=easternDay();
  const [includeEmployeeMeals,setIncludeEmployeeMeals]=useState(false);
  const [includeUberEats,setIncludeUberEats]=useState(false);
  const comparing=includeEmployeeMeals||includeUberEats;
  const [period,setPeriod]=useState<Period>('previous-week');
  const [customStart,setCustomStart]=useState(()=>typeof window!=='undefined'?(window.localStorage.getItem('opsvista-bonus-custom-start')||today):today);
  const [customEnd,setCustomEnd]=useState(()=>typeof window!=='undefined'?(window.localStorage.getItem('opsvista-bonus-custom-end')||today):today);
  const [selected,setSelected]=useState(()=>typeof window!=='undefined'?window.sessionStorage.getItem('opsvista-bonus-location')||'All locations':'All locations');
  const range=useMemo(()=>selectedRange(period,customStart,customEnd),[period,customStart,customEnd]);
  const rangeDays=Math.floor((Date.parse(`${range.end}T00:00:00Z`)-Date.parse(`${range.start}T00:00:00Z`))/86400000)+1;
  const rangeError=!range.start||!range.end||rangeDays<1?'Selecciona una fecha inicial y final válidas.':rangeDays>31?'El rango personalizado puede incluir hasta 31 días.':undefined;
  const alcoholRange=useMemo(()=>rangeError?range:beverageBonusRange(range.end),[range.start,range.end,rangeError]);
  const alcohol=useBeverageScore(alcoholRange.start,alcoholRange.end,!rangeError);
  const [tasks,setTasks]=useState<TaskResponse>({});const [toast,setToast]=useState<ToastResponse>({});const [reviews,setReviews]=useState<ReviewsResponse>({});const [loading,setLoading]=useState(true);
  const scope=allowedLocations?.length?allowedLocations:locationsDefault;
  useEffect(()=>{window.sessionStorage.setItem('opsvista-bonus-period',period);window.localStorage.setItem('opsvista-bonus-period',period);window.localStorage.setItem('opsvista-bonus-period-v2','1');window.localStorage.setItem('opsvista-bonus-custom-start',customStart);window.localStorage.setItem('opsvista-bonus-custom-end',customEnd)},[period,customStart,customEnd]);
  useEffect(()=>{window.sessionStorage.setItem('opsvista-bonus-location',selected)},[selected]);
  useEffect(()=>{if(selected!=='All locations'&&!scope.includes(selected))setSelected('All locations')},[selected,scope.join('|')]);
  useEffect(()=>{if(rangeError){setTasks({});setToast({});setReviews({});setLoading(false);return}let cancelled=false;const run=async()=>{setLoading(true);setTasks({});setToast({});setReviews({});const qs=new URLSearchParams({start:range.start,end:range.end});const [tr,sr,rr]=await Promise.allSettled([fetch(`/api/tasks/weekly?${qs}`,{credentials:'include',cache:'no-store'}),fetch(`/api/operations/performance?${qs}`,{credentials:'include',cache:'no-store'}),fetch(`/api/google-business/reviews?${qs}`,{credentials:'include',cache:'no-store'})]);
    const read=async<T,>(result:PromiseSettledResult<Response>,label:string):Promise<T>=>{
      if(result.status==='rejected')return {error:`${label} unavailable`} as T;
      const body=await result.value.json().catch(()=>({error:`${label}: respuesta inválida`})) as T & {error?:string};
      return result.value.ok?body:{error:body.error||`${label} unavailable`} as T;
    };
    const [taskData,toastData,reviewData]=await Promise.all([read<TaskResponse>(tr,'7shifts'),read<ToastResponse>(sr,'Toast'),read<ReviewsResponse>(rr,'Google Business Profile')]);
    if(cancelled)return;
    setTasks(taskData);setToast(toastData);setReviews(reviewData);
    setLoading(false);};void run();return()=>{cancelled=true};},[range.start,range.end,rangeError]);
  const visibleScope=selected==='All locations'?scope:[selected];
  const rows=useMemo<Row[]>(()=>scope.map(location=>{
    const t=tasks.locations?.find(x=>x.locationName.toLowerCase().includes(location.toLowerCase())||location.toLowerCase().includes(x.locationName.toLowerCase()))?.completionPct??undefined;
    const s=toast.locations?.find(x=>x.location.toLowerCase().includes(location.toLowerCase())||location.toLowerCase().includes(x.location.toLowerCase()));
    const review=reviews.locations?.find(x=>x.location.toLowerCase().includes(location.toLowerCase())||location.toLowerCase().includes(x.location.toLowerCase()));
    const locationLogs=(tasks.logbook||[]).filter(x=>x.locationName.toLowerCase().includes(location.toLowerCase())||location.toLowerCase().includes(x.locationName.toLowerCase()));
    const logbookCount=new Set(locationLogs.map(x=>x.date)).size;
    const logbookTarget=Math.max(1,Math.ceil(rangeDays/7*4));
    const logbookAvailable=tasks.logbook!==undefined&&!tasks.logbookError&&tasks.logbookComplete!==false;
    const leadershipPct=logbookAvailable?Math.min(100,logbookCount/logbookTarget*100):undefined;
    const bonusDiscountPct=s?.bonusDiscountPct;
    const reviewAverage=review?.averageRating??undefined,reviewCount=review?.reviewCount;
    const alcoholRow=alcohol.data?.rows.find(row=>row.location===location);
    const result=calculateWeeklyBonus({liquorCostScorePct:alcoholRow?.points==null?undefined:alcoholRow.points*20,tasksPct:t??undefined,discountsPct:bonusDiscountPct,voidsPct:s?.voidPct,overtimeLaborPct:s?.overtimeLaborPct,reviewAverage,reviewCount,leadershipScorePct:leadershipPct,logbookComplete:leadershipPct===undefined?undefined:logbookCount>=logbookTarget});
    const ready=result.metrics.filter(m=>m.ready);return{location,alcohol:alcoholRow,netSales:s?.netSales,totalDiscounts:s?.discountAmount,bonusDiscountAmount:s?.bonusDiscountAmount,tasks:t??undefined,discounts:bonusDiscountPct,uberEatsExcluded:s?.uberEatsDiscountAmount,employeeMealsExcluded:s?.employeeMealDiscountAmount,voids:s?.voidPct,ot:s?.overtimeLaborPct,reviews:review,reviewAverage,reviewCount,leadershipPct,logbookCount,logbookTarget,points:ready.reduce((n,m)=>n+(m.points??0),0),availableMax:ready.reduce((n,m)=>n+m.weight,0),eligible:result.eligible,failed:result.eligibilityReasons};
  }).sort((a,b)=>{const aScore=a.availableMax?a.points/a.availableMax:-1;const bScore=b.availableMax?b.points/b.availableMax:-1;return bScore-aScore||b.points-a.points||a.location.localeCompare(b.location)}).map((row,index)=>({...row,rank:index+1})).filter(row=>visibleScope.includes(row.location)),[scope.join('|'),visibleScope.join('|'),tasks,toast,reviews,rangeDays,alcohol.data]);
  return <section className="panel" style={{marginBottom:16}}><div className="panel-header"><div><h2>Bono semanal · Ranking de managers</h2><p>{range.start} → {range.end} · Corte semanal: miércoles a martes. Preparación automática cada miércoles de madrugada (Connecticut).</p></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><span className="count-pill">{loading?'SYNCING':reviews.source==='Vista Social CSV'?'VISTA SOCIAL':'LIVE SOURCES'}</span><select aria-label="Período del bono" value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="today">Hoy</option><option value="yesterday">Ayer</option><option value="this-week">Semana en curso</option><option value="previous-week">Última semana cerrada</option><option value="this-month">Este mes</option><option value="last-30-days">Últimos 30 días</option><option value="custom">Personalizado</option></select><CustomDateRangePicker active={period==='custom'} start={customStart} end={customEnd} maxDate={today} maxRangeDays={31} onApply={(start,end)=>{setCustomStart(start);setCustomEnd(end);}} ariaLabel="Seleccionar periodo de Bono semanal"/><select aria-label="Locación del bono" value={selected} onChange={e=>setSelected(e.target.value)}><option>All locations</option>{scope.map(location=><option key={location}>{location}</option>)}</select></div></div><div style={{padding:18,display:'grid',gap:12}}>
    <details style={{padding:12,border:'1px solid #cbd5e1',borderRadius:10}}><summary style={{cursor:'pointer'}}>Comparar descuentos · empleados y Uber Eats</summary>
      <div style={{display:'flex',gap:18,flexWrap:'wrap'}}>
        <label style={{display:'flex',gap:8,alignItems:'center',cursor:'pointer'}}><input type="checkbox" role="switch" checked={includeEmployeeMeals} onChange={e=>setIncludeEmployeeMeals(e.target.checked)}/> Incluir descuentos de empleados</label>
        <label style={{display:'flex',gap:8,alignItems:'center',cursor:'pointer'}}><input type="checkbox" role="switch" checked={includeUberEats} onChange={e=>setIncludeUberEats(e.target.checked)}/> Incluir descuentos de Uber Eats</label>
        {comparing&&<button type="button" onClick={()=>{setIncludeEmployeeMeals(false);setIncludeUberEats(false);}}>Volver al bono oficial</button>}
      </div>
      <span style={{fontSize:14,color:'#475569'}}>{comparing?'Los interruptores cambian el importe y porcentaje mostrados para comparar. Los puntos, ranking y elegibilidad conservan las exclusiones del bono oficial.':'Activa uno o ambos interruptores para comparar. Al volver a entrar, ambos estarán apagados.'}</span>
    </details>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',fontSize:14}}><span><strong>Alcohol · últimas 8 semanas:</strong> {alcoholRange.start} → {alcoholRange.end}. Menor compra / venta, más puntos. {alcohol.error?'Revisión pendiente.':!alcohol.data?'Abriendo datos guardados…':alcohol.data.periodOpen?`Período en curso · ${alcohol.data.readyCount} de ${alcohol.data.expectedCount} locaciones conciliadas · resultados provisionales.`:alcohol.data.provisional?`Ranking provisional · ${alcohol.data.readyCount} de ${alcohol.data.expectedCount} locaciones conciliadas.`:'Seis locaciones conciliadas.'}</span>{canReadRestaurant365&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" disabled={Boolean(rangeError)||alcohol.refreshing} onClick={()=>void alcohol.refresh()}>{alcohol.refreshing?'Actualizando datos de alcohol…':'Actualizar datos de alcohol'}</button>{onOpenRestaurant365&&<button type="button" onClick={()=>onOpenRestaurant365(alcoholRange.start,alcoholRange.end)}>Detalle en Restaurant365 →</button>}</div>}</div>
    {alcohol.refreshNotice&&<p role="status" style={{margin:0,fontSize:13,color:'#475569'}}>{alcohol.refreshNotice}</p>}
    {rangeError&&<div className="detail-block"><label>RANGO DE FECHAS</label><p>{rangeError}</p></div>}
    {(tasks.error||tasks.logbookError||toast.error||reviews.error)&&<div className="detail-block"><label>ESTADO DE FUENTES</label><p>{tasks.error?`7shifts: ${tasks.error}. `:''}{tasks.logbookError?`7shifts Logbook: ${tasks.logbookError}. `:''}{toast.error?`Toast: ${toast.error}. `:''}{reviews.error?`Google Reviews: ${reviews.error}.`:''}</p><p style={{color:'#64748b'}}>Las fuentes faltantes permanecen pendientes; OpsVista no sustituye números de prueba ni penaliza Logbook con datos incompletos.</p></div>}
    <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1060}}><thead><tr>{['PUESTO','LOCACIÓN','PUNTOS','ALCOHOL · 5','TASKS · 35',comparing?'DESCUENTOS · COMPARACIÓN':'DESCUENTOS · 20','VOIDS · 15','OT · 15','RESEÑAS · 5','LOGBOOK · 5','CALIFICACIÓN'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=>{
      const amount=r.bonusDiscountAmount===undefined||(includeEmployeeMeals&&r.employeeMealsExcluded===undefined)||(includeUberEats&&r.uberEatsExcluded===undefined)?undefined:r.bonusDiscountAmount+(includeEmployeeMeals?r.employeeMealsExcluded!:0)+(includeUberEats?r.uberEatsExcluded!:0);
      const displayPct=comparing?(amount!==undefined&&r.netSales!==undefined&&r.netSales>0?amount/r.netSales*100:undefined):r.discounts;
      return <tr key={r.location}><td style={{padding:10,fontWeight:900}}>#{r.rank}</td><td style={{padding:10,fontWeight:850}}>{r.location}</td><td style={{padding:10,fontWeight:850}}>{r.availableMax?`${r.points.toFixed(1)} / ${r.availableMax}`:'Pending'}</td><td style={{padding:10}}><strong>{r.alcohol?.purchasePct==null?'Pendiente':pct(r.alcohol.purchasePct,2)}</strong><small style={{display:'block',marginTop:3,fontWeight:700}}>{r.alcohol?.points==null?'Puntos pendientes':`${r.alcohol.points} / 5 pts · #${r.alcohol.rank}${alcohol.data?.provisional?' provisional':''}`}</small><details><summary style={{fontSize:12,cursor:'pointer'}}>Ver cálculo</summary>{canReadRestaurant365&&<small style={{display:'block'}}>Compras: {usd(r.alcohol?.purchases??undefined)} · Ventas netas de alcohol: {usd(r.alcohol?.sales??undefined)}</small>}<small style={{display:'block'}}>{r.alcohol?.issues.join(' · ')||'Facturas de compra menos créditos / ventas netas de alcohol en ocho semanas.'}</small></details></td><td style={{padding:10,fontWeight:700}}>{pct(r.tasks)}</td><td style={{padding:10}}><strong>{pct(displayPct,2)}</strong><small style={{display:'block',marginTop:3,fontWeight:700}}>{comparing?'Total de comparación':'Para bono'}: {usd(amount)}</small><details><summary style={{fontSize:12,cursor:'pointer'}}>Ver exclusiones</summary><small style={{display:'block',marginTop:3,color:'#64748b'}}>Total Toast: {usd(r.totalDiscounts)}</small><small style={{display:'block',marginTop:3,color:'#64748b'}}>{r.uberEatsExcluded===undefined?'Exclusión pendiente':`${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(r.uberEatsExcluded)} Uber Eats ${includeUberEats?'incluido en comparación':'excluido'}`}</small><small style={{display:'block',marginTop:3,color:'#64748b'}}>{r.employeeMealsExcluded===undefined?'Comida empleados: exclusión pendiente':`${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(r.employeeMealsExcluded)} empleados ${includeEmployeeMeals?'incluidos en comparación':'excluidos'}`}</small><small style={{display:'block',marginTop:3}}>Bono oficial: {usd(r.bonusDiscountAmount)} ({pct(r.discounts,2)}) · Ventas netas: {usd(r.netSales)}</small></details></td><td style={{padding:10}}>{pct(r.voids,2)}</td><td style={{padding:10}}>{pct(r.ot,2)}</td><td style={{padding:10}}>{r.reviewAverage===undefined?'Pending':<><strong>{r.reviewAverage.toFixed(2)} ★</strong><small style={{display:'block',marginTop:3,color:'#64748b'}}>{r.reviewCount} reviews · mín. 5</small></>}</td><td style={{padding:10}}><strong>{pct(r.leadershipPct,0)}</strong><small style={{display:'block',marginTop:3,color:'#64748b'}}>{r.leadershipPct===undefined?'Fuente pendiente':`${r.logbookCount}/${r.logbookTarget} días con Logbook`}</small></td><td style={{padding:10,fontWeight:800,color:r.failed.length?'#b45309':r.eligible?'#16803f':'#64748b'}}>{r.failed.length?r.failed.join(' · '):r.eligible?'Calificado':'Fuentes pendientes'}</td></tr>})}</tbody></table></div>
    {alcohol.data && <details style={{padding:12,border:'1px solid #cbd5e1',borderRadius:10}} open>
      <summary style={{cursor:'pointer',fontWeight:700}}>Compras Provi integradas · control del bono</summary>
      <p style={{fontSize:13,color:'#475569'}}>Último reporte guardado por locación que cruza la ventana de alcohol. Su total incluye productos de bar y puede contener mezcladores y bebidas sin alcohol. Las calificaciones usan las compras y ventas conciliadas de las ocho semanas; este reporte permite revisar su cobertura.</p>
      <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:650}}>
        <thead><tr>{['LOCACIÓN','PERÍODO DEL REPORTE',...(canReadRestaurant365?['TOTAL PROVI']:[]),'CONCILIACIÓN DEL REPORTE','USO EN EL BONO'].map(label=><th key={label} style={{textAlign:'left',padding:8}}>{label}</th>)}</tr></thead>
        <tbody>{rows.map(row=><tr key={row.location}>
          <th scope="row" style={{textAlign:'left',padding:8}}>{row.location}</th>
          <td style={{padding:8}}>{row.alcohol?.provi?`${row.alcohol.provi.start} → ${row.alcohol.provi.end}`:'Sin reporte guardado para esta ventana'}</td>
          {canReadRestaurant365&&<td style={{padding:8}}>{usd(row.alcohol?.provi?.spend??undefined)}</td>}
          <td style={{padding:8}}>{row.alcohol?.provi?`${row.alcohol.provi.covered}/${row.alcohol.provi.expected} bloques R365 · ${row.alcohol.provi.reconciliationPending?'Pendiente':'Actualizado'}`:'Pendiente'}</td>
          <td style={{padding:8,fontSize:13}}>{row.alcohol?.provi?(row.alcohol.provi.periodMatches?'Referencia del mismo período.':'Referencia de otro período; sin prorratear.'):'Las facturas y evidencias disponibles siguen alimentando el cálculo.'} {row.alcohol?.provi&&'No se suma a R365 ni a reportes anteriores.'}</td>
        </tr>)}</tbody>
      </table></div>
    </details>}
    <details style={{fontSize:13,color:'#475569'}}><summary style={{cursor:'pointer'}}>Reglas del bono y estado de alcohol</summary>
      <p>Alcohol: facturas de compra menos créditos ÷ ventas netas de destilados, cócteles, cerveza y vino × 100, en las últimas 8 semanas hasta el cierre seleccionado. Las facturas pendientes de aprobación de pago ya forman parte de las compras. Las demás métricas conservan el período del bono. Es eficiencia de compras; la utilidad requiere inventarios.</p>
      <p>De menor a mayor porcentaje: 5, 4, 3, 2, 1 y 0 puntos. Los empates comparten puesto y puntos; el siguiente puesto salta las posiciones empatadas. Se necesitan al menos dos locaciones conciliadas. Los resultados son provisionales mientras falten locaciones y se recalculan al incorporar sus datos.</p>
      <p>Una locación sin compras identificadas o con información incompleta conserva puntos pendientes. El miércoles prepara la evaluación, pero puedes actualizarla después si llegan facturas tarde. Las órdenes con evidencia conciliada conservan su fecha de orden y usan el monto final de R365; las demás compras conservan la fecha de factura. Los reportes Provi agregados mantienen sus fechas originales y no se reparten entre semanas ni se suman a las facturas. El período en curso es provisional: los pedidos y las facturas todavía pueden incorporarse. Para evaluar una semana cerrada, selecciona Última semana cerrada. Filtrar una locación no cambia su puesto de alcohol. Las facturas, créditos, productos y reportes Provi se revisan en Restaurant365 → Alcohol o Compras Provi.</p>
      <p>Ranking general: puntos obtenidos ÷ puntos disponibles. Pesos: Tasks 35, Descuentos 20, Voids 15, OT 15, Reseñas 5, Alcohol 5 y Logbook 5. Los descuentos excluyen Uber Eats y comidas de empleados; límite 2%. Logbook aporta puntos y no bloquea la calificación. Reseñas exige mínimo cinco; calidad 80% y volumen 20%.</p>
      {alcohol.error&&<p role="status">{alcohol.error} {alcohol.data?'Se conserva la última evaluación guardada; la revisión está pendiente.':''}</p>}
      {alcohol.data?.updatedAt&&<p>Última copia de alcohol: {new Date(alcohol.data.updatedAt).toLocaleString('es-MX',{timeZone:'America/New_York'})} (Connecticut).</p>}
    </details>
  </div></section>;
}
