import postgres from 'postgres';
import type { SessionUser } from './authSession.js';

export type PaymentStatus='Pending Approval'|'Approved'|'Rejected'|'Paid';
export type PaymentRequest={
  id:string;organizationId:string;location:string;requestDate:string;title:string;payee:string;amount:number;reason:string;
  requestedById:string;requestedByName:string;requestedAt:string;status:PaymentStatus;
  approvedById?:string;approvedByName?:string;approvedAt?:string;approvalNote?:string;
  checkNumber?:string;checkDate?:string;issuedById?:string;issuedByName?:string;issuedAt?:string;paymentNote?:string;updatedAt:string;
};
let client:ReturnType<typeof postgres>|undefined;let initialized=false;
function databaseUrl(){return process.env.OPSVISTA_DATABASE_URL||process.env.OPSVISTA_DATABASE_DATABASE_URL||'';}
function sql(){const url=databaseUrl();if(!url)throw new Error('OpsVista database URL is not configured');if(!client)client=postgres(url,{max:4,idle_timeout:20,connect_timeout:10});return client;}
async function ensureSchema(){if(initialized)return;const db=sql();await db`create table if not exists opsvista_payment_requests (
 id text primary key, organization_id text not null, location text not null, request_date date not null, title text not null, payee text not null, amount numeric(12,2) not null, reason text not null,
 requested_by_id text not null, requested_by_name text not null, requested_at timestamptz not null, status text not null default 'Pending Approval',
 approved_by_id text, approved_by_name text, approved_at timestamptz, approval_note text,
 check_number text, check_date date, issued_by_id text, issued_by_name text, issued_at timestamptz, payment_note text, updated_at timestamptz not null default now()
)`;await db`create table if not exists opsvista_payment_audit (
 id text primary key, payment_id text not null, at timestamptz not null, actor_id text not null, actor_name text not null, action text not null, before_value text, after_value text, reason text not null
)`;await db`create index if not exists opsvista_payments_status_idx on opsvista_payment_requests(status,request_date desc)`;await db`create index if not exists opsvista_payments_location_idx on opsvista_payment_requests(location,request_date desc)`;await db`create index if not exists opsvista_payment_audit_idx on opsvista_payment_audit(payment_id,at desc)`;initialized=true;}
function norm(r:Record<string,unknown>):PaymentRequest{return {id:String(r.id),organizationId:String(r.organization_id),location:String(r.location),requestDate:String(r.request_date).slice(0,10),title:String(r.title),payee:String(r.payee),amount:Number(r.amount),reason:String(r.reason),requestedById:String(r.requested_by_id),requestedByName:String(r.requested_by_name),requestedAt:new Date(String(r.requested_at)).toISOString(),status:String(r.status) as PaymentStatus,approvedById:r.approved_by_id?String(r.approved_by_id):undefined,approvedByName:r.approved_by_name?String(r.approved_by_name):undefined,approvedAt:r.approved_at?new Date(String(r.approved_at)).toISOString():undefined,approvalNote:r.approval_note?String(r.approval_note):undefined,checkNumber:r.check_number?String(r.check_number):undefined,checkDate:r.check_date?String(r.check_date).slice(0,10):undefined,issuedById:r.issued_by_id?String(r.issued_by_id):undefined,issuedByName:r.issued_by_name?String(r.issued_by_name):undefined,issuedAt:r.issued_at?new Date(String(r.issued_at)).toISOString():undefined,paymentNote:r.payment_note?String(r.payment_note):undefined,updatedAt:new Date(String(r.updated_at)).toISOString()};}
function canSee(user:SessionUser,p:PaymentRequest){return ['Founder','Corporate','Administration'].includes(user.role)||user.locations.includes(p.location)||p.requestedById===user.id;}
function aid(){return `pa-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;}
export async function listPayments(user:SessionUser){await ensureSchema();const rows=await sql()`select * from opsvista_payment_requests order by requested_at desc limit 500`;return rows.map(r=>norm(r)).filter(p=>canSee(user,p));}
export async function getPayment(id:string){await ensureSchema();const rows=await sql()`select * from opsvista_payment_requests where id=${id} limit 1`;return rows[0]?norm(rows[0]):null;}
export async function createPayment(input:{location:string;requestDate:string;title:string;payee:string;amount:number;reason:string},actor:SessionUser){await ensureSchema();const id=`PAY-${Date.now().toString(36).toUpperCase()}`;const at=new Date().toISOString();const org=actor.organizationId||'org-puerto-vallarta';await sql().begin(async tx=>{await tx`insert into opsvista_payment_requests(id,organization_id,location,request_date,title,payee,amount,reason,requested_by_id,requested_by_name,requested_at,status) values(${id},${org},${input.location},${input.requestDate},${input.title},${input.payee},${input.amount},${input.reason},${actor.id},${actor.name},${at},'Pending Approval')`;await tx`insert into opsvista_payment_audit(id,payment_id,at,actor_id,actor_name,action,after_value,reason) values(${aid()},${id},${at},${actor.id},${actor.name},'Payment requested','Pending Approval',${input.reason})`;});return getPayment(id);}
export async function decidePayment(id:string,decision:'Approved'|'Rejected',note:string,actor:SessionUser){await ensureSchema();const p=await getPayment(id);if(!p)throw new Error('Payment request not found');if(p.status!=='Pending Approval')throw new Error('Only pending requests can be approved or rejected');const at=new Date().toISOString();await sql().begin(async tx=>{await tx`update opsvista_payment_requests set status=${decision},approved_by_id=${actor.id},approved_by_name=${actor.name},approved_at=${at},approval_note=${note||null},updated_at=now() where id=${id}`;await tx`insert into opsvista_payment_audit(id,payment_id,at,actor_id,actor_name,action,before_value,after_value,reason) values(${aid()},${id},${at},${actor.id},${actor.name},'Approval decision','Pending Approval',${decision},${note||decision})`;});return getPayment(id);}
export async function issuePayment(id:string,input:{checkNumber:string;checkDate:string;note?:string},actor:SessionUser){await ensureSchema();const p=await getPayment(id);if(!p)throw new Error('Payment request not found');if(p.status!=='Approved')throw new Error('Only approved requests can be issued');const at=new Date().toISOString();await sql().begin(async tx=>{await tx`update opsvista_payment_requests set status='Paid',check_number=${input.checkNumber},check_date=${input.checkDate},issued_by_id=${actor.id},issued_by_name=${actor.name},issued_at=${at},payment_note=${input.note??null},updated_at=now() where id=${id}`;await tx`insert into opsvista_payment_audit(id,payment_id,at,actor_id,actor_name,action,before_value,after_value,reason) values(${aid()},${id},${at},${actor.id},${actor.name},'Check issued','Approved',${`Paid · Check ${input.checkNumber}`},${input.note||'Approved payment issued'})`;});return getPayment(id);}
export async function paymentAudit(id:string){await ensureSchema();return await sql()`select * from opsvista_payment_audit where payment_id=${id} order by at desc`;}
