import postgres from 'postgres';
import { getToastEmployeeRoster } from './toastPerformance.js';

export type TeamEmployee={opsvistaEmployeeId:string;toastEmployeeGuid:string;externalEmployeeId:string;firstName:string;lastName:string;email:string;phone:string;hireDate:string;position:string;location:string;additionalLocations:string[];status:'Active'|'Inactive'};

let client:ReturnType<typeof postgres>|undefined,initialized=false;
function db(){const url=process.env.OPSVISTA_DATABASE_URL||process.env.OPSVISTA_DATABASE_DATABASE_URL||'';if(!url)throw new Error('OpsVista database URL is not configured');return client??=postgres(url,{max:4,idle_timeout:20,connect_timeout:10});}
async function schema(){if(initialized)return;await db()`create table if not exists opsvista_team_employees (organization_id text not null, toast_employee_guid text not null, opsvista_employee_id text not null, external_employee_id text not null default '', first_name text not null default '', last_name text not null default '', email text not null default '', phone text not null default '', hire_date text not null default '', position text not null default '', primary_location text not null default '', additional_locations jsonb not null default '[]'::jsonb, status text not null default 'Active', source text not null default 'Toast', synced_at timestamptz not null default now(), primary key(organization_id,toast_employee_guid))`;initialized=true;}
export async function syncTeamFromToast(organizationId='org-puerto-vallarta',locations?:string[]){await schema();const roster=await getToastEmployeeRoster(locations);const sql=db();for(const e of roster){await sql`insert into opsvista_team_employees (organization_id,toast_employee_guid,opsvista_employee_id,external_employee_id,first_name,last_name,email,phone,hire_date,position,primary_location,additional_locations,status,source,synced_at) values (${organizationId},${e.toastEmployeeGuid},${e.opsvistaEmployeeId},${e.externalEmployeeId},${e.firstName},${e.lastName},${e.email},${e.phone},${e.hireDate},${e.position},${e.location},${sql.json(e.additionalLocations)},${e.status},'Toast',now()) on conflict (organization_id,toast_employee_guid) do update set external_employee_id=excluded.external_employee_id,first_name=excluded.first_name,last_name=excluded.last_name,email=excluded.email,phone=excluded.phone,hire_date=excluded.hire_date,position=excluded.position,primary_location=excluded.primary_location,additional_locations=excluded.additional_locations,status=excluded.status,synced_at=now()`;}return roster;}
export async function listTeamEmployees(organizationId='org-puerto-vallarta'){await schema();const rows=await db()`select * from opsvista_team_employees where organization_id=${organizationId} order by status,first_name,last_name`;return rows.map((r:any)=>({opsvistaEmployeeId:r.opsvista_employee_id,toastEmployeeGuid:r.toast_employee_guid,externalEmployeeId:r.external_employee_id,firstName:r.first_name,lastName:r.last_name,email:r.email,phone:r.phone,hireDate:r.hire_date,position:r.position,location:r.primary_location,additionalLocations:Array.isArray(r.additional_locations)?r.additional_locations:[],status:r.status}));}
